In [1]:
import requests as req
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import re

In [2]:
url1 = "https://www.cars24.com/buy-used-car?sort=lhl&serveWarrantyCount=true&listingSource=Homepage_Filters&storeCityId=3686&pinId=500001"
resp = req.get(url1)
resp.status_code

200

In [3]:
soup = BeautifulSoup(resp.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n878 Used Cars in Hyderabad - Second Hand Cars for Sale\n\n HyderabadBuy a carPopular makesMarutiHyundaiHondaRenaultTataVolkswagenDatsunFordMahindraNissanView all makesPopular ModelsHyundai i10Hyundai i20Maruti SwiftMaruti Wagon RHonda CityMaruti AltoMaruti DzireMaruti BalenoRenault KwidTata TiagoView all modelsBody typeHatchbackSedanSUVLuxury SUVLuxury SedanFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Swift (51)Honda City (47)Hyundai Elite i20 (43)Hyundai Grand i10 (40)Maruti Baleno (38)Renault Kwid (36)ALL BRANDSMaruti (315)Hyundai (210)Honda (94)Renault (59)Tata (57)Volkswagen (30)Datsun (23)Ford (20)Mahindra (14)Nissan (14)Toyota (12)Skoda (9)KIA (8)Jeep (7)MG (6)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Volvo (0)Jaguar (0)Budget₹ 1,50,000₹ 25,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear All878 Used cars in HyderabadSort By:Recently Added  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New2010 Hyundai i10MAGNA 1.2Manual57,942 km2nd OwnerPetrolAP-28₹3,863/month ₹49,400 downpayment₹2,47,000Attapur, Hyderabad2016 Hyundai Grand i101.2 SPORTZ PRIME EDITION VTVTManual75,568 km1st OwnerPetrolTS-07₹7,085/month ₹90,600 downpayment₹4,53,000Attapur, HyderabadNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility 2021 Maruti CiazSIGMA 1.5 SHVS MT  PETROLManual41,362 km1st OwnerPetrolTS-07₹12,471/month ₹1,63,800 downpayment₹8,19,000Kompally, Hyderabad2017 Honda WR-V1.5L I-DTEC S MTManual53,535 km1st OwnerDieselTS-07₹10,338/month ₹1,32,200 downpayment₹6,61,000Bachupally, Hyderabad2017 Maruti BalenoDELTA CVT PETROL 1.2Automatic41,260 km2nd OwnerPetrolTS-07₹9,243/month ₹1,18,200 downpayment₹5,91,000Vanasthalipuram, Hyderabad.\nUsed cars in Hyderabad by brandMarutiHyundaiHondaRenaultTataVolkswagenDatsunFordNissanMahindraToyotaSkodaKIAJeepMG2012 Hyundai i20SPORTZ 1.2Manual92,054 km1st OwnerPetrolAP-29₹5,896/month ₹75,400 downpayment₹3,77,000Kompally, Hyderabad2018 Hyundai Elite i20ASTA 1.4 CRDIManual89,269 km1st OwnerDieselTS-07₹11,933/month ₹1,52,600 downpayment₹7,63,000Kompally, Hyderabad2018 Honda Amaze1.2L I-VTEC VManual97,090 km1st OwnerPetrolTS-10₹9,509/month ₹1,21,600 downpayment₹6,08,000Bachupally, HyderabadUsed cars in Hyderabad by body typeHatchbackSedanSUVLuxury SUVLuxury Sedan2015 Maruti Alto 800LXIManual72,308 km2nd OwnerPetrolTS-08₹4,129/month ₹52,800 downpayment₹2,64,000Bachupally, Hyderabad2018 Hyundai NEW SANTROSPORTZ AMTAutomatic92,388 km1st OwnerPetrolTS-11₹6,772/month ₹86,600 downpayment₹4,33,000Attapur, Hyderabad2017 Maruti Celerio XZXI AMTAutomatic48,408 km1st OwnerPetrolTS-08₹7,617/month ₹97,400 downpayment₹4,87,000Bachupally, HyderabadUsed cars in Hyderabad by fuel typePetrolDieselCNGLPG2018 Maruti Alto 800LXI OManual48,542 km2nd OwnerPetrolTS-07₹5,130/month ₹65,600 downpayment₹3,28,000Vanasthalipuram, Hyderabad.\n2015 Renault Duster85 PS RXL DIESELManual98,087 km1st OwnerDieselTS-07₹7,820/month ₹1,00,000 downpayment₹5,00,000Bachupally, Hyderabad2015 Honda Jazz1.2L I-VTEC V ATAutomatic51,895 km1st OwnerPetrolTS-07₹7,914/month ₹1,01,200 downpayment₹5,06,000Bachupally, HyderabadUsed cars in Hyderabad by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhsunder 2 lakhs₹24,000off2017 Maruti SwiftVXIManual77,321 km1st OwnerPetrolTS-15₹9,212/month ₹1,17,800 downpayment₹5,89,000₹6,13,000Kompally, Hyderabad₹50,000off2022 Tata ALTROZXZA PLUSAutomatic9,638 km1st OwnerPetrolTS-08₹14,633/month ₹1,92,200 downpayment₹9,61,000₹10,11,000Kompally, Hyderabad2012 Volkswagen PoloTRENDLINE 1.2L PETROLManual67,852 km1st OwnerPetrolAP-28₹5,693/month ₹72,800 downpayment₹3,64,000Currently tokenedUsed cars in Hyderabad by modelHyundai i10Hyundai i20Maruti SwiftMaruti Wagon RHonda CityMaruti AltoMaruti DzireMaruti BalenoRenault KwidTata TiagoMaruti CelerioMaruti BrezzaHyundai SantroVolkswagen PoloHyundai CretaMaruti CiazHyundai VernaDatsun Redi GoHonda AmazeHonda Jazz₹26,000off2017 Maruti CiazALPHA DIESEL 1.3Manual79,751 km2nd OwnerDieselTS-34₹11,777/month ₹1,50,600 downpayment₹7,53,000₹7,79,000Kompally, Hyderabad2019 Maruti XL6ALPHA ATAutomatic55,188 km2nd OwnerPetrolTS-10₹15,882/month ₹2,08,600 downpayment₹10,43,000Kompally, Hyderabad2013 Hyundai i10SPORTZ 1.2 ATAutomatic16,213 km1st OwnerPetrolAP-29₹6,319/month ₹80,800 downpayment₹4,04,000Kompally, HyderabadHomeUsed CarsHyderabad45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions HyderabadWhat are the most popular brands available for 2nd hand cars in Hyderabad?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Hyderabad of your choice on CARS24.What body types are available for 2nd hand cars in Hyderabad?Used cars in Hyderabad are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Hyderabad?Of Course yes, you can buy used cars online in Hyderabad from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in HyderabadWhat to check before buying a second hand car in Hyderabad?Important things to check  before buying a second hand car in Hyderabad are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Hyderabad?You can buy used cars in Hyderabad from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Hyderabad?You can check second hand cars in Hyderabad using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in HyderabadHow many second hand cars are available in Hyderabad?878 used cars are available in Hyderabad of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in HyderabadUsed Hyundai Cars in HyderabadUsed Honda Cars in HyderabadUsed Renault Cars in HyderabadUsed Tata Cars in HyderabadUsed Volkswagen Cars in HyderabadUsed Datsun Cars in HyderabadUsed Ford Cars in HyderabadUsed Nissan Cars in HyderabadUsed Mahindra Cars in HyderabadUsed Toyota Cars in HyderabadUsed Skoda Cars in HyderabadUsed KIA Cars in HyderabadUsed Jeep Cars in HyderabadUsed MG Cars in HyderabadBody :Used Hatchback Cars in HyderabadUsed Sedan Cars in HyderabadUsed SUV Cars in HyderabadUsed Luxury SUV Cars in HyderabadUsed Luxury Sedan Cars in HyderabadFuel :Used Petrol Cars in HyderabadUsed Diesel Cars in HyderabadUsed CNG Cars in HyderabadUsed LPG Cars in HyderabadBudget :Used Cars between 5 to 10 lakhs in HyderabadUsed Cars between 2 to 5 lakhs in HyderabadUsed Cars above 10 lakhs in HyderabadUsed Cars under 2 lakhs in HyderabadModel :Used Hyundai i10 Cars in HyderabadUsed Hyundai i20 Cars in HyderabadUsed Maruti Swift Cars in HyderabadUsed Maruti Wagon R Cars in HyderabadUsed Honda City Cars in HyderabadUsed Maruti Alto Cars in HyderabadUsed Maruti Dzire Cars in HyderabadUsed Maruti Baleno Cars in HyderabadUsed Renault Kwid Cars in HyderabadUsed Tata Tiago Cars in HyderabadUsed Maruti Celerio Cars in HyderabadUsed Maruti Brezza Cars in HyderabadUsed Hyundai Santro Cars in HyderabadUsed Volkswagen Polo Cars in HyderabadUsed Hyundai Creta Cars in HyderabadUsed Maruti Ciaz Cars in HyderabadUsed Hyundai Verna Cars in HyderabadUsed Datsun Redi Go Cars in HyderabadUsed Honda Amaze Cars in HyderabadUsed Honda Jazz Cars in HyderabadTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [4]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
kmt1 =[]
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)

In [5]:
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2010', '2016', '2021', '2017', '2017', '2012', '2018', '2018', '2015', '2018', '2017', '2018', '2015', '2015', '2017', '2022', '2012', '2017', '2019', '2013']
[[' Hyundai', ' i10'], [' Hyundai', ' Grand', ' i10'], [' Maruti', ' Ciaz'], [' Honda', ' WR'], [' Maruti', ' Baleno'], [' Hyundai', ' i20'], [' Hyundai', ' Elite', ' i20'], [' Honda', ' Amaze'], [' Maruti', ' Alto', ' 800'], [' Hyundai', ' NEW', ' SANTRO'], [' Maruti', ' Celerio', ' X'], [' Maruti', ' Alto', ' 800'], [' Renault', ' Duster'], [' Honda', ' Jazz'], [' Maruti', ' Swift'], [' Tata', ' ALTROZ'], [' Volkswagen', ' Polo'], [' Maruti', ' Ciaz'], [' Maruti', ' XL6'], [' Hyundai', ' i10']]
['Attapur, Hyderabad', 'Attapur, Hyderabad', 'Kompally, Hyderabad', 'Bachupally, Hyderabad', 'Vanasthalipuram, Hyderabad.\n', 'Kompally, Hyderabad', 'Kompally, Hyderabad', 'Bachupally, Hyderabad', 'Bachupally, Hyderabad', 'Attapur, Hyderabad', 'Bachupally, Hyderabad', 'Vanasthalipuram, Hyderabad.\n', 'Bachupally, Hyderabad', 'Bachupally, Hyderabad', 'Kompally, Hyderabad', 'Kompally, Hyderabad', nan, 'Kompally, Hyderabad', 'Kompally, Hyderabad', 'Kompally, Hyderabad']
[['57,942'], ['75,568'], ['41,362'], ['53,535'], ['41,260'], ['92,054'], ['89,269'], ['97,090'], ['72,308'], ['92,388'], ['48,408'], ['48,542'], ['98,087'], ['51,895'], ['77,321'], ['9,638'], ['67,852'], ['79,751'], ['55,188'], ['16,213']]
[['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Automatic'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Automatic'], ['Automatic']]
['247000', '453000', '819000', '661000', '591000', '377000', '763000', '608000', '264000', '433000', '487000', '328000', '500000', '506000', '589000', '961000', '364000', '753000', '1043000', '404000']

In [6]:
dicto = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [7]:
kmt1 = []
dicto["Kmt run"]
for i in dicto["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

In [8]:
dicton = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicton

{'Name of Cars': [[' Hyundai', ' i10'],
  [' Hyundai', ' Grand', ' i10'],
  [' Maruti', ' Ciaz'],
  [' Honda', ' WR'],
  [' Maruti', ' Baleno'],
  [' Hyundai', ' i20'],
  [' Hyundai', ' Elite', ' i20'],
  [' Honda', ' Amaze'],
  [' Maruti', ' Alto', ' 800'],
  [' Hyundai', ' NEW', ' SANTRO'],
  [' Maruti', ' Celerio', ' X'],
  [' Maruti', ' Alto', ' 800'],
  [' Renault', ' Duster'],
  [' Honda', ' Jazz'],
  [' Maruti', ' Swift'],
  [' Tata', ' ALTROZ'],
  [' Volkswagen', ' Polo'],
  [' Maruti', ' Ciaz'],
  [' Maruti', ' XL6'],
  [' Hyundai', ' i10']],
 'Registration Year': ['2010',
  '2016',
  '2021',
  '2017',
  '2017',
  '2012',
  '2018',
  '2018',
  '2015',
  '2018',
  '2017',
  '2018',
  '2015',
  '2015',
  '2017',
  '2022',
  '2012',
  '2017',
  '2019',
  '2013'],
 'Kmt run': [57942,
  75568,
  41362,
  53535,
  41260,
  92054,
  89269,
  97090,
  72308,
  92388,
  48408,
  48542,
  98087,
  51895,
  77321,
  9638,
  67852,
  79751,
  55188,
  16213],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Automatic']],
 'Fuel type': [['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['247000',
  '453000',
  '819000',
  '661000',
  '591000',
  '377000',
  '763000',
  '608000',
  '264000',
  '433000',
  '487000',
  '328000',
  '500000',
  '506000',
  '589000',
  '961000',
  '364000',
  '753000',
  '1043000',
  '404000'],
 'Location of car': ['Attapur, Hyderabad',
  'Attapur, Hyderabad',
  'Kompally, Hyderabad',
  'Bachupally, Hyderabad',
  'Vanasthalipuram, Hyderabad.\n',
  'Kompally, Hyderabad',
  'Kompally, Hyderabad',
  'Bachupally, Hyderabad',
  'Bachupally, Hyderabad',
  'Attapur, Hyderabad',
  'Bachupally, Hyderabad',
  'Vanasthalipuram, Hyderabad.\n',
  'Bachupally, Hyderabad',
  'Bachupally, Hyderabad',
  'Kompally, Hyderabad',
  'Kompally, Hyderabad',
  nan,
  'Kompally, Hyderabad',
  'Kompally, Hyderabad',
  'Kompally, Hyderabad']}

# 2nd

In [9]:
url2 = "https://www.cars24.com/buy-used-car?sort=lhl&serveWarrantyCount=true&listingSource=Homepage_Filters&storeCityId=3686&pinId=500002"

In [10]:
new1 = req.get(url2)
new1

In [11]:
soup = BeautifulSoup(new1.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n878 Used Cars in Hyderabad - Second Hand Cars for Sale\n\n HyderabadBuy a carPopular makesMarutiHyundaiHondaRenaultTataVolkswagenDatsunFordMahindraNissanView all makesPopular ModelsHyundai i10Hyundai i20Maruti SwiftMaruti Wagon RHonda CityMaruti AltoMaruti DzireMaruti BalenoRenault KwidTata TiagoView all modelsBody typeHatchbackSedanSUVLuxury SUVLuxury SedanFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Swift (51)Honda City (47)Hyundai Elite i20 (43)Hyundai Grand i10 (40)Maruti Baleno (38)Renault Kwid (36)ALL BRANDSMaruti (315)Hyundai (210)Honda (94)Renault (59)Tata (57)Volkswagen (30)Datsun (23)Ford (20)Mahindra (14)Nissan (14)Toyota (12)Skoda (9)KIA (8)Jeep (7)MG (6)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Volvo (0)Jaguar (0)Budget₹ 1,50,000₹ 25,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear All878 Used cars in HyderabadSort By:Recently Added  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New2010 Hyundai i10MAGNA 1.2Manual57,942 km2nd OwnerPetrolAP-28₹3,863/month ₹49,400 downpayment₹2,47,000Attapur, Hyderabad2016 Hyundai Grand i101.2 SPORTZ PRIME EDITION VTVTManual75,568 km1st OwnerPetrolTS-07₹7,085/month ₹90,600 downpayment₹4,53,000Attapur, HyderabadNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility 2021 Maruti CiazSIGMA 1.5 SHVS MT  PETROLManual41,362 km1st OwnerPetrolTS-07₹12,471/month ₹1,63,800 downpayment₹8,19,000Kompally, Hyderabad2017 Honda WR-V1.5L I-DTEC S MTManual53,535 km1st OwnerDieselTS-07₹10,338/month ₹1,32,200 downpayment₹6,61,000Bachupally, Hyderabad2017 Maruti BalenoDELTA CVT PETROL 1.2Automatic41,260 km2nd OwnerPetrolTS-07₹9,243/month ₹1,18,200 downpayment₹5,91,000Vanasthalipuram, Hyderabad.\nUsed cars in Hyderabad by brandMarutiHyundaiHondaRenaultTataVolkswagenDatsunFordNissanMahindraToyotaSkodaKIAJeepMG2012 Hyundai i20SPORTZ 1.2Manual92,054 km1st OwnerPetrolAP-29₹5,896/month ₹75,400 downpayment₹3,77,000Kompally, Hyderabad2018 Hyundai Elite i20ASTA 1.4 CRDIManual89,269 km1st OwnerDieselTS-07₹11,933/month ₹1,52,600 downpayment₹7,63,000Kompally, Hyderabad2018 Honda Amaze1.2L I-VTEC VManual97,090 km1st OwnerPetrolTS-10₹9,509/month ₹1,21,600 downpayment₹6,08,000Bachupally, HyderabadUsed cars in Hyderabad by body typeHatchbackSedanSUVLuxury SUVLuxury Sedan2015 Maruti Alto 800LXIManual72,308 km2nd OwnerPetrolTS-08₹4,129/month ₹52,800 downpayment₹2,64,000Bachupally, Hyderabad2018 Hyundai NEW SANTROSPORTZ AMTAutomatic92,388 km1st OwnerPetrolTS-11₹6,772/month ₹86,600 downpayment₹4,33,000Attapur, Hyderabad2017 Maruti Celerio XZXI AMTAutomatic48,408 km1st OwnerPetrolTS-08₹7,617/month ₹97,400 downpayment₹4,87,000Bachupally, HyderabadUsed cars in Hyderabad by fuel typePetrolDieselCNGLPG2018 Maruti Alto 800LXI OManual48,542 km2nd OwnerPetrolTS-07₹5,130/month ₹65,600 downpayment₹3,28,000Vanasthalipuram, Hyderabad.\n2015 Renault Duster85 PS RXL DIESELManual98,087 km1st OwnerDieselTS-07₹7,820/month ₹1,00,000 downpayment₹5,00,000Bachupally, Hyderabad2015 Honda Jazz1.2L I-VTEC V ATAutomatic51,895 km1st OwnerPetrolTS-07₹7,914/month ₹1,01,200 downpayment₹5,06,000Bachupally, HyderabadUsed cars in Hyderabad by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhsunder 2 lakhs₹24,000off2017 Maruti SwiftVXIManual77,321 km1st OwnerPetrolTS-15₹9,212/month ₹1,17,800 downpayment₹5,89,000₹6,13,000Kompally, Hyderabad₹50,000off2022 Tata ALTROZXZA PLUSAutomatic9,638 km1st OwnerPetrolTS-08₹14,633/month ₹1,92,200 downpayment₹9,61,000₹10,11,000Kompally, Hyderabad2012 Volkswagen PoloTRENDLINE 1.2L PETROLManual67,852 km1st OwnerPetrolAP-28₹5,693/month ₹72,800 downpayment₹3,64,000Currently tokenedUsed cars in Hyderabad by modelHyundai i10Hyundai i20Maruti SwiftMaruti Wagon RHonda CityMaruti AltoMaruti DzireMaruti BalenoRenault KwidTata TiagoMaruti CelerioMaruti BrezzaHyundai SantroVolkswagen PoloHyundai CretaMaruti CiazHyundai VernaDatsun Redi GoHonda AmazeHonda Jazz₹26,000off2017 Maruti CiazALPHA DIESEL 1.3Manual79,751 km2nd OwnerDieselTS-34₹11,777/month ₹1,50,600 downpayment₹7,53,000₹7,79,000Kompally, Hyderabad2019 Maruti XL6ALPHA ATAutomatic55,188 km2nd OwnerPetrolTS-10₹15,882/month ₹2,08,600 downpayment₹10,43,000Kompally, Hyderabad2013 Hyundai i10SPORTZ 1.2 ATAutomatic16,213 km1st OwnerPetrolAP-29₹6,319/month ₹80,800 downpayment₹4,04,000Kompally, HyderabadHomeUsed CarsHyderabad45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions HyderabadWhat are the most popular brands available for 2nd hand cars in Hyderabad?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Hyderabad of your choice on CARS24.What body types are available for 2nd hand cars in Hyderabad?Used cars in Hyderabad are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Hyderabad?Of Course yes, you can buy used cars online in Hyderabad from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in HyderabadWhat to check before buying a second hand car in Hyderabad?Important things to check  before buying a second hand car in Hyderabad are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Hyderabad?You can buy used cars in Hyderabad from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Hyderabad?You can check second hand cars in Hyderabad using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in HyderabadHow many second hand cars are available in Hyderabad?878 used cars are available in Hyderabad of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in HyderabadUsed Hyundai Cars in HyderabadUsed Honda Cars in HyderabadUsed Renault Cars in HyderabadUsed Tata Cars in HyderabadUsed Volkswagen Cars in HyderabadUsed Datsun Cars in HyderabadUsed Ford Cars in HyderabadUsed Nissan Cars in HyderabadUsed Mahindra Cars in HyderabadUsed Toyota Cars in HyderabadUsed Skoda Cars in HyderabadUsed KIA Cars in HyderabadUsed Jeep Cars in HyderabadUsed MG Cars in HyderabadBody :Used Hatchback Cars in HyderabadUsed Sedan Cars in HyderabadUsed SUV Cars in HyderabadUsed Luxury SUV Cars in HyderabadUsed Luxury Sedan Cars in HyderabadFuel :Used Petrol Cars in HyderabadUsed Diesel Cars in HyderabadUsed CNG Cars in HyderabadUsed LPG Cars in HyderabadBudget :Used Cars between 5 to 10 lakhs in HyderabadUsed Cars between 2 to 5 lakhs in HyderabadUsed Cars above 10 lakhs in HyderabadUsed Cars under 2 lakhs in HyderabadModel :Used Hyundai i10 Cars in HyderabadUsed Hyundai i20 Cars in HyderabadUsed Maruti Swift Cars in HyderabadUsed Maruti Wagon R Cars in HyderabadUsed Honda City Cars in HyderabadUsed Maruti Alto Cars in HyderabadUsed Maruti Dzire Cars in HyderabadUsed Maruti Baleno Cars in HyderabadUsed Renault Kwid Cars in HyderabadUsed Tata Tiago Cars in HyderabadUsed Maruti Celerio Cars in HyderabadUsed Maruti Brezza Cars in HyderabadUsed Hyundai Santro Cars in HyderabadUsed Volkswagen Polo Cars in HyderabadUsed Hyundai Creta Cars in HyderabadUsed Maruti Ciaz Cars in HyderabadUsed Hyundai Verna Cars in HyderabadUsed Datsun Redi Go Cars in HyderabadUsed Honda Amaze Cars in HyderabadUsed Honda Jazz Cars in HyderabadTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [12]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)

In [13]:
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2010', '2016', '2021', '2017', '2017', '2012', '2018', '2018', '2015', '2018', '2017', '2018', '2015', '2015', '2017', '2022', '2012', '2017', '2019', '2013']
[[' Hyundai', ' i10'], [' Hyundai', ' Grand', ' i10'], [' Maruti', ' Ciaz'], [' Honda', ' WR'], [' Maruti', ' Baleno'], [' Hyundai', ' i20'], [' Hyundai', ' Elite', ' i20'], [' Honda', ' Amaze'], [' Maruti', ' Alto', ' 800'], [' Hyundai', ' NEW', ' SANTRO'], [' Maruti', ' Celerio', ' X'], [' Maruti', ' Alto', ' 800'], [' Renault', ' Duster'], [' Honda', ' Jazz'], [' Maruti', ' Swift'], [' Tata', ' ALTROZ'], [' Volkswagen', ' Polo'], [' Maruti', ' Ciaz'], [' Maruti', ' XL6'], [' Hyundai', ' i10']]
['Attapur, Hyderabad', 'Attapur, Hyderabad', 'Kompally, Hyderabad', 'Bachupally, Hyderabad', 'Vanasthalipuram, Hyderabad.\n', 'Kompally, Hyderabad', 'Kompally, Hyderabad', 'Bachupally, Hyderabad', 'Bachupally, Hyderabad', 'Attapur, Hyderabad', 'Bachupally, Hyderabad', 'Vanasthalipuram, Hyderabad.\n', 'Bachupally, Hyderabad', 'Bachupally, Hyderabad', 'Kompally, Hyderabad', 'Kompally, Hyderabad', nan, 'Kompally, Hyderabad', 'Kompally, Hyderabad', 'Kompally, Hyderabad']
[['57,942'], ['75,568'], ['41,362'], ['53,535'], ['41,260'], ['92,054'], ['89,269'], ['97,090'], ['72,308'], ['92,388'], ['48,408'], ['48,542'], ['98,087'], ['51,895'], ['77,321'], ['9,638'], ['67,852'], ['79,751'], ['55,188'], ['16,213']]
[['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Automatic'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Automatic'], ['Automatic']]
['247000', '453000', '819000', '661000', '591000', '377000', '763000', '608000', '264000', '433000', '487000', '328000', '500000', '506000', '589000', '961000', '364000', '753000', '1043000', '404000']

In [14]:
dicto2 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [15]:
kmt1 = []
dicto2["Kmt run"]
for i in dicto2["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

In [16]:
dicto2n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto2n

{'Name of Cars': [[' Hyundai', ' i10'],
  [' Hyundai', ' Grand', ' i10'],
  [' Maruti', ' Ciaz'],
  [' Honda', ' WR'],
  [' Maruti', ' Baleno'],
  [' Hyundai', ' i20'],
  [' Hyundai', ' Elite', ' i20'],
  [' Honda', ' Amaze'],
  [' Maruti', ' Alto', ' 800'],
  [' Hyundai', ' NEW', ' SANTRO'],
  [' Maruti', ' Celerio', ' X'],
  [' Maruti', ' Alto', ' 800'],
  [' Renault', ' Duster'],
  [' Honda', ' Jazz'],
  [' Maruti', ' Swift'],
  [' Tata', ' ALTROZ'],
  [' Volkswagen', ' Polo'],
  [' Maruti', ' Ciaz'],
  [' Maruti', ' XL6'],
  [' Hyundai', ' i10']],
 'Registration Year': ['2010',
  '2016',
  '2021',
  '2017',
  '2017',
  '2012',
  '2018',
  '2018',
  '2015',
  '2018',
  '2017',
  '2018',
  '2015',
  '2015',
  '2017',
  '2022',
  '2012',
  '2017',
  '2019',
  '2013'],
 'Kmt run': [57942,
  75568,
  41362,
  53535,
  41260,
  92054,
  89269,
  97090,
  72308,
  92388,
  48408,
  48542,
  98087,
  51895,
  77321,
  9638,
  67852,
  79751,
  55188,
  16213],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Automatic']],
 'Fuel type': [['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['247000',
  '453000',
  '819000',
  '661000',
  '591000',
  '377000',
  '763000',
  '608000',
  '264000',
  '433000',
  '487000',
  '328000',
  '500000',
  '506000',
  '589000',
  '961000',
  '364000',
  '753000',
  '1043000',
  '404000'],
 'Location of car': ['Attapur, Hyderabad',
  'Attapur, Hyderabad',
  'Kompally, Hyderabad',
  'Bachupally, Hyderabad',
  'Vanasthalipuram, Hyderabad.\n',
  'Kompally, Hyderabad',
  'Kompally, Hyderabad',
  'Bachupally, Hyderabad',
  'Bachupally, Hyderabad',
  'Attapur, Hyderabad',
  'Bachupally, Hyderabad',
  'Vanasthalipuram, Hyderabad.\n',
  'Bachupally, Hyderabad',
  'Bachupally, Hyderabad',
  'Kompally, Hyderabad',
  'Kompally, Hyderabad',
  nan,
  'Kompally, Hyderabad',
  'Kompally, Hyderabad',
  'Kompally, Hyderabad']}

# 3

In [17]:
url3 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Amaruti&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&listingSource=TabFilter&storeCityId=2&pinId=110001"

In [18]:
new3 = req.get(url3)
new3

In [19]:
soup = BeautifulSoup(new3.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n817 Used Cars in New Delhi - Second Hand Cars for Sale\n\n New DelhiBuy a carPopular makesMarutiHyundaiHondaRenaultTataFordToyotaVolkswagenMahindraKIAView all makesPopular ModelsMaruti BalenoHyundai i10Honda CityMaruti Wagon RMaruti SwiftMaruti AltoHonda AmazeHyundai i20Maruti CelerioHyundai CretaView all modelsBody typeHatchbackSedanSUVLuxury SUVLuxury SedanFuel typePetrolCNGDieselTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Baleno (161)Maruti Swift (125)Honda City (108)Honda Amaze (89)Maruti Wagon R 1.0 (76)Hyundai Grand i10 (65)ALL BRANDSMaruti (817)Hyundai (423)Honda (266)Tata (99)Renault (72)Toyota (62)Mahindra (43)Ford (41)Volkswagen (32)Datsun (28)KIA (25)Nissan (19)Jeep (16)Skoda (10)MG (5)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Volvo (0)Jaguar (0)Budget₹ 1,00,000₹ 30,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear All817 Used cars in New DelhiSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹19,000off2019 Maruti Vitara BrezzaVDIManual55,523 km1st OwnerDieselHR-30₹12,182/month ₹1,60,000 downpayment₹8,00,000₹8,19,000M3M Urbana, Golf Course Ext., Gurugram₹41,000off2015 Maruti SwiftVDI ABSManual1,17,499 km1st OwnerDieselHR-30₹5,881/month ₹75,200 downpayment₹3,76,000₹4,17,000Spaze Platinum, Sohna Road, GurugramNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹23,000off2018 Maruti SwiftVXIManual91,534 km2nd OwnerPetrolHR-50₹8,039/month ₹1,02,800 downpayment₹5,14,000₹5,37,000M3M Urbana, Golf Course Ext., Gurugram₹37,000off2019 Maruti Vitara BrezzaVDIManual50,767 km1st OwnerDieselHR-29₹12,231/month ₹1,56,400 downpayment₹7,82,000₹8,19,000M3M Urbana, Golf Course Ext., Gurugram2015 Maruti Alto 800LXIManual35,843 km3rd OwnerPetrolHR-29₹3,660/month ₹46,800 downpayment₹2,34,000Spaze Platinum, Sohna Road, GurugramUsed cars in New Delhi by brandMarutiHyundaiHondaRenaultTataFordToyotaVolkswagenMahindraDatsunKIANissanJeepSkodaMGBMWAudiMercedes Benz₹72,000off2019 Maruti BalenoDELTA PETROL 1.2Manual97,494 km1st OwnerPetrolHR-30₹7,210/month ₹92,200 downpayment₹4,61,000₹5,33,000Spaze Platinum, Sohna Road, Gurugram₹34,000off2019 Maruti New Wagon-RLXI CNG 1.0Manual48,404 km1st OwnerCNGHR-29₹7,210/month ₹92,200 downpayment₹4,61,000₹4,95,000Metro Walk, Rohini, New Delhi2014 Maruti Wagon R 1.0VXIManual97,752 km1st OwnerPetrolHR-30₹4,583/month ₹58,600 downpayment₹2,93,000Spaze Platinum, Sohna Road, GurugramUsed cars in New Delhi by body typeHatchbackSedanSUVLuxury SUVLuxury Sedan₹31,000off2014 Maruti Wagon R 1.0VXIManual79,204 km2nd OwnerPetrolHR-30₹3,894/month ₹49,800 downpayment₹2,49,000₹2,80,000Spaze Platinum, Sohna Road, Gurugram₹45,000off2018 Maruti Vitara BrezzaVDIManual30,549 km1st OwnerDieselHR-30₹10,995/month ₹1,40,600 downpayment₹7,03,000₹7,48,000Parsvnath City Mall, Faridabad₹5,000off2010 Maruti Wagon R 1.0VXIManual61,569 km2nd OwnerPetrolHR-50₹2,831/month ₹36,200 downpayment₹1,81,000₹1,86,000Chhatarpur, Delhi\nUsed cars in New Delhi by fuel typePetrolCNGDiesel2019 Maruti AltoLXIManual18,475 km1st OwnerPetrolHR-29₹5,318/month ₹68,000 downpayment₹3,40,000GIP Mall, Noida₹15,000off2020 Maruti SwiftLXIManual44,817 km2nd OwnerPetrolHR-36₹8,227/month ₹1,05,200 downpayment₹5,26,000₹5,41,000Metro Walk, Rohini, New Delhi₹22,000off2014 Maruti Alto K10VXIManual47,899 km1st OwnerPetrolHR-36₹3,801/month ₹48,600 downpayment₹2,43,000₹2,65,000Spaze Platinum, Sohna Road, GurugramUsed cars in New Delhi by budgetbetween 2 to 5 lakhsbetween 5 to 10 lakhsunder 2 lakhsabove 10 lakhs₹44,000off2018 Maruti SwiftVXIManual34,966 km1st OwnerPetrolHR-14₹8,805/month ₹1,12,600 downpayment₹5,63,000₹6,07,000Metro Walk, Rohini, New Delhi₹48,000off2016 Maruti Alto 800LXIManual89,634 km1st OwnerPetrolHR-82₹3,816/month ₹48,800 downpayment₹2,44,000₹2,92,000Parsvnath City Mall, Faridabad2014 Maruti Alto 800LXIManual1,02,337 km1st OwnerPetrolHR-76₹3,503/month ₹44,800 downpayment₹2,24,000Spaze Platinum, Sohna Road, GurugramUsed cars in New Delhi by modelMaruti BalenoHyundai i10Honda CityMaruti Wagon RMaruti SwiftMaruti AltoHonda AmazeHyundai i20Maruti CelerioHyundai CretaMaruti DzireMaruti CiazHyundai SantroFord EcosportMaruti IGNISRenault KwidHonda JazzHyundai VernaTata NEXONHonda WR-V₹48,000off2016 Maruti Alto K10VXIManual32,031 km1st OwnerPetrolHR-36₹4,583/month ₹58,600 downpayment₹2,93,000₹3,41,000Spaze Platinum, Sohna Road, Gurugram₹87,000off2019 Maruti Celerio XZXI (O)Manual54,711 km1st OwnerPetrolHR-36₹7,398/month ₹94,600 downpayment₹4,73,000₹5,60,000Metro Walk, Rohini, New Delhi₹15,000off2017 Maruti Alto 800LXIManual25,868 km1st OwnerPetrolHR-36₹5,020/month ₹64,200 downpayment₹3,21,000₹3,36,000Metro Walk, Rohini, New DelhiHomeUsed CarsNew Delhi45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions New DelhiWhat are the most popular brands available for 2nd hand cars in New Delhi?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in New Delhi of your choice on CARS24.What body types are available for 2nd hand cars in New Delhi?Used cars in New Delhi are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in New Delhi?Of Course yes, you can buy used cars online in New Delhi from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in New DelhiWhat to check before buying a second hand car in New Delhi?Important things to check  before buying a second hand car in New Delhi are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in New Delhi?You can buy used cars in New Delhi from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in New Delhi?You can check second hand cars in New Delhi using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in New DelhiHow many second hand cars are available in New Delhi?817 used cars are available in New Delhi of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in New DelhiUsed Hyundai Cars in New DelhiUsed Honda Cars in New DelhiUsed Renault Cars in New DelhiUsed Tata Cars in New DelhiUsed Ford Cars in New DelhiUsed Toyota Cars in New DelhiUsed Volkswagen Cars in New DelhiUsed Mahindra Cars in New DelhiUsed Datsun Cars in New DelhiUsed KIA Cars in New DelhiUsed Nissan Cars in New DelhiUsed Jeep Cars in New DelhiUsed Skoda Cars in New DelhiUsed MG Cars in New DelhiUsed BMW Cars in New DelhiUsed Audi Cars in New DelhiUsed Mercedes Benz Cars in New DelhiBody :Used Hatchback Cars in New DelhiUsed Sedan Cars in New DelhiUsed SUV Cars in New DelhiUsed Luxury SUV Cars in New DelhiUsed Luxury Sedan Cars in New DelhiFuel :Used Petrol Cars in New DelhiUsed CNG Cars in New DelhiUsed Diesel Cars in New DelhiBudget :Used Cars between 2 to 5 lakhs in New DelhiUsed Cars between 5 to 10 lakhs in New DelhiUsed Cars under 2 lakhs in New DelhiUsed Cars above 10 lakhs in New DelhiModel :Used Maruti Baleno Cars in New DelhiUsed Hyundai i10 Cars in New DelhiUsed Honda City Cars in New DelhiUsed Maruti Wagon R Cars in New DelhiUsed Maruti Swift Cars in New DelhiUsed Maruti Alto Cars in New DelhiUsed Honda Amaze Cars in New DelhiUsed Hyundai i20 Cars in New DelhiUsed Maruti Celerio Cars in New DelhiUsed Hyundai Creta Cars in New DelhiUsed Maruti Dzire Cars in New DelhiUsed Maruti Ciaz Cars in New DelhiUsed Hyundai Santro Cars in New DelhiUsed Ford Ecosport Cars in New DelhiUsed Maruti IGNIS Cars in New DelhiUsed Renault Kwid Cars in New DelhiUsed Honda Jazz Cars in New DelhiUsed Hyundai Verna Cars in New DelhiUsed Tata NEXON Cars in New DelhiUsed Honda WR-V Cars in New DelhiTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [20]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)

In [21]:
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2019', '2015', '2018', '2019', '2015', '2019', '2019', '2014', '2014', '2018', '2010', '2019', '2020', '2014', '2018', '2016', '2014', '2016', '2019', '2017']
[[' Maruti', ' Vitara', ' Brezza'], [' Maruti', ' Swift'], [' Maruti', ' Swift'], [' Maruti', ' Vitara', ' Brezza'], [' Maruti', ' Alto', ' 800'], [' Maruti', ' Baleno'], [' Maruti', ' New', ' Wagon'], [' Maruti', ' Wagon', ' R', ' 1'], [' Maruti', ' Wagon', ' R', ' 1'], [' Maruti', ' Vitara', ' Brezza'], [' Maruti', ' Wagon', ' R', ' 1'], [' Maruti', ' Alto'], [' Maruti', ' Swift'], [' Maruti', ' Alto', ' K10'], [' Maruti', ' Swift'], [' Maruti', ' Alto', ' 800'], [' Maruti', ' Alto', ' 800'], [' Maruti', ' Alto', ' K10'], [' Maruti', ' Celerio', ' X'], [' Maruti', ' Alto', ' 800']]
['M3M Urbana, Golf Course Ext., Gurugram', 'Spaze Platinum, Sohna Road, Gurugram', 'M3M Urbana, Golf Course Ext., Gurugram', 'M3M Urbana, Golf Course Ext., Gurugram', 'Spaze Platinum, Sohna Road, Gurugram', 'Spaze Platinum, Sohna Road, Gurugram', 'Metro Walk, Rohini, New Delhi', 'Spaze Platinum, Sohna Road, Gurugram', 'Spaze Platinum, Sohna Road, Gurugram', 'Parsvnath City Mall, Faridabad', 'Chhatarpur, Delhi\n', 'GIP Mall, Noida', 'Metro Walk, Rohini, New Delhi', 'Spaze Platinum, Sohna Road, Gurugram', 'Metro Walk, Rohini, New Delhi', 'Parsvnath City Mall, Faridabad', 'Spaze Platinum, Sohna Road, Gurugram', 'Spaze Platinum, Sohna Road, Gurugram', 'Metro Walk, Rohini, New Delhi', 'Metro Walk, Rohini, New Delhi']
[['55,523'], ['1,17', ',499'], ['91,534'], ['50,767'], ['35,843'], ['97,494'], ['48,404'], ['97,752'], ['79,204'], ['30,549'], ['61,569'], ['18,475'], ['44,817'], ['47,899'], ['34,966'], ['89,634'], ['1,02', ',337'], ['32,031'], ['54,711'], ['25,868']]
[['Diesel'], ['Diesel'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], nan, ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['800000', '376000', '514000', '782000', '234000', '461000', '461000', '293000', '249000', '703000', '181000', '340000', '526000', '243000', '563000', '244000', '224000', '293000', '473000', '321000']

In [22]:
dicto3 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [23]:
kmt1 = []
dicto3["Kmt run"]
for i in dicto3["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

In [24]:
dicto3n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto3n

{'Name of Cars': [[' Maruti', ' Vitara', ' Brezza'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Vitara', ' Brezza'],
  [' Maruti', ' Alto', ' 800'],
  [' Maruti', ' Baleno'],
  [' Maruti', ' New', ' Wagon'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Maruti', ' Vitara', ' Brezza'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Maruti', ' Alto'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Alto', ' K10'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Alto', ' 800'],
  [' Maruti', ' Alto', ' 800'],
  [' Maruti', ' Alto', ' K10'],
  [' Maruti', ' Celerio', ' X'],
  [' Maruti', ' Alto', ' 800']],
 'Registration Year': ['2019',
  '2015',
  '2018',
  '2019',
  '2015',
  '2019',
  '2019',
  '2014',
  '2014',
  '2018',
  '2010',
  '2019',
  '2020',
  '2014',
  '2018',
  '2016',
  '2014',
  '2016',
  '2019',
  '2017'],
 'Kmt run': [55523,
  117499,
  91534,
  50767,
  35843,
  97494,
  48404,
  97752,
  79204,
  30549,
  61569,
  18475,
  44817,
  47899,
  34966,
  89634,
  102337,
  32031,
  54711,
  25868],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Diesel'],
  ['Diesel'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  nan,
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['800000',
  '376000',
  '514000',
  '782000',
  '234000',
  '461000',
  '461000',
  '293000',
  '249000',
  '703000',
  '181000',
  '340000',
  '526000',
  '243000',
  '563000',
  '244000',
  '224000',
  '293000',
  '473000',
  '321000'],
 'Location of car': ['M3M Urbana, Golf Course Ext., Gurugram',
  'Spaze Platinum, Sohna Road, Gurugram',
  'M3M Urbana, Golf Course Ext., Gurugram',
  'M3M Urbana, Golf Course Ext., Gurugram',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Metro Walk, Rohini, New Delhi',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Parsvnath City Mall, Faridabad',
  'Chhatarpur, Delhi\n',
  'GIP Mall, Noida',
  'Metro Walk, Rohini, New Delhi',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Metro Walk, Rohini, New Delhi',
  'Parsvnath City Mall, Faridabad',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Metro Walk, Rohini, New Delhi',
  'Metro Walk, Rohini, New Delhi']}

In [25]:
url4 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&listingSource=TabFilter&storeCityId=1692&pinId=380001"

In [26]:
new4 = req.get(url4)
new4

In [27]:
soup = BeautifulSoup(new4.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n159 Used Cars in Ahmedabad - Second Hand Cars for Sale\n\n AhmedabadBuy a carPopular makesMarutiHyundaiHondaTataMahindraRenaultVolkswagenFordToyotaDatsunView all makesPopular ModelsHyundai i10Maruti BalenoHyundai i20Maruti DzireMaruti AltoMaruti Wagon RMaruti SwiftMaruti CiazMaruti IGNISHyundai VernaView all modelsBody typeHatchbackSUVSedanLuxury SUVLuxury SedanFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Baleno (41)Hyundai Grand i10 (27)Hyundai Elite i20 (22)Maruti Swift (20)Maruti Ciaz (19)Hyundai i10 (17)ALL BRANDSMaruti (203)Hyundai (159)Honda (59)Tata (49)Mahindra (26)Renault (22)Volkswagen (20)Ford (13)Toyota (12)Datsun (11)Nissan (7)MG (7)KIA (6)Jeep (5)Skoda (1)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Volvo (0)Jaguar (0)Budget₹ 1,50,000₹ 25,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear All159 Used cars in AhmedabadSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New2012 Hyundai i10MAGNA 1.2Manual88,748 km1st OwnerPetrolGJ-01₹4,909/month ₹46,600 downpayment₹2,33,000Karnavati Club, Ahmedabad₹20,000off2014 Hyundai i20MAGNA (O) 1.2Manual64,814 km3rd OwnerPetrolGJ-01₹5,552/month ₹71,000 downpayment₹3,55,000₹3,75,000Naroda, AhmedabadNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹81,000off2019 Hyundai CretaE PLUS 1.6 PETROLManual43,804 km1st OwnerPetrolGJ-06₹13,141/month ₹1,72,600 downpayment₹8,63,000₹9,44,000Karnavati Club, Ahmedabad₹74,000off2018 Hyundai Elite i20ASTA 1.2Manual67,470 km2nd OwnerPetrolGJ-01₹9,713/month ₹1,24,200 downpayment₹6,21,000₹6,95,000Naroda, Ahmedabad₹11,000off2010 Hyundai i10SPORTZ 1.2Manual87,197 km3rd OwnerPetrolGJ-01₹6,289/month ₹33,400 downpayment₹1,67,000₹1,78,000Naroda, AhmedabadUsed cars in Ahmedabad by brandMarutiHyundaiHondaTataMahindraVolkswagenRenaultFordToyotaDatsunMGNissanKIAJeepSkodaAudiVolvo₹66,000off2022 Hyundai CretaS IMT 1.5 PETROLManual4,344 km1st OwnerPetrolGJ-36₹19,095/month ₹2,50,800 downpayment₹12,54,000₹13,20,000Karnavati Club, Ahmedabad2013 Hyundai i20MAGNA 1.4 CRDIManual1,05,286 km2nd OwnerDieselGJ-27₹6,046/month ₹57,400 downpayment₹2,87,000Naroda, Ahmedabad₹42,000off2021 Hyundai CretaSX 1.5 DIESELManual51,463 km1st OwnerDieselGJ-01₹22,095/month ₹2,90,200 downpayment₹14,51,000₹14,93,000Karnavati Club, AhmedabadUsed cars in Ahmedabad by body typeHatchbackSUVSedanLuxury SUVLuxury Sedan₹31,000off2016 Hyundai Elite i20ASTA 1.2Manual1,15,488 km3rd OwnerCNGGJ-14₹8,951/month ₹1,00,600 downpayment₹5,03,000₹5,34,000Karnavati Club, Ahmedabad2011 Hyundai i10MAGNA 1.1Manual1,24,420 km3rd OwnerPetrolGJ-18₹5,288/month ₹39,800 downpayment₹1,99,000Naroda, Ahmedabad₹24,000off2015 Hyundai i10SPORTZ 1.1Manual76,494 km2nd OwnerCNGGJ-24₹5,944/month ₹66,800 downpayment₹3,34,000₹3,58,000Naroda, AhmedabadUsed cars in Ahmedabad by fuel typePetrolDieselCNG₹70,000off2017 Hyundai Elite i20ASTA 1.4 CRDIManual1,16,263 km3rd OwnerDieselGJ-38₹9,823/month ₹1,10,400 downpayment₹5,52,000₹6,22,000Naroda, Ahmedabad₹18,000off2012 Hyundai EonERA +Manual1,05,830 km1st OwnerPetrolGJ-01₹3,645/month ₹34,600 downpayment₹1,73,000₹1,91,000Naroda, Ahmedabad₹1,03,000off2019 Hyundai CretaSX 1.6 DIESELManual82,074 km2nd OwnerDieselGJ-01₹15,045/month ₹1,97,600 downpayment₹9,88,000₹10,91,000Naroda, AhmedabadUsed cars in Ahmedabad by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhsunder 2 lakhs₹1,26,000off2020 Hyundai Verna1.6 VTVT SX + ATAutomatic69,761 km1st OwnerPetrolGJ-06₹14,451/month ₹1,89,800 downpayment₹9,49,000₹10,75,000Naroda, Ahmedabad₹46,000off2016 Hyundai CretaSX 1.6 DIESELManual1,07,787 km2nd OwnerDieselGJ-01₹13,738/month ₹1,54,400 downpayment₹7,72,000₹8,18,000Karnavati Club, Ahmedabad2020 Hyundai CretaSX 1.5 PETROLManual30,099 km1st OwnerPetrolGJ-01₹21,151/month ₹2,77,800 downpayment₹13,89,000Karnavati Club, AhmedabadUsed cars in Ahmedabad by modelHyundai i10Maruti BalenoHyundai i20Maruti AltoMaruti DzireMaruti Wagon RMaruti SwiftMaruti CiazMaruti IGNISHyundai SantroHyundai VernaHonda CityHyundai VENUEHonda AmazeHyundai CretaTata TiagoHyundai EonFord EcosportTata HarrierHonda Brio₹32,000off2019 Hyundai Elite i20MAGNA PLUS 1.2Manual1,08,140 km1st OwnerPetrolGJ-27₹10,339/month ₹1,16,200 downpayment₹5,81,000₹6,13,000Naroda, Ahmedabad₹47,000off2017 Hyundai XcentE+Manual36,486 km1st OwnerPetrolGJ-18₹7,523/month ₹96,200 downpayment₹4,81,000₹5,28,000Karnavati Club, Ahmedabad₹8,000off2017 Hyundai EonERA +Manual91,991 km1st OwnerCNGGJ-01₹4,379/month ₹56,000 downpayment₹2,80,000₹2,88,000Karnavati Club, AhmedabadHomeUsed CarsAhmedabad45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions AhmedabadWhat are the most popular brands available for 2nd hand cars in Ahmedabad?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Ahmedabad of your choice on CARS24.What body types are available for 2nd hand cars in Ahmedabad?Used cars in Ahmedabad are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Ahmedabad?Of Course yes, you can buy used cars online in Ahmedabad from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in AhmedabadWhat to check before buying a second hand car in Ahmedabad?Important things to check  before buying a second hand car in Ahmedabad are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Ahmedabad?You can buy used cars in Ahmedabad from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Ahmedabad?You can check second hand cars in Ahmedabad using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in AhmedabadHow many second hand cars are available in Ahmedabad?159 used cars are available in Ahmedabad of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in AhmedabadUsed Hyundai Cars in AhmedabadUsed Honda Cars in AhmedabadUsed Tata Cars in AhmedabadUsed Mahindra Cars in AhmedabadUsed Volkswagen Cars in AhmedabadUsed Renault Cars in AhmedabadUsed Ford Cars in AhmedabadUsed Toyota Cars in AhmedabadUsed Datsun Cars in AhmedabadUsed MG Cars in AhmedabadUsed Nissan Cars in AhmedabadUsed KIA Cars in AhmedabadUsed Jeep Cars in AhmedabadUsed Skoda Cars in AhmedabadUsed Audi Cars in AhmedabadUsed Volvo Cars in AhmedabadBody :Used Hatchback Cars in AhmedabadUsed SUV Cars in AhmedabadUsed Sedan Cars in AhmedabadUsed Luxury SUV Cars in AhmedabadUsed Luxury Sedan Cars in AhmedabadFuel :Used Petrol Cars in AhmedabadUsed Diesel Cars in AhmedabadUsed CNG Cars in AhmedabadBudget :Used Cars between 5 to 10 lakhs in AhmedabadUsed Cars between 2 to 5 lakhs in AhmedabadUsed Cars above 10 lakhs in AhmedabadUsed Cars under 2 lakhs in AhmedabadModel :Used Hyundai i10 Cars in AhmedabadUsed Maruti Baleno Cars in AhmedabadUsed Hyundai i20 Cars in AhmedabadUsed Maruti Alto Cars in AhmedabadUsed Maruti Dzire Cars in AhmedabadUsed Maruti Wagon R Cars in AhmedabadUsed Maruti Swift Cars in AhmedabadUsed Maruti Ciaz Cars in AhmedabadUsed Maruti IGNIS Cars in AhmedabadUsed Hyundai Santro Cars in AhmedabadUsed Hyundai Verna Cars in AhmedabadUsed Honda City Cars in AhmedabadUsed Hyundai VENUE Cars in AhmedabadUsed Honda Amaze Cars in AhmedabadUsed Hyundai Creta Cars in AhmedabadUsed Tata Tiago Cars in AhmedabadUsed Hyundai Eon Cars in AhmedabadUsed Ford Ecosport Cars in AhmedabadUsed Tata Harrier Cars in AhmedabadUsed Honda Brio Cars in AhmedabadTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [28]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)

In [29]:
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2012', '2014', '2019', '2018', '2010', '2022', '2013', '2021', '2016', '2011', '2015', '2017', '2012', '2019', '2020', '2016', '2020', '2019', '2017', '2017']
[[' Hyundai', ' i10'], [' Hyundai', ' i20'], [' Hyundai', ' Creta'], [' Hyundai', ' Elite', ' i20'], [' Hyundai', ' i10'], [' Hyundai', ' Creta'], [' Hyundai', ' i20'], [' Hyundai', ' Creta'], [' Hyundai', ' Elite', ' i20'], [' Hyundai', ' i10'], [' Hyundai', ' i10'], [' Hyundai', ' Elite', ' i20'], [' Hyundai', ' Eon'], [' Hyundai', ' Creta'], [' Hyundai', ' Verna'], [' Hyundai', ' Creta'], [' Hyundai', ' Creta'], [' Hyundai', ' Elite', ' i20'], [' Hyundai', ' Xcent'], [' Hyundai', ' Eon']]
['Karnavati Club, Ahmedabad', 'Naroda, Ahmedabad', 'Karnavati Club, Ahmedabad', 'Naroda, Ahmedabad', 'Naroda, Ahmedabad', 'Karnavati Club, Ahmedabad', 'Naroda, Ahmedabad', 'Karnavati Club, Ahmedabad', 'Karnavati Club, Ahmedabad', 'Naroda, Ahmedabad', 'Naroda, Ahmedabad', 'Naroda, Ahmedabad', 'Naroda, Ahmedabad', 'Naroda, Ahmedabad', 'Naroda, Ahmedabad', 'Karnavati Club, Ahmedabad', 'Karnavati Club, Ahmedabad', 'Naroda, Ahmedabad', 'Karnavati Club, Ahmedabad', 'Karnavati Club, Ahmedabad']
[['88,748'], ['64,814'], ['43,804'], ['67,470'], ['87,197'], ['4,344'], ['1,05', ',286'], ['51,463'], ['1,15', ',488'], ['1,24', ',420'], ['76,494'], ['1,16', ',263'], ['1,05', ',830'], ['82,074'], ['69,761'], ['1,07', ',787'], ['30,099'], ['1,08', ',140'], ['36,486'], ['91,991']]
[['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Diesel'], nan, ['Petrol'], nan, ['Diesel'], ['Petrol'], ['Diesel'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], nan]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['233000', '355000', '863000', '621000', '167000', '1254000', '287000', '1451000', '503000', '199000', '334000', '552000', '173000', '988000', '949000', '772000', '1389000', '581000', '481000', '280000']

In [30]:
dicto4 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [31]:
kmt1 = []
dicto4["Kmt run"]
for i in dicto4["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto4n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto4n

{'Name of Cars': [[' Hyundai', ' i10'],
  [' Hyundai', ' i20'],
  [' Hyundai', ' Creta'],
  [' Hyundai', ' Elite', ' i20'],
  [' Hyundai', ' i10'],
  [' Hyundai', ' Creta'],
  [' Hyundai', ' i20'],
  [' Hyundai', ' Creta'],
  [' Hyundai', ' Elite', ' i20'],
  [' Hyundai', ' i10'],
  [' Hyundai', ' i10'],
  [' Hyundai', ' Elite', ' i20'],
  [' Hyundai', ' Eon'],
  [' Hyundai', ' Creta'],
  [' Hyundai', ' Verna'],
  [' Hyundai', ' Creta'],
  [' Hyundai', ' Creta'],
  [' Hyundai', ' Elite', ' i20'],
  [' Hyundai', ' Xcent'],
  [' Hyundai', ' Eon']],
 'Registration Year': ['2012',
  '2014',
  '2019',
  '2018',
  '2010',
  '2022',
  '2013',
  '2021',
  '2016',
  '2011',
  '2015',
  '2017',
  '2012',
  '2019',
  '2020',
  '2016',
  '2020',
  '2019',
  '2017',
  '2017'],
 'Kmt run': [88748,
  64814,
  43804,
  67470,
  87197,
  4344,
  105286,
  51463,
  115488,
  124420,
  76494,
  116263,
  105830,
  82074,
  69761,
  107787,
  30099,
  108140,
  36486,
  91991],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Diesel'],
  nan,
  ['Petrol'],
  nan,
  ['Diesel'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  nan],
 'Price': ['233000',
  '355000',
  '863000',
  '621000',
  '167000',
  '1254000',
  '287000',
  '1451000',
  '503000',
  '199000',
  '334000',
  '552000',
  '173000',
  '988000',
  '949000',
  '772000',
  '1389000',
  '581000',
  '481000',
  '280000'],
 'Location of car': ['Karnavati Club, Ahmedabad',
  'Naroda, Ahmedabad',
  'Karnavati Club, Ahmedabad',
  'Naroda, Ahmedabad',
  'Naroda, Ahmedabad',
  'Karnavati Club, Ahmedabad',
  'Naroda, Ahmedabad',
  'Karnavati Club, Ahmedabad',
  'Karnavati Club, Ahmedabad',
  'Naroda, Ahmedabad',
  'Naroda, Ahmedabad',
  'Naroda, Ahmedabad',
  'Naroda, Ahmedabad',
  'Naroda, Ahmedabad',
  'Naroda, Ahmedabad',
  'Karnavati Club, Ahmedabad',
  'Karnavati Club, Ahmedabad',
  'Naroda, Ahmedabad',
  'Karnavati Club, Ahmedabad',
  'Karnavati Club, Ahmedabad']}

In [32]:
url5 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=4709&pinId=560001"

In [33]:
new5 = req.get(url5)
new5

In [34]:
soup = BeautifulSoup(new5.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n402 Used Cars in Bangalore - Second Hand Cars for Sale\n\n BangaloreBuy a carPopular makesMarutiHyundaiHondaRenaultTataMahindraFordVolkswagenKIAToyotaView all makesPopular ModelsHyundai i10Hyundai i20Maruti SwiftMaruti CelerioMaruti BalenoMaruti AltoRenault KwidMaruti DzireHonda CityMaruti Wagon RView all modelsBody typeHatchbackSUVSedanLuxury SUVLuxury SedanFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Swift (118)Hyundai Grand i10 (94)Maruti Celerio (72)Maruti Baleno (70)Hyundai Elite i20 (70)Renault Kwid (60)ALL BRANDSMaruti (558)Hyundai (402)Honda (141)Renault (111)Tata (72)Mahindra (50)Ford (46)Volkswagen (35)KIA (27)Toyota (18)Skoda (16)Nissan (12)Datsun (8)Jeep (4)MG (4)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Volvo (0)Jaguar (0)Budget₹ 2,00,000₹ 25,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear All402 Used cars in BangaloreSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹23,000off2011 Hyundai VernaFLUIDIC 1.6 CRDI EXManual83,963 km2nd OwnerDieselKA-03₹5,834/month ₹74,600 downpayment₹3,73,000₹3,96,000Whitefield Main Road, Bhoruka Tech Park, Benga...2012 Hyundai i10SPORTZ 1.2Manual74,961 km3rd OwnerPetrolKA-18₹4,520/month ₹57,800 downpayment₹2,89,000Whitefield Main Road, Bhoruka Tech Park, Benga...Need a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility 2015 Hyundai i20 Active1.2 SManual56,366 km2nd OwnerPetrolKA-03₹8,102/month ₹1,03,600 downpayment₹5,18,000Bellahalli, Bengaluru2012 Hyundai i10SPORTZ 1.2Manual50,312 km1st OwnerPetrolKA-05₹5,396/month ₹69,000 downpayment₹3,45,000Whitefield Main Road, Bhoruka Tech Park, Benga...2016 Hyundai CretaE PLUS 1.6 PETROLManual46,063 km2nd OwnerPetrolKA-53₹12,913/month ₹1,69,600 downpayment₹8,48,000Bellahalli, BengaluruUsed cars in Bangalore by brandMarutiHyundaiHondaRenaultTataMahindraFordVolkswagenKIAToyotaSkodaNissanDatsunJeepMGFiatMercedes Benz₹65,000off2016 Hyundai CretaSX PLUS 1.6 PETROLManual81,853 km2nd OwnerPetrolKA-01₹13,156/month ₹1,72,800 downpayment₹8,64,000₹9,29,000Bellahalli, Bengaluru2016 Hyundai VernaFLUIDIC 4S 1.6 VTVT S ATAutomatic62,295 km2nd OwnerPetrolKA-51₹8,712/month ₹1,11,400 downpayment₹5,57,000Bellahalli, Bengaluru2010 Hyundai i10MAGNA 1.2Manual1,16,372 km2nd OwnerPetrolKA-53₹3,847/month ₹49,200 downpayment₹2,46,000Bellahalli, BengaluruUsed cars in Bangalore by body typeHatchbackSUVSedanLuxury SUVLuxury Sedan₹11,000off2015 Hyundai VernaFLUIDIC 4S 1.6 VTVT S(O)Manual95,193 km2nd OwnerPetrolKA-04₹8,852/month ₹1,13,200 downpayment₹5,66,000₹5,77,000Bellahalli, Bengaluru2019 Hyundai VENUESX PLUS 1.0 TURBO DCTAutomatic27,530 km1st OwnerPetrolKA-03₹15,319/month ₹2,01,200 downpayment₹10,06,000Garuda Mall, Magrath Road, Bengaluru2014 Hyundai Grand i10ASTA AT 1.2 KAPPA VTVTAutomatic42,627 km1st OwnerPetrolKA-51₹7,789/month ₹99,600 downpayment₹4,98,000Bellahalli, BengaluruUsed cars in Bangalore by fuel typePetrolDieselCNG₹23,000off2014 Hyundai EonMAGNA +Manual29,940 km1st OwnerPetrolKA-03₹4,629/month ₹59,200 downpayment₹2,96,000₹3,19,000Sonnappanahalli\n2014 Hyundai Grand i10ASTA 1.2 KAPPA VTVTManual38,830 km2nd OwnerPetrolKA-01₹6,850/month ₹87,600 downpayment₹4,38,000Bellahalli, Bengaluru₹49,000off2019 Hyundai NEW SANTROMAGNAManual21,302 km1st OwnerPetrolKA-41₹7,398/month ₹94,600 downpayment₹4,73,000₹5,22,000GT World Mall, BengaluruUsed cars in Bangalore by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhsunder 2 lakhs2014 Hyundai Grand i10MAGNA 1.2 KAPPA VTVTManual26,002 km1st OwnerPetrolKA-03₹7,038/month ₹90,000 downpayment₹4,50,000Bellahalli, Bengaluru₹58,000off2017 Hyundai Grand i10ASTA (O) AT 1.2 KAPPA VTVTAutomatic28,418 km1st OwnerPetrolKA-20₹8,649/month ₹1,10,600 downpayment₹5,53,000₹6,11,000Bellahalli, Bengaluru2014 Hyundai Grand i10MAGNA 1.2 KAPPA VTVTManual46,110 km1st OwnerPetrolKA-53₹7,054/month ₹90,200 downpayment₹4,51,000Bellahalli, BengaluruUsed cars in Bangalore by modelHyundai i10Hyundai i20Maruti SwiftMaruti CelerioMaruti BalenoMaruti AltoRenault KwidMaruti DzireHonda CityMaruti Wagon RHyundai VernaHyundai CretaFord EcosportMahindra XUV500Renault DusterHonda JazzMaruti CiazHyundai SantroTata NEXONMaruti Ertiga₹19,000off2012 Hyundai i20MAGNA (O) 1.4 CRDIManual64,958 km2nd OwnerDieselKA-01₹5,427/month ₹69,400 downpayment₹3,47,000₹3,66,000Bellahalli, Bengaluru₹51,200off2016 Hyundai CretaSX PLUS 1.6 PETROLManual37,550 km3rd OwnerPetrolKA-04₹12,773/month ₹1,67,760 downpayment₹8,38,800₹8,90,000Whitefield Main Road, Bhoruka Tech Park, Benga...₹19,000off2010 Hyundai i10SPORTZ 1.2Manual43,529 km2nd OwnerPetrolKA-51₹4,035/month ₹51,600 downpayment₹2,58,000₹2,77,000Whitefield Main Road, Bhoruka Tech Park, Benga...HomeUsed CarsBangalore45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions BangaloreWhat are the most popular brands available for 2nd hand cars in Bangalore?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Bangalore of your choice on CARS24.What body types are available for 2nd hand cars in Bangalore?Used cars in Bangalore are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Bangalore?Of Course yes, you can buy used cars online in Bangalore from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in BangaloreWhat to check before buying a second hand car in Bangalore?Important things to check  before buying a second hand car in Bangalore are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Bangalore?You can buy used cars in Bangalore from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Bangalore?You can check second hand cars in Bangalore using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in BangaloreHow many second hand cars are available in Bangalore?402 used cars are available in Bangalore of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in BangaloreUsed Hyundai Cars in BangaloreUsed Honda Cars in BangaloreUsed Renault Cars in BangaloreUsed Tata Cars in BangaloreUsed Mahindra Cars in BangaloreUsed Ford Cars in BangaloreUsed Volkswagen Cars in BangaloreUsed KIA Cars in BangaloreUsed Toyota Cars in BangaloreUsed Skoda Cars in BangaloreUsed Nissan Cars in BangaloreUsed Datsun Cars in BangaloreUsed Jeep Cars in BangaloreUsed MG Cars in BangaloreUsed Fiat Cars in BangaloreUsed Mercedes Benz Cars in BangaloreBody :Used Hatchback Cars in BangaloreUsed SUV Cars in BangaloreUsed Sedan Cars in BangaloreUsed Luxury SUV Cars in BangaloreUsed Luxury Sedan Cars in BangaloreFuel :Used Petrol Cars in BangaloreUsed Diesel Cars in BangaloreUsed CNG Cars in BangaloreBudget :Used Cars between 5 to 10 lakhs in BangaloreUsed Cars between 2 to 5 lakhs in BangaloreUsed Cars above 10 lakhs in BangaloreUsed Cars under 2 lakhs in BangaloreModel :Used Hyundai i10 Cars in BangaloreUsed Hyundai i20 Cars in BangaloreUsed Maruti Swift Cars in BangaloreUsed Maruti Celerio Cars in BangaloreUsed Maruti Baleno Cars in BangaloreUsed Maruti Alto Cars in BangaloreUsed Renault Kwid Cars in BangaloreUsed Maruti Dzire Cars in BangaloreUsed Honda City Cars in BangaloreUsed Maruti Wagon R Cars in BangaloreUsed Hyundai Verna Cars in BangaloreUsed Hyundai Creta Cars in BangaloreUsed Ford Ecosport Cars in BangaloreUsed Mahindra XUV500 Cars in BangaloreUsed Renault Duster Cars in BangaloreUsed Honda Jazz Cars in BangaloreUsed Maruti Ciaz Cars in BangaloreUsed Hyundai Santro Cars in BangaloreUsed Tata NEXON Cars in BangaloreUsed Maruti Ertiga Cars in BangaloreTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [35]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)

In [36]:
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2011', '2012', '2015', '2012', '2016', '2016', '2016', '2010', '2015', '2019', '2014', '2014', '2014', '2019', '2014', '2017', '2014', '2012', '2016', '2010']
[[' Hyundai', ' Verna'], [' Hyundai', ' i10'], [' Hyundai', ' i20', ' Active'], [' Hyundai', ' i10'], [' Hyundai', ' Creta'], [' Hyundai', ' Creta'], [' Hyundai', ' Verna'], [' Hyundai', ' i10'], [' Hyundai', ' Verna'], [' Hyundai', ' VENUE'], [' Hyundai', ' Grand', ' i10'], [' Hyundai', ' Eon'], [' Hyundai', ' Grand', ' i10'], [' Hyundai', ' NEW', ' SANTRO'], [' Hyundai', ' Grand', ' i10'], [' Hyundai', ' Grand', ' i10'], [' Hyundai', ' Grand', ' i10'], [' Hyundai', ' i20'], [' Hyundai', ' Creta'], [' Hyundai', ' i10']]
['Whitefield Main Road, Bhoruka Tech Park, Benga...', 'Whitefield Main Road, Bhoruka Tech Park, Benga...', 'Bellahalli, Bengaluru', 'Whitefield Main Road, Bhoruka Tech Park, Benga...', 'Bellahalli, Bengaluru', 'Bellahalli, Bengaluru', 'Bellahalli, Bengaluru', 'Bellahalli, Bengaluru', 'Bellahalli, Bengaluru', 'Garuda Mall, Magrath Road, Bengaluru', 'Bellahalli, Bengaluru', 'Sonnappanahalli\n', 'Bellahalli, Bengaluru', 'GT World Mall, Bengaluru', 'Bellahalli, Bengaluru', 'Bellahalli, Bengaluru', 'Bellahalli, Bengaluru', 'Bellahalli, Bengaluru', 'Whitefield Main Road, Bhoruka Tech Park, Benga...', 'Whitefield Main Road, Bhoruka Tech Park, Benga...']
[['83,963'], ['74,961'], ['56,366'], ['50,312'], ['46,063'], ['81,853'], ['62,295'], ['1,16', ',372'], ['95,193'], ['27,530'], ['42,627'], ['29,940'], ['38,830'], ['21,302'], ['26,002'], ['28,418'], ['46,110'], ['64,958'], ['37,550'], ['43,529']]
[['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Automatic'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['373000', '289000', '518000', '345000', '848000', '864000', '557000', '246000', '566000', '1006000', '498000', '296000', '438000', '473000', '450000', '553000', '451000', '347000', '838800', '258000']

In [37]:
dicto5 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [38]:
kmt1 = []
dicto5["Kmt run"]
for i in dicto5["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto5n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto5n

{'Name of Cars': [[' Hyundai', ' Verna'],
  [' Hyundai', ' i10'],
  [' Hyundai', ' i20', ' Active'],
  [' Hyundai', ' i10'],
  [' Hyundai', ' Creta'],
  [' Hyundai', ' Creta'],
  [' Hyundai', ' Verna'],
  [' Hyundai', ' i10'],
  [' Hyundai', ' Verna'],
  [' Hyundai', ' VENUE'],
  [' Hyundai', ' Grand', ' i10'],
  [' Hyundai', ' Eon'],
  [' Hyundai', ' Grand', ' i10'],
  [' Hyundai', ' NEW', ' SANTRO'],
  [' Hyundai', ' Grand', ' i10'],
  [' Hyundai', ' Grand', ' i10'],
  [' Hyundai', ' Grand', ' i10'],
  [' Hyundai', ' i20'],
  [' Hyundai', ' Creta'],
  [' Hyundai', ' i10']],
 'Registration Year': ['2011',
  '2012',
  '2015',
  '2012',
  '2016',
  '2016',
  '2016',
  '2010',
  '2015',
  '2019',
  '2014',
  '2014',
  '2014',
  '2019',
  '2014',
  '2017',
  '2014',
  '2012',
  '2016',
  '2010'],
 'Kmt run': [83963,
  74961,
  56366,
  50312,
  46063,
  81853,
  62295,
  116372,
  95193,
  27530,
  42627,
  29940,
  38830,
  21302,
  26002,
  28418,
  46110,
  64958,
  37550,
  43529],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['373000',
  '289000',
  '518000',
  '345000',
  '848000',
  '864000',
  '557000',
  '246000',
  '566000',
  '1006000',
  '498000',
  '296000',
  '438000',
  '473000',
  '450000',
  '553000',
  '451000',
  '347000',
  '838800',
  '258000'],
 'Location of car': ['Whitefield Main Road, Bhoruka Tech Park, Benga...',
  'Whitefield Main Road, Bhoruka Tech Park, Benga...',
  'Bellahalli, Bengaluru',
  'Whitefield Main Road, Bhoruka Tech Park, Benga...',
  'Bellahalli, Bengaluru',
  'Bellahalli, Bengaluru',
  'Bellahalli, Bengaluru',
  'Bellahalli, Bengaluru',
  'Bellahalli, Bengaluru',
  'Garuda Mall, Magrath Road, Bengaluru',
  'Bellahalli, Bengaluru',
  'Sonnappanahalli\n',
  'Bellahalli, Bengaluru',
  'GT World Mall, Bengaluru',
  'Bellahalli, Bengaluru',
  'Bellahalli, Bengaluru',
  'Bellahalli, Bengaluru',
  'Bellahalli, Bengaluru',
  'Whitefield Main Road, Bhoruka Tech Park, Benga...',
  'Whitefield Main Road, Bhoruka Tech Park, Benga...']}

In [39]:
url6 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&listingSource=TabFilter&storeCityId=5732&pinId=600001"

In [40]:
new6 = req.get(url6)
new6

In [41]:
soup = BeautifulSoup(new6.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n390 Used Cars in Chennai - Second Hand Cars for Sale\n\n ChennaiBuy a carPopular makesHyundaiMarutiHondaTataFordRenaultVolkswagenMahindraDatsunNissanView all makesPopular ModelsHyundai i20Hyundai i10Maruti SwiftFord EcosportMaruti AltoMaruti BalenoMaruti DzireMaruti CelerioHonda JazzHonda CityView all modelsBody typeHatchbackSUVSedanLuxury SUVLuxury SedanFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Swift (47)Hyundai Elite i20 (45)Ford Ecosport (36)Hyundai Grand i10 (31)Maruti Baleno (26)Honda Jazz (23)ALL BRANDSHyundai (196)Maruti (194)Honda (79)Tata (73)Ford (48)Renault (43)Volkswagen (27)Mahindra (22)Datsun (19)Nissan (17)Skoda (9)Toyota (9)Jeep (6)KIA (5)MG (3)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Volvo (0)Jaguar (0)Budget₹ 2,00,000₹ 25,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear All390 Used cars in ChennaiSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹23,000off2011 Hyundai VernaFLUIDIC 1.6 CRDI EXManual1,17,255 km3rd OwnerDieselTN-01₹5,365/month ₹68,600 downpayment₹3,43,000₹3,66,000Thiruverkadu, Chennai\n2019 Hyundai VENUESX PLUS 1.0 TURBO DCTAutomatic53,193 km1st OwnerPetrolTN-22₹14,984/month ₹1,96,800 downpayment₹9,84,000NavalurNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility 2019 Hyundai VENUESX PLUS 1.0 TURBO DCT DUAL TONEAutomatic63,061 km1st OwnerPetrolTN-10₹14,466/month ₹1,90,000 downpayment₹9,50,000Thiruverkadu, Chennai\n2021 Hyundai NEW SANTROSPORTZ AMTAutomatic20,586 km1st OwnerPetrolTN-13₹9,400/month ₹1,20,200 downpayment₹6,01,000Navalur2015 Maruti Alto K10VXI AMTAutomatic61,739 km2nd OwnerPetrolTN-06₹4,895/month ₹62,600 downpayment₹3,13,000NavalurUsed cars in Chennai by brandHyundaiMarutiHondaTataFordRenaultVolkswagenMahindraDatsunNissanToyotaSkodaKIAJeepMGFiatMercedes Benz2014 Hyundai Elite i20ASTA 1.2Manual1,12,184 km1st OwnerPetrolTN-02₹7,601/month ₹97,200 downpayment₹4,86,000Thiruverkadu, Chennai\n₹27,000off2019 Maruti New Wagon-RVXI 1.2Manual47,181 km1st OwnerPetrolTN-06₹8,555/month ₹1,09,400 downpayment₹5,47,000₹5,74,000Thiruverkadu, Chennai\n₹42,000off2013 Maruti SwiftVXIManual88,192 km3rd OwnerPetrolTN-11₹5,630/month ₹72,000 downpayment₹3,60,000₹4,02,000Thiruverkadu, Chennai\nUsed cars in Chennai by body typeHatchbackSUVSedanLuxury SUVLuxury Sedan2017 Maruti IGNISZETA 1.2 AMTAutomatic42,365 km1st OwnerPetrolTN-06₹8,962/month ₹1,14,600 downpayment₹5,73,000Navalur2018 Hyundai XcentSX 1.2Manual33,682 km1st OwnerPetrolTN-11₹9,822/month ₹1,25,600 downpayment₹6,28,000Navalur₹42,000off2022 Maruti SwiftVXIManual51,140 km1st OwnerPetrolTN-07₹10,620/month ₹1,35,800 downpayment₹6,79,000₹7,21,000NavalurUsed cars in Chennai by fuel typePetrolDieselCNG2016 Maruti CelerioVXI AMTAutomatic88,890 km2nd OwnerPetrolTN-22₹6,976/month ₹89,200 downpayment₹4,46,000Navalur2016 Hyundai i10SPORTZ 1.1Manual60,778 km2nd OwnerPetrolTN-03₹6,506/month ₹83,200 downpayment₹4,16,000Navalur₹1,13,000off2019 Maruti BalenoDELTA PETROL 1.2Manual82,425 km2nd OwnerPetrolTN-20₹8,602/month ₹1,10,000 downpayment₹5,50,000₹6,63,000NavalurUsed cars in Chennai by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhsunder 2 lakhs₹7,000off2011 Hyundai i10SPORTZ 1.2Manual59,947 km3rd OwnerPetrolTN-07₹3,801/month ₹48,600 downpayment₹2,43,000₹2,50,000Thiruverkadu, Chennai\n₹70,000off2019 Hyundai Grand i10MAGNA 1.2 KAPPA VTVTManual40,240 km1st OwnerPetrolTN-14₹7,961/month ₹1,01,800 downpayment₹5,09,000₹5,79,000Navalur2016 Hyundai Grand i10SPORTZ 1.2 KAPPA VTVTManual57,479 km1st OwnerPetrolTN-11₹7,539/month ₹96,400 downpayment₹4,82,000NavalurUsed cars in Chennai by modelHyundai i20Hyundai i10Maruti SwiftFord EcosportMaruti AltoMaruti BalenoMaruti DzireMaruti CelerioHonda JazzHonda CityHonda AmazeRenault KwidTata TiagoHyundai CretaHyundai VENUEMaruti Wagon RTata ALTROZHyundai SantroHyundai VernaRenault TRIBER2017 Hyundai Grand i10SPORTZ 1.2 KAPPA VTVTManual36,882 km1st OwnerPetrolTN-07₹8,837/month ₹1,13,000 downpayment₹5,65,000Thiruverkadu, Chennai\n₹57,000off2018 Hyundai Verna1.6 VTVT SXManual32,220 km2nd OwnerPetrolTN-09₹12,418/month ₹1,58,800 downpayment₹7,94,000₹8,51,000Navalur₹72,000off2016 Hyundai Elite i20ASTA 1.2Manual35,451 km1st OwnerPetrolTN-48₹8,993/month ₹1,15,000 downpayment₹5,75,000₹6,47,000NavalurHomeUsed CarsChennai45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions ChennaiWhat are the most popular brands available for 2nd hand cars in Chennai?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Chennai of your choice on CARS24.What body types are available for 2nd hand cars in Chennai?Used cars in Chennai are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Chennai?Of Course yes, you can buy used cars online in Chennai from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in ChennaiWhat to check before buying a second hand car in Chennai?Important things to check  before buying a second hand car in Chennai are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Chennai?You can buy used cars in Chennai from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Chennai?You can check second hand cars in Chennai using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in ChennaiHow many second hand cars are available in Chennai?390 used cars are available in Chennai of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Hyundai Cars in ChennaiUsed Maruti Cars in ChennaiUsed Honda Cars in ChennaiUsed Tata Cars in ChennaiUsed Ford Cars in ChennaiUsed Renault Cars in ChennaiUsed Volkswagen Cars in ChennaiUsed Mahindra Cars in ChennaiUsed Datsun Cars in ChennaiUsed Nissan Cars in ChennaiUsed Toyota Cars in ChennaiUsed Skoda Cars in ChennaiUsed KIA Cars in ChennaiUsed Jeep Cars in ChennaiUsed MG Cars in ChennaiUsed Fiat Cars in ChennaiUsed Mercedes Benz Cars in ChennaiBody :Used Hatchback Cars in ChennaiUsed SUV Cars in ChennaiUsed Sedan Cars in ChennaiUsed Luxury SUV Cars in ChennaiUsed Luxury Sedan Cars in ChennaiFuel :Used Petrol Cars in ChennaiUsed Diesel Cars in ChennaiUsed CNG Cars in ChennaiBudget :Used Cars between 5 to 10 lakhs in ChennaiUsed Cars between 2 to 5 lakhs in ChennaiUsed Cars above 10 lakhs in ChennaiUsed Cars under 2 lakhs in ChennaiModel :Used Hyundai i20 Cars in ChennaiUsed Hyundai i10 Cars in ChennaiUsed Maruti Swift Cars in ChennaiUsed Ford Ecosport Cars in ChennaiUsed Maruti Alto Cars in ChennaiUsed Maruti Baleno Cars in ChennaiUsed Maruti Dzire Cars in ChennaiUsed Maruti Celerio Cars in ChennaiUsed Honda Jazz Cars in ChennaiUsed Honda City Cars in ChennaiUsed Honda Amaze Cars in ChennaiUsed Renault Kwid Cars in ChennaiUsed Tata Tiago Cars in ChennaiUsed Hyundai Creta Cars in ChennaiUsed Hyundai VENUE Cars in ChennaiUsed Maruti Wagon R Cars in ChennaiUsed Tata ALTROZ Cars in ChennaiUsed Hyundai Santro Cars in ChennaiUsed Hyundai Verna Cars in ChennaiUsed Renault TRIBER Cars in ChennaiTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [42]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)

In [43]:
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2011', '2019', '2019', '2021', '2015', '2014', '2019', '2013', '2017', '2018', '2022', '2016', '2016', '2019', '2011', '2019', '2016', '2017', '2018', '2016']
[[' Hyundai', ' Verna'], [' Hyundai', ' VENUE'], [' Hyundai', ' VENUE'], [' Hyundai', ' NEW', ' SANTRO'], [' Maruti', ' Alto', ' K10'], [' Hyundai', ' Elite', ' i20'], [' Maruti', ' New', ' Wagon'], [' Maruti', ' Swift'], [' Maruti', ' IGNIS'], [' Hyundai', ' Xcent'], [' Maruti', ' Swift'], [' Maruti', ' Celerio'], [' Hyundai', ' i10'], [' Maruti', ' Baleno'], [' Hyundai', ' i10'], [' Hyundai', ' Grand', ' i10'], [' Hyundai', ' Grand', ' i10'], [' Hyundai', ' Grand', ' i10'], [' Hyundai', ' Verna'], [' Hyundai', ' Elite', ' i20']]
['Thiruverkadu, Chennai\n', 'Navalur', 'Thiruverkadu, Chennai\n', 'Navalur', 'Navalur', 'Thiruverkadu, Chennai\n', 'Thiruverkadu, Chennai\n', 'Thiruverkadu, Chennai\n', 'Navalur', 'Navalur', 'Navalur', 'Navalur', 'Navalur', 'Navalur', 'Thiruverkadu, Chennai\n', 'Navalur', 'Navalur', 'Thiruverkadu, Chennai\n', 'Navalur', 'Navalur']
[['1,17', ',255'], ['53,193'], ['63,061'], ['20,586'], ['61,739'], ['1,12', ',184'], ['47,181'], ['88,192'], ['42,365'], ['33,682'], ['51,140'], ['88,890'], ['60,778'], ['82,425'], ['59,947'], ['40,240'], ['57,479'], ['36,882'], ['32,220'], ['35,451']]
[['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol']]
[['Manual'], ['Automatic'], ['Automatic'], ['Automatic'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['343000', '984000', '950000', '601000', '313000', '486000', '547000', '360000', '573000', '628000', '679000', '446000', '416000', '550000', '243000', '509000', '482000', '565000', '794000', '575000']

In [44]:
dicto6 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [45]:
kmt1 = []
dicto6["Kmt run"]
for i in dicto6["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto6n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto6n

{'Name of Cars': [[' Hyundai', ' Verna'],
  [' Hyundai', ' VENUE'],
  [' Hyundai', ' VENUE'],
  [' Hyundai', ' NEW', ' SANTRO'],
  [' Maruti', ' Alto', ' K10'],
  [' Hyundai', ' Elite', ' i20'],
  [' Maruti', ' New', ' Wagon'],
  [' Maruti', ' Swift'],
  [' Maruti', ' IGNIS'],
  [' Hyundai', ' Xcent'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Celerio'],
  [' Hyundai', ' i10'],
  [' Maruti', ' Baleno'],
  [' Hyundai', ' i10'],
  [' Hyundai', ' Grand', ' i10'],
  [' Hyundai', ' Grand', ' i10'],
  [' Hyundai', ' Grand', ' i10'],
  [' Hyundai', ' Verna'],
  [' Hyundai', ' Elite', ' i20']],
 'Registration Year': ['2011',
  '2019',
  '2019',
  '2021',
  '2015',
  '2014',
  '2019',
  '2013',
  '2017',
  '2018',
  '2022',
  '2016',
  '2016',
  '2019',
  '2011',
  '2019',
  '2016',
  '2017',
  '2018',
  '2016'],
 'Kmt run': [117255,
  53193,
  63061,
  20586,
  61739,
  112184,
  47181,
  88192,
  42365,
  33682,
  51140,
  88890,
  60778,
  82425,
  59947,
  40240,
  57479,
  36882,
  32220,
  35451],
 'Transmission': [['Manual'],
  ['Automatic'],
  ['Automatic'],
  ['Automatic'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['343000',
  '984000',
  '950000',
  '601000',
  '313000',
  '486000',
  '547000',
  '360000',
  '573000',
  '628000',
  '679000',
  '446000',
  '416000',
  '550000',
  '243000',
  '509000',
  '482000',
  '565000',
  '794000',
  '575000'],
 'Location of car': ['Thiruverkadu, Chennai\n',
  'Navalur',
  'Thiruverkadu, Chennai\n',
  'Navalur',
  'Navalur',
  'Thiruverkadu, Chennai\n',
  'Thiruverkadu, Chennai\n',
  'Thiruverkadu, Chennai\n',
  'Navalur',
  'Navalur',
  'Navalur',
  'Navalur',
  'Navalur',
  'Navalur',
  'Thiruverkadu, Chennai\n',
  'Navalur',
  'Navalur',
  'Thiruverkadu, Chennai\n',
  'Navalur',
  'Navalur']}

In [46]:
url7 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=5&pinId=122001"

In [47]:
new7 = req.get(url7)
new7

In [48]:
soup = BeautifulSoup(new7.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n1240 Used Cars in Gurgaon - Second Hand Cars for Sale\n\n GurgaonBuy a carPopular makesMarutiHyundaiHondaTataRenaultToyotaMahindraFordKIANissanView all makesPopular ModelsMaruti BalenoMaruti Wagon RMaruti SwiftHyundai i20Hyundai i10Maruti AltoMaruti BrezzaHyundai CretaRenault KwidMaruti CelerioView all modelsBody typeHatchbackSUVSedanLuxury SUVLuxury SedanFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Baleno (161)Maruti Swift (125)Honda City (108)Honda Amaze (89)Maruti Wagon R 1.0 (76)Hyundai Grand i10 (65)ALL BRANDSMaruti (817)Hyundai (423)Honda (266)Tata (99)Renault (72)Toyota (62)Mahindra (43)Ford (41)Volkswagen (32)Datsun (28)KIA (25)Nissan (19)Jeep (16)Skoda (10)MG (5)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Volvo (0)Jaguar (0)Budget₹ 1,00,000₹ 30,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear All1240 Used cars in GurgaonSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹34,000off2020 Hyundai AURAS 1.2 CNGManual67,853 km2nd OwnerCNGUP-13₹10,448/month ₹1,33,600 downpayment₹6,68,000₹7,02,000Sector-18, Noida₹19,000off2019 Maruti Vitara BrezzaVDIManual55,523 km1st OwnerDieselHR-30₹12,182/month ₹1,60,000 downpayment₹8,00,000₹8,19,000M3M Urbana, Golf Course Ext., GurugramNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹41,000off2015 Maruti SwiftVDI ABSManual1,17,499 km1st OwnerDieselHR-30₹5,881/month ₹75,200 downpayment₹3,76,000₹4,17,000Spaze Platinum, Sohna Road, Gurugram₹23,000off2018 Maruti SwiftVXIManual91,534 km2nd OwnerPetrolHR-50₹8,039/month ₹1,02,800 downpayment₹5,14,000₹5,37,000M3M Urbana, Golf Course Ext., Gurugram₹37,000off2019 Maruti Vitara BrezzaVDIManual50,767 km1st OwnerDieselHR-29₹12,231/month ₹1,56,400 downpayment₹7,82,000₹8,19,000M3M Urbana, Golf Course Ext., GurugramUsed cars in Gurgaon by brandMarutiHyundaiHondaTataToyotaRenaultMahindraFordKIANissanJeepDatsunMGVolkswagenSkodaFiatBMWAudi2015 Maruti Alto 800LXIManual35,843 km3rd OwnerPetrolHR-29₹3,660/month ₹46,800 downpayment₹2,34,000Spaze Platinum, Sohna Road, Gurugram₹72,000off2019 Maruti BalenoDELTA PETROL 1.2Manual97,494 km1st OwnerPetrolHR-30₹7,210/month ₹92,200 downpayment₹4,61,000₹5,33,000Spaze Platinum, Sohna Road, Gurugram₹34,000off2019 Maruti New Wagon-RLXI CNG 1.0Manual48,404 km1st OwnerCNGHR-29₹7,210/month ₹92,200 downpayment₹4,61,000₹4,95,000Metro Walk, Rohini, New DelhiUsed cars in Gurgaon by body typeHatchbackSUVSedanLuxury SUVLuxury Sedan2014 Maruti Wagon R 1.0VXIManual97,752 km1st OwnerPetrolHR-30₹4,583/month ₹58,600 downpayment₹2,93,000Spaze Platinum, Sohna Road, Gurugram₹31,000off2014 Maruti Wagon R 1.0VXIManual79,204 km2nd OwnerPetrolHR-30₹3,894/month ₹49,800 downpayment₹2,49,000₹2,80,000Spaze Platinum, Sohna Road, Gurugram₹45,000off2018 Maruti Vitara BrezzaVDIManual30,549 km1st OwnerDieselHR-30₹10,995/month ₹1,40,600 downpayment₹7,03,000₹7,48,000Parsvnath City Mall, FaridabadUsed cars in Gurgaon by fuel typePetrolDieselCNG₹5,000off2010 Maruti Wagon R 1.0VXIManual61,569 km2nd OwnerPetrolHR-50₹2,831/month ₹36,200 downpayment₹1,81,000₹1,86,000Chhatarpur, Delhi\n2019 Maruti AltoLXIManual18,475 km1st OwnerPetrolHR-29₹5,318/month ₹68,000 downpayment₹3,40,000GIP Mall, Noida₹15,000off2020 Maruti SwiftLXIManual44,817 km2nd OwnerPetrolHR-36₹8,227/month ₹1,05,200 downpayment₹5,26,000₹5,41,000Metro Walk, Rohini, New DelhiUsed cars in Gurgaon by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhsunder 2 lakhs₹22,000off2014 Maruti Alto K10VXIManual47,899 km1st OwnerPetrolHR-36₹3,801/month ₹48,600 downpayment₹2,43,000₹2,65,000Spaze Platinum, Sohna Road, Gurugram₹44,000off2018 Maruti SwiftVXIManual34,966 km1st OwnerPetrolHR-14₹8,805/month ₹1,12,600 downpayment₹5,63,000₹6,07,000Metro Walk, Rohini, New Delhi₹48,000off2016 Maruti Alto 800LXIManual89,634 km1st OwnerPetrolHR-82₹3,816/month ₹48,800 downpayment₹2,44,000₹2,92,000Parsvnath City Mall, FaridabadUsed cars in Gurgaon by modelMaruti BalenoMaruti Wagon RMaruti SwiftHyundai i20Hyundai i10Maruti AltoMaruti BrezzaHyundai CretaMaruti CelerioRenault KwidMaruti CiazHonda AmazeHonda CityMaruti DzireTata NEXONHyundai SantroFord EcosportMaruti ErtigaTata TiagoToyota Corolla Altis2014 Maruti Alto 800LXIManual1,02,337 km1st OwnerPetrolHR-76₹3,503/month ₹44,800 downpayment₹2,24,000Spaze Platinum, Sohna Road, Gurugram₹48,000off2016 Maruti Alto K10VXIManual32,031 km1st OwnerPetrolHR-36₹4,583/month ₹58,600 downpayment₹2,93,000₹3,41,000Spaze Platinum, Sohna Road, Gurugram₹47,000off2017 Hyundai Elite i20SPORTZ 1.2Manual81,711 km1st OwnerPetrolHR-36₹8,915/month ₹1,14,000 downpayment₹5,70,000₹6,17,000Parsvnath City Mall, FaridabadHomeUsed CarsGurgaon45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions GurgaonWhat are the most popular brands available for 2nd hand cars in Gurgaon?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Gurgaon of your choice on CARS24.What body types are available for 2nd hand cars in Gurgaon?Used cars in Gurgaon are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Gurgaon?Of Course yes, you can buy used cars online in Gurgaon from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in GurgaonWhat to check before buying a second hand car in Gurgaon?Important things to check  before buying a second hand car in Gurgaon are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Gurgaon?You can buy used cars in Gurgaon from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Gurgaon?You can check second hand cars in Gurgaon using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in GurgaonHow many second hand cars are available in Gurgaon?1240 used cars are available in Gurgaon of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in GurgaonUsed Hyundai Cars in GurgaonUsed Honda Cars in GurgaonUsed Tata Cars in GurgaonUsed Toyota Cars in GurgaonUsed Renault Cars in GurgaonUsed Mahindra Cars in GurgaonUsed Ford Cars in GurgaonUsed KIA Cars in GurgaonUsed Nissan Cars in GurgaonUsed Jeep Cars in GurgaonUsed Datsun Cars in GurgaonUsed MG Cars in GurgaonUsed Volkswagen Cars in GurgaonUsed Skoda Cars in GurgaonUsed Fiat Cars in GurgaonUsed BMW Cars in GurgaonUsed Audi Cars in GurgaonBody :Used Hatchback Cars in GurgaonUsed SUV Cars in GurgaonUsed Sedan Cars in GurgaonUsed Luxury SUV Cars in GurgaonUsed Luxury Sedan Cars in GurgaonFuel :Used Petrol Cars in GurgaonUsed Diesel Cars in GurgaonUsed CNG Cars in GurgaonBudget :Used Cars between 5 to 10 lakhs in GurgaonUsed Cars between 2 to 5 lakhs in GurgaonUsed Cars above 10 lakhs in GurgaonUsed Cars under 2 lakhs in GurgaonModel :Used Maruti Baleno Cars in GurgaonUsed Maruti Wagon R Cars in GurgaonUsed Maruti Swift Cars in GurgaonUsed Hyundai i20 Cars in GurgaonUsed Hyundai i10 Cars in GurgaonUsed Maruti Alto Cars in GurgaonUsed Maruti Brezza Cars in GurgaonUsed Hyundai Creta Cars in GurgaonUsed Maruti Celerio Cars in GurgaonUsed Renault Kwid Cars in GurgaonUsed Maruti Ciaz Cars in GurgaonUsed Honda Amaze Cars in GurgaonUsed Honda City Cars in GurgaonUsed Maruti Dzire Cars in GurgaonUsed Tata NEXON Cars in GurgaonUsed Hyundai Santro Cars in GurgaonUsed Ford Ecosport Cars in GurgaonUsed Maruti Ertiga Cars in GurgaonUsed Tata Tiago Cars in GurgaonUsed Toyota Corolla Altis Cars in GurgaonTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [49]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)

In [50]:
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2020', '2019', '2015', '2018', '2019', '2015', '2019', '2019', '2014', '2014', '2018', '2010', '2019', '2020', '2014', '2018', '2016', '2014', '2016', '2017']
[[' Hyundai', ' AURA'], [' Maruti', ' Vitara', ' Brezza'], [' Maruti', ' Swift'], [' Maruti', ' Swift'], [' Maruti', ' Vitara', ' Brezza'], [' Maruti', ' Alto', ' 800'], [' Maruti', ' Baleno'], [' Maruti', ' New', ' Wagon'], [' Maruti', ' Wagon', ' R', ' 1'], [' Maruti', ' Wagon', ' R', ' 1'], [' Maruti', ' Vitara', ' Brezza'], [' Maruti', ' Wagon', ' R', ' 1'], [' Maruti', ' Alto'], [' Maruti', ' Swift'], [' Maruti', ' Alto', ' K10'], [' Maruti', ' Swift'], [' Maruti', ' Alto', ' 800'], [' Maruti', ' Alto', ' 800'], [' Maruti', ' Alto', ' K10'], [' Hyundai', ' Elite', ' i20']]
['Sector-18, Noida', 'M3M Urbana, Golf Course Ext., Gurugram', 'Spaze Platinum, Sohna Road, Gurugram', 'M3M Urbana, Golf Course Ext., Gurugram', 'M3M Urbana, Golf Course Ext., Gurugram', 'Spaze Platinum, Sohna Road, Gurugram', 'Spaze Platinum, Sohna Road, Gurugram', 'Metro Walk, Rohini, New Delhi', 'Spaze Platinum, Sohna Road, Gurugram', 'Spaze Platinum, Sohna Road, Gurugram', 'Parsvnath City Mall, Faridabad', 'Chhatarpur, Delhi\n', 'GIP Mall, Noida', 'Metro Walk, Rohini, New Delhi', 'Spaze Platinum, Sohna Road, Gurugram', 'Metro Walk, Rohini, New Delhi', 'Parsvnath City Mall, Faridabad', 'Spaze Platinum, Sohna Road, Gurugram', 'Spaze Platinum, Sohna Road, Gurugram', 'Parsvnath City Mall, Faridabad']
[['67,853'], ['55,523'], ['1,17', ',499'], ['91,534'], ['50,767'], ['35,843'], ['97,494'], ['48,404'], ['97,752'], ['79,204'], ['30,549'], ['61,569'], ['18,475'], ['44,817'], ['47,899'], ['34,966'], ['89,634'], ['1,02', ',337'], ['32,031'], ['81,711']]
[nan, ['Diesel'], ['Diesel'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], nan, ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['668000', '800000', '376000', '514000', '782000', '234000', '461000', '461000', '293000', '249000', '703000', '181000', '340000', '526000', '243000', '563000', '244000', '224000', '293000', '570000']

In [51]:
dicto7 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [52]:
kmt1 = []
dicto7["Kmt run"]
for i in dicto7["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto7n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto7n

{'Name of Cars': [[' Hyundai', ' AURA'],
  [' Maruti', ' Vitara', ' Brezza'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Vitara', ' Brezza'],
  [' Maruti', ' Alto', ' 800'],
  [' Maruti', ' Baleno'],
  [' Maruti', ' New', ' Wagon'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Maruti', ' Vitara', ' Brezza'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Maruti', ' Alto'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Alto', ' K10'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Alto', ' 800'],
  [' Maruti', ' Alto', ' 800'],
  [' Maruti', ' Alto', ' K10'],
  [' Hyundai', ' Elite', ' i20']],
 'Registration Year': ['2020',
  '2019',
  '2015',
  '2018',
  '2019',
  '2015',
  '2019',
  '2019',
  '2014',
  '2014',
  '2018',
  '2010',
  '2019',
  '2020',
  '2014',
  '2018',
  '2016',
  '2014',
  '2016',
  '2017'],
 'Kmt run': [67853,
  55523,
  117499,
  91534,
  50767,
  35843,
  97494,
  48404,
  97752,
  79204,
  30549,
  61569,
  18475,
  44817,
  47899,
  34966,
  89634,
  102337,
  32031,
  81711],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [nan,
  ['Diesel'],
  ['Diesel'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  nan,
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['668000',
  '800000',
  '376000',
  '514000',
  '782000',
  '234000',
  '461000',
  '461000',
  '293000',
  '249000',
  '703000',
  '181000',
  '340000',
  '526000',
  '243000',
  '563000',
  '244000',
  '224000',
  '293000',
  '570000'],
 'Location of car': ['Sector-18, Noida',
  'M3M Urbana, Golf Course Ext., Gurugram',
  'Spaze Platinum, Sohna Road, Gurugram',
  'M3M Urbana, Golf Course Ext., Gurugram',
  'M3M Urbana, Golf Course Ext., Gurugram',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Metro Walk, Rohini, New Delhi',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Parsvnath City Mall, Faridabad',
  'Chhatarpur, Delhi\n',
  'GIP Mall, Noida',
  'Metro Walk, Rohini, New Delhi',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Metro Walk, Rohini, New Delhi',
  'Parsvnath City Mall, Faridabad',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Parsvnath City Mall, Faridabad']}

In [53]:
url8 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&listingSource=TabFilter&storeCityId=2920&pinId=450001"

In [54]:
new8 = req.get(url8)
new8

In [55]:
soup = BeautifulSoup(new8.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n113 Used Cars in Indore - Second Hand Cars for Sale\n\n IndoreBuy a carPopular makesMarutiHyundaiTataHondaRenaultToyotaJeepFordMahindraVolkswagenView all makesPopular ModelsMaruti BalenoHyundai i10Maruti AltoTata TiagoHyundai SantroHyundai i20Maruti SwiftMaruti CiazMaruti DzireHyundai VernaView all modelsBody typeHatchbackSedanSUVLuxury SUVFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Baleno (18)Tata Tiago (7)Hyundai Grand i10 (6)Maruti Swift (5)Maruti Ciaz (5)Hyundai Elite i20 (5)ALL BRANDSMaruti (57)Hyundai (39)Tata (17)Honda (11)Renault (6)Toyota (4)Ford (3)Jeep (3)Mahindra (2)Volkswagen (2)Datsun (1)Skoda (1)Nissan (1)KIA (0)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)MG (0)Volvo (0)Jaguar (0)Budget₹ 2,00,000₹ 15,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear All113 Used cars in IndoreSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹53,000off2016 Maruti Alto 800LXIManual41,370 km3rd OwnerPetrolMP-04₹3,550/month ₹45,400 downpayment₹2,27,000₹2,80,000Dewas Naka, Lasudia Mori₹80,000off2019 Tata NEXONXM DIESELManual1,10,321 km1st OwnerDieselMP-09₹9,071/month ₹1,16,000 downpayment₹5,80,000₹6,60,000Dewas Naka, Lasudia MoriNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹39,000off2010 Hyundai i10MAGNA 1.2Manual70,706 km2nd OwnerPetrolMP-04₹3,191/month ₹40,800 downpayment₹2,04,000₹2,43,000Dewas Naka, Lasudia Mori₹51,000off2012 Maruti Swift DzireVXIManual70,713 km1st OwnerPetrolMP-09₹4,645/month ₹59,400 downpayment₹2,97,000₹3,48,000Dewas Naka, Lasudia Mori₹94,000off2018 Maruti SwiftVXIManual47,004 km1st OwnerPetrolMP-09₹7,961/month ₹1,01,800 downpayment₹5,09,000₹6,03,000Dewas Naka, Lasudia MoriUsed cars in Indore by brandMarutiHyundaiTataHondaRenaultToyotaFordJeepVolkswagenMahindraSkodaNissanDatsunMGKIA₹46,000off2015 Hyundai Elite i20MAGNA 1.4 CRDIManual2 km2nd OwnerDieselMP-13₹6,647/month ₹85,000 downpayment₹4,25,000₹4,71,000Dewas Naka, Lasudia Mori₹57,000off2022 Hyundai VENUES 1.2Manual10,506 km1st OwnerPetrolMP-09₹13,248/month ₹1,74,000 downpayment₹8,70,000₹9,27,000Dewas Naka, Lasudia Mori₹77,000off2019 Maruti SwiftVXIManual25,984 km1st OwnerPetrolMP-13₹8,446/month ₹1,08,000 downpayment₹5,40,000₹6,17,000Dewas Naka, Lasudia MoriUsed cars in Indore by body typeHatchbackSedanSUVLuxury SUVLuxury Sedan₹67,000off2022 Maruti Alto K10LXIManual2,266 km1st OwnerPetrolMP-09₹6,976/month ₹89,200 downpayment₹4,46,000₹5,13,000Dewas Naka, Lasudia Mori₹28,000off2011 Maruti Wagon R 1.0LXIManual25,090 km1st OwnerPetrolMP-09₹3,472/month ₹44,400 downpayment₹2,22,000₹2,50,000Dewas Naka, Lasudia Mori₹71,000off2020 Hyundai CretaEX 1.5 PETROLManual38,586 km2nd OwnerPetrolMP-09₹15,699/month ₹2,06,200 downpayment₹10,31,000₹11,02,000Dewas Naka, Lasudia MoriUsed cars in Indore by fuel typePetrolDieselCNG₹65,000off2019 Maruti DzireVDIManual69,492 km1st OwnerDieselMP-04₹10,839/month ₹1,38,600 downpayment₹6,93,000₹7,58,000Dewas Naka, Lasudia Mori₹89,000off2020 Tata ALTROZXZ PETROLManual31,690 km1st OwnerPetrolMP-09₹10,104/month ₹1,29,200 downpayment₹6,46,000₹7,35,000Dewas Naka, Lasudia Mori₹1,08,000off2020 Maruti Vitara BrezzaZXIManual47,622 km2nd OwnerPetrolMP-09₹11,636/month ₹1,48,800 downpayment₹7,44,000₹8,52,000Dewas Naka, Lasudia MoriUsed cars in Indore by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhsunder 2 lakhs₹30,000off2015 Hyundai Grand i10MAGNA 1.2 KAPPA VTVTManual57,738 km1st OwnerPetrolMP-04₹5,896/month ₹75,400 downpayment₹3,77,000₹4,07,000Dewas Naka, Lasudia Mori₹47,000off2019 Hyundai EonERA +Manual84,957 km1st OwnerCNGMP-07₹4,645/month ₹59,400 downpayment₹2,97,000₹3,44,000Dewas Naka, Lasudia Mori₹26,000off2015 Maruti Wagon R 1.0LXIManual44,228 km1st OwnerPetrolMP-04₹5,271/month ₹67,400 downpayment₹3,37,000₹3,63,000Dewas Naka, Lasudia MoriUsed cars in Indore by modelMaruti BalenoHyundai i10Maruti AltoTata TiagoHyundai i20Hyundai SantroMaruti SwiftMaruti CiazHyundai VernaHonda BrioHyundai EonMaruti DzireMaruti IGNISTata NEXONMaruti Wagon RRenault KwidHyundai AURATata ALTROZHyundai VENUEHonda Amaze₹33,000off2014 Maruti CelerioVXI AMTAutomatic25,719 km1st OwnerPetrolMP-04₹5,677/month ₹72,600 downpayment₹3,63,000₹3,96,000Dewas Naka, Lasudia Mori₹31,000off2018 Maruti Alto 800VXI OManual43,031 km1st OwnerPetrolMP-04₹4,942/month ₹63,200 downpayment₹3,16,000₹3,47,000Dewas Naka, Lasudia Mori₹36,000off2016 Maruti CelerioVXIManual1,23,998 km1st OwnerPetrolMP-04₹4,817/month ₹61,600 downpayment₹3,08,000₹3,44,000Dewas Naka, Lasudia MoriHomeUsed CarsIndore45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions IndoreWhat are the most popular brands available for 2nd hand cars in Indore?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Indore of your choice on CARS24.What body types are available for 2nd hand cars in Indore?Used cars in Indore are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Indore?Of Course yes, you can buy used cars online in Indore from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in IndoreWhat to check before buying a second hand car in Indore?Important things to check  before buying a second hand car in Indore are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Indore?You can buy used cars in Indore from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Indore?You can check second hand cars in Indore using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in IndoreHow many second hand cars are available in Indore?113 used cars are available in Indore of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in IndoreUsed Hyundai Cars in IndoreUsed Tata Cars in IndoreUsed Honda Cars in IndoreUsed Renault Cars in IndoreUsed Toyota Cars in IndoreUsed Ford Cars in IndoreUsed Jeep Cars in IndoreUsed Volkswagen Cars in IndoreUsed Mahindra Cars in IndoreUsed Skoda Cars in IndoreUsed Nissan Cars in IndoreUsed Datsun Cars in IndoreUsed MG Cars in IndoreUsed KIA Cars in IndoreBody :Used Hatchback Cars in IndoreUsed Sedan Cars in IndoreUsed SUV Cars in IndoreUsed Luxury SUV Cars in IndoreUsed Luxury Sedan Cars in IndoreFuel :Used Petrol Cars in IndoreUsed Diesel Cars in IndoreUsed CNG Cars in IndoreBudget :Used Cars between 5 to 10 lakhs in IndoreUsed Cars between 2 to 5 lakhs in IndoreUsed Cars above 10 lakhs in IndoreUsed Cars under 2 lakhs in IndoreModel :Used Maruti Baleno Cars in IndoreUsed Hyundai i10 Cars in IndoreUsed Maruti Alto Cars in IndoreUsed Tata Tiago Cars in IndoreUsed Hyundai i20 Cars in IndoreUsed Hyundai Santro Cars in IndoreUsed Maruti Swift Cars in IndoreUsed Maruti Ciaz Cars in IndoreUsed Hyundai Verna Cars in IndoreUsed Honda Brio Cars in IndoreUsed Hyundai Eon Cars in IndoreUsed Maruti Dzire Cars in IndoreUsed Maruti IGNIS Cars in IndoreUsed Tata NEXON Cars in IndoreUsed Maruti Wagon R Cars in IndoreUsed Renault Kwid Cars in IndoreUsed Hyundai AURA Cars in IndoreUsed Tata ALTROZ Cars in IndoreUsed Hyundai VENUE Cars in IndoreUsed Honda Amaze Cars in IndoreTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [56]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)

In [57]:
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2016', '2019', '2010', '2012', '2018', '2015', '2022', '2019', '2022', '2011', '2020', '2019', '2020', '2020', '2015', '2019', '2015', '2014', '2018', '2016']
[[' Maruti', ' Alto', ' 800'], [' Tata', ' NEXON'], [' Hyundai', ' i10'], [' Maruti', ' Swift', ' Dzire'], [' Maruti', ' Swift'], [' Hyundai', ' Elite', ' i20'], [' Hyundai', ' VENUE'], [' Maruti', ' Swift'], [' Maruti', ' Alto', ' K10'], [' Maruti', ' Wagon', ' R', ' 1'], [' Hyundai', ' Creta'], [' Maruti', ' Dzire'], [' Tata', ' ALTROZ'], [' Maruti', ' Vitara', ' Brezza'], [' Hyundai', ' Grand', ' i10'], [' Hyundai', ' Eon'], [' Maruti', ' Wagon', ' R', ' 1'], [' Maruti', ' Celerio'], [' Maruti', ' Alto', ' 800'], [' Maruti', ' Celerio']]
['Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori', 'Dewas Naka, Lasudia Mori']
[['41,370'], ['1,10', ',321'], ['70,706'], ['70,713'], ['47,004'], nan, ['10,506'], ['25,984'], ['2,266'], ['25,090'], ['38,586'], ['69,492'], ['31,690'], ['47,622'], ['57,738'], ['84,957'], ['44,228'], ['25,719'], ['43,031'], ['1,23', ',998']]
[['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], nan, ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual']]
['227000', '580000', '204000', '297000', '509000', '425000', '870000', '540000', '446000', '222000', '1031000', '693000', '646000', '744000', '377000', '297000', '337000', '363000', '316000', '308000']

In [58]:
dicto8 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [59]:
kmt1 = []
dicto8["Kmt run"]
for i in dicto8["Kmt run"]:
    
    if i:
        a = str(i).replace('[','')
        b = a.replace(' ','')
        c = b.replace(',','')
        d = c.replace(']','')
        e = d.replace("''",'')
        kmt1.append((e.strip("'")))
    else:
        kmt1.append(' ')

dicto8n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto8n

{'Name of Cars': [[' Maruti', ' Alto', ' 800'],
  [' Tata', ' NEXON'],
  [' Hyundai', ' i10'],
  [' Maruti', ' Swift', ' Dzire'],
  [' Maruti', ' Swift'],
  [' Hyundai', ' Elite', ' i20'],
  [' Hyundai', ' VENUE'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Alto', ' K10'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Hyundai', ' Creta'],
  [' Maruti', ' Dzire'],
  [' Tata', ' ALTROZ'],
  [' Maruti', ' Vitara', ' Brezza'],
  [' Hyundai', ' Grand', ' i10'],
  [' Hyundai', ' Eon'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Maruti', ' Celerio'],
  [' Maruti', ' Alto', ' 800'],
  [' Maruti', ' Celerio']],
 'Registration Year': ['2016',
  '2019',
  '2010',
  '2012',
  '2018',
  '2015',
  '2022',
  '2019',
  '2022',
  '2011',
  '2020',
  '2019',
  '2020',
  '2020',
  '2015',
  '2019',
  '2015',
  '2014',
  '2018',
  '2016'],
 'Kmt run': ['41370',
  '110321',
  '70706',
  '70713',
  '47004',
  'nan',
  '10506',
  '25984',
  '2266',
  '25090',
  '38586',
  '69492',
  '31690',
  '47622',
  '57738',
  '84957',
  '44228',
  '25719',
  '43031',
  '123998'],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  nan,
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['227000',
  '580000',
  '204000',
  '297000',
  '509000',
  '425000',
  '870000',
  '540000',
  '446000',
  '222000',
  '1031000',
  '693000',
  '646000',
  '744000',
  '377000',
  '297000',
  '337000',
  '363000',
  '316000',
  '308000'],
 'Location of car': ['Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori',
  'Dewas Naka, Lasudia Mori']}

In [60]:
url9 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=2130&pinId=302001"

In [61]:
new9 = req.get(url9)
new9

In [62]:
soup = BeautifulSoup(new9.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n110 Used Cars in Jaipur - Second Hand Cars for Sale\n\n JaipurBuy a carPopular makesMarutiHyundaiHondaTataRenaultDatsunVolkswagenMahindraSkodaFordView all makesPopular ModelsMaruti DzireMaruti SwiftHyundai i20Maruti BalenoHonda AmazeHyundai i10Maruti CiazHonda CityMaruti Wagon RMaruti AltoView all modelsBody typeHatchbackSedanSUVLuxury SUVFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Swift (12)Maruti Baleno (12)Honda Amaze (11)Hyundai Elite i20 (9)Maruti Ciaz (8)Honda City (6)ALL BRANDSMaruti (68)Hyundai (30)Honda (22)Tata (12)Renault (9)Datsun (5)Volkswagen (5)Ford (3)Skoda (3)Mahindra (3)Jeep (2)KIA (1)Nissan (1)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Toyota (0)MG (0)Volvo (0)Jaguar (0)Budget₹ 2,00,000₹ 20,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear All110 Used cars in JaipurSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹16,000off2015 Maruti Alto 800LXIManual45,518 km1st OwnerPetrolRJ-14₹3,722/month ₹47,600 downpayment₹2,38,000₹2,54,000Mansarovar₹1,01,000off2021 Maruti Vitara BrezzaVXIManual55,657 km1st OwnerPetrolRJ-05₹11,918/month ₹1,52,400 downpayment₹7,62,000₹8,63,000MansarovarNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹21,500off2011 Maruti Swift DzireLDIManual65,848 km1st OwnerDieselRJ-14₹3,902/month ₹49,900 downpayment₹2,49,500₹2,71,000Mansarovar₹40,000off2016 Maruti Alto 800LXIManual67,039 km1st OwnerPetrolRJ-14₹3,879/month ₹49,600 downpayment₹2,48,000₹2,88,000Mansarovar₹56,000off2015 Maruti SwiftVDI ABSManual81,040 km2nd OwnerDieselRJ-45₹6,553/month ₹83,800 downpayment₹4,19,000₹4,75,000MansarovarUsed cars in Jaipur by brandMarutiHyundaiHondaTataRenaultDatsunVolkswagenFordMahindraSkodaJeepKIANissanToyotaMG₹21,000off2010 Maruti SwiftVDIManual1,04,842 km2nd OwnerDieselRJ-45₹3,722/month ₹47,600 downpayment₹2,38,000₹2,59,000Mansarovar₹86,000off2020 Tata ALTROZXE PETROLManual21,388 km1st OwnerPetrolRJ-45₹8,242/month ₹1,05,400 downpayment₹5,27,000₹6,13,000Mansarovar₹54,000off2012 Maruti Swift DzireVXIManual73,214 km1st OwnerPetrolRJ-14₹5,427/month ₹69,400 downpayment₹3,47,000₹4,01,000MansarovarUsed cars in Jaipur by body typeHatchbackSedanSUVLuxury SUVLuxury Sedan₹57,000off2017 Tata TiagoXTA PETROLAutomatic67,719 km1st OwnerPetrolRJ-14₹6,272/month ₹80,200 downpayment₹4,01,000₹4,58,000Mansarovar₹35,000off2016 Maruti Alto K10VXI AMTAutomatic75,196 km1st OwnerPetrolRJ-40₹4,927/month ₹63,000 downpayment₹3,15,000₹3,50,000Mansarovar₹89,000off2018 Maruti SwiftVXIManual97,229 km1st OwnerPetrolRJ-45₹7,804/month ₹99,800 downpayment₹4,99,000₹5,88,000MansarovarUsed cars in Jaipur by fuel typePetrolDieselCNG₹1,10,000off2021 Maruti SwiftZXI PLUS AMT DUAL TONEAutomatic7,183 km2nd OwnerPetrolRJ-45₹12,340/month ₹1,57,800 downpayment₹7,89,000₹8,99,000Mansarovar₹93,000off2019 Maruti DzireVXIManual64,916 km1st OwnerPetrolRJ-26₹9,306/month ₹1,19,000 downpayment₹5,95,000₹6,88,000Mansarovar₹91,000off2015 Maruti SwiftVXIManual71,098 km2nd OwnerPetrolRJ-29₹6,506/month ₹83,200 downpayment₹4,16,000₹5,07,000MansarovarUsed cars in Jaipur by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhsunder 2 lakhs₹42,000off2014 Hyundai i10MAGNA 1.1Manual50,789 km3rd OwnerPetrolRJ-23₹4,176/month ₹53,400 downpayment₹2,67,000₹3,09,000Mansarovar₹53,000off2020 Maruti AltoVXIManual28,328 km1st OwnerPetrolRJ-45₹5,834/month ₹74,600 downpayment₹3,73,000₹4,26,000Mansarovar₹18,000off2011 Hyundai i10MAGNA 1.2Manual74,496 km1st OwnerPetrolRJ-14₹3,425/month ₹43,800 downpayment₹2,19,000₹2,37,000MansarovarUsed cars in Jaipur by modelHyundai i20Maruti SwiftMaruti BalenoMaruti DzireHonda AmazeHyundai i10Maruti CiazHonda CityMaruti Wagon RMaruti AltoTata ALTROZTata TiagoRenault TRIBERRenault KwidHyundai VernaHonda WR-VSkoda RapidMaruti Celerio XMaruti CelerioVolkswagen Polo₹91,000off2014 Maruti ErtigaZDIManual1,00,227 km1st OwnerDieselRJ-14₹9,415/month ₹1,20,400 downpayment₹6,02,000₹6,93,000Mansarovar₹45,000off2012 Maruti Swift DzireVXIManual94,554 km1st OwnerPetrolRJ-14₹5,756/month ₹73,600 downpayment₹3,68,000₹4,13,000Mansarovar₹38,000off2012 Maruti Swift DzireVDIManual1,04,243 km1st OwnerDieselRJ-14₹5,724/month ₹73,200 downpayment₹3,66,000₹4,04,000MansarovarHomeUsed CarsJaipur45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions JaipurWhat are the most popular brands available for 2nd hand cars in Jaipur?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Jaipur of your choice on CARS24.What body types are available for 2nd hand cars in Jaipur?Used cars in Jaipur are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Jaipur?Of Course yes, you can buy used cars online in Jaipur from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in JaipurWhat to check before buying a second hand car in Jaipur?Important things to check  before buying a second hand car in Jaipur are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Jaipur?You can buy used cars in Jaipur from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Jaipur?You can check second hand cars in Jaipur using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in JaipurHow many second hand cars are available in Jaipur?110 used cars are available in Jaipur of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in JaipurUsed Hyundai Cars in JaipurUsed Honda Cars in JaipurUsed Tata Cars in JaipurUsed Renault Cars in JaipurUsed Datsun Cars in JaipurUsed Volkswagen Cars in JaipurUsed Ford Cars in JaipurUsed Mahindra Cars in JaipurUsed Skoda Cars in JaipurUsed Jeep Cars in JaipurUsed KIA Cars in JaipurUsed Nissan Cars in JaipurUsed Toyota Cars in JaipurUsed MG Cars in JaipurBody :Used Hatchback Cars in JaipurUsed Sedan Cars in JaipurUsed SUV Cars in JaipurUsed Luxury SUV Cars in JaipurUsed Luxury Sedan Cars in JaipurFuel :Used Petrol Cars in JaipurUsed Diesel Cars in JaipurUsed CNG Cars in JaipurBudget :Used Cars between 5 to 10 lakhs in JaipurUsed Cars between 2 to 5 lakhs in JaipurUsed Cars above 10 lakhs in JaipurUsed Cars under 2 lakhs in JaipurModel :Used Hyundai i20 Cars in JaipurUsed Maruti Swift Cars in JaipurUsed Maruti Baleno Cars in JaipurUsed Maruti Dzire Cars in JaipurUsed Honda Amaze Cars in JaipurUsed Hyundai i10 Cars in JaipurUsed Maruti Ciaz Cars in JaipurUsed Honda City Cars in JaipurUsed Maruti Wagon R Cars in JaipurUsed Maruti Alto Cars in JaipurUsed Tata ALTROZ Cars in JaipurUsed Tata Tiago Cars in JaipurUsed Renault TRIBER Cars in JaipurUsed Renault Kwid Cars in JaipurUsed Hyundai Verna Cars in JaipurUsed Honda WR-V Cars in JaipurUsed Skoda Rapid Cars in JaipurUsed Maruti Celerio X Cars in JaipurUsed Maruti Celerio Cars in JaipurUsed Volkswagen Polo Cars in JaipurTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n"

In [63]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)

In [64]:
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2015', '2021', '2011', '2016', '2015', '2010', '2020', '2012', '2017', '2016', '2018', '2021', '2019', '2015', '2014', '2020', '2011', '2014', '2012', '2012']
[[' Maruti', ' Alto', ' 800'], [' Maruti', ' Vitara', ' Brezza'], [' Maruti', ' Swift', ' Dzire'], [' Maruti', ' Alto', ' 800'], [' Maruti', ' Swift'], [' Maruti', ' Swift'], [' Tata', ' ALTROZ'], [' Maruti', ' Swift', ' Dzire'], [' Tata', ' Tiago'], [' Maruti', ' Alto', ' K10'], [' Maruti', ' Swift'], [' Maruti', ' Swift'], [' Maruti', ' Dzire'], [' Maruti', ' Swift'], [' Hyundai', ' i10'], [' Maruti', ' Alto'], [' Hyundai', ' i10'], [' Maruti', ' Ertiga'], [' Maruti', ' Swift', ' Dzire'], [' Maruti', ' Swift', ' Dzire']]
['Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar', 'Mansarovar']
[['45,518'], ['55,657'], ['65,848'], ['67,039'], ['81,040'], ['1,04', ',842'], ['21,388'], ['73,214'], ['67,719'], ['75,196'], ['97,229'], ['7,183'], ['64,916'], ['71,098'], ['50,789'], ['28,328'], ['74,496'], ['1,00', ',227'], ['94,554'], ['1,04', ',243']]
[['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Diesel'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Diesel']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Automatic'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['238000', '762000', '249500', '248000', '419000', '238000', '527000', '347000', '401000', '315000', '499000', '789000', '595000', '416000', '267000', '373000', '219000', '602000', '368000', '366000']

In [65]:
dicto9 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [66]:
kmt1 = []
dicto9["Kmt run"]
for i in dicto9["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto9n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto9n

{'Name of Cars': [[' Maruti', ' Alto', ' 800'],
  [' Maruti', ' Vitara', ' Brezza'],
  [' Maruti', ' Swift', ' Dzire'],
  [' Maruti', ' Alto', ' 800'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Swift'],
  [' Tata', ' ALTROZ'],
  [' Maruti', ' Swift', ' Dzire'],
  [' Tata', ' Tiago'],
  [' Maruti', ' Alto', ' K10'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Dzire'],
  [' Maruti', ' Swift'],
  [' Hyundai', ' i10'],
  [' Maruti', ' Alto'],
  [' Hyundai', ' i10'],
  [' Maruti', ' Ertiga'],
  [' Maruti', ' Swift', ' Dzire'],
  [' Maruti', ' Swift', ' Dzire']],
 'Registration Year': ['2015',
  '2021',
  '2011',
  '2016',
  '2015',
  '2010',
  '2020',
  '2012',
  '2017',
  '2016',
  '2018',
  '2021',
  '2019',
  '2015',
  '2014',
  '2020',
  '2011',
  '2014',
  '2012',
  '2012'],
 'Kmt run': [45518,
  55657,
  65848,
  67039,
  81040,
  104842,
  21388,
  73214,
  67719,
  75196,
  97229,
  7183,
  64916,
  71098,
  50789,
  28328,
  74496,
  100227,
  94554,
  104243],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Automatic'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Diesel'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Diesel']],
 'Price': ['238000',
  '762000',
  '249500',
  '248000',
  '419000',
  '238000',
  '527000',
  '347000',
  '401000',
  '315000',
  '499000',
  '789000',
  '595000',
  '416000',
  '267000',
  '373000',
  '219000',
  '602000',
  '368000',
  '366000'],
 'Location of car': ['Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar',
  'Mansarovar']}

In [67]:
url10="https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=777&pinId=700001"

In [68]:
new10 = req.get(url10)
new10

In [69]:
soup = BeautifulSoup(new10.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n225 Used Cars in Kolkata - Second Hand Cars for Sale\n\n KolkataBuy a carPopular makesMarutiHyundaiHondaTataMahindraRenaultKIAToyotaFordDatsunView all makesPopular ModelsMaruti AltoHyundai i10Maruti SwiftHonda CityHyundai i20Maruti Wagon RMaruti DzireMaruti CelerioMaruti BalenoHyundai SantroView all modelsBody typeHatchbackSedanSUVLuxury SUVLuxury SedanFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Swift (20)Honda City (16)Maruti Celerio (14)Maruti Swift Dzire (12)Maruti Baleno (12)Maruti Alto 800 (12)ALL BRANDSMaruti (125)Hyundai (80)Honda (38)Tata (20)Mahindra (16)Renault (14)KIA (10)Toyota (10)Ford (7)Datsun (4)Volkswagen (3)Skoda (2)Nissan (2)MG (2)Jeep (1)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Volvo (0)Jaguar (0)Budget₹ 1,00,000₹ 20,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear All225 Used cars in KolkataSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New2015 Hyundai VernaFLUIDIC 4S 1.6 VTVT S(O)Manual79,281 km2nd OwnerPetrolWB-02₹6,741/month ₹86,200 downpayment₹4,31,000Barasat, Kolkata₹10,000off2015 Maruti Alto 800LXIManual38,595 km1st OwnerPetrolWB-18₹3,331/month ₹42,600 downpayment₹2,13,000₹2,23,000Barasat, KolkataNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹25,000off2017 Hyundai EonMAGNA+ SEManual42,874 km1st OwnerPetrolWB-06₹4,520/month ₹57,800 downpayment₹2,89,000₹3,14,000Barasat, Kolkata₹21,000off2016 Maruti Alto 800LXIManual27,186 km1st OwnerPetrolWB-26₹4,176/month ₹53,400 downpayment₹2,67,000₹2,88,000Barasat, Kolkata2019 Hyundai Verna1.6 VTVT SXManual26,288 km1st OwnerPetrolWB-08₹12,745/month ₹1,67,400 downpayment₹8,37,000Barasat, KolkataUsed cars in Kolkata by brandMarutiHyundaiHondaTataMahindraRenaultToyotaKIAFordDatsunVolkswagenSkodaNissanMGJeepJaguar2015 Maruti Alto K10VXIManual31,316 km1st OwnerPetrolWB-16₹3,363/month ₹43,000 downpayment₹2,15,000Barasat, Kolkata₹29,000off2015 Maruti BalenoDELTA PETROL 1.2Manual75,441 km1st OwnerPetrolWB-02₹6,084/month ₹77,800 downpayment₹3,89,000₹4,18,000Acropolis Mall, Kolkata2018 Hyundai Elite i20ASTA 1.2Manual66,485 km1st OwnerPetrolWB-08₹8,899/month ₹1,13,800 downpayment₹5,69,000Barasat, KolkataUsed cars in Kolkata by body typeHatchbackSedanSUVLuxury SUVLuxury Sedan2020 Hyundai NEW I20ASTA 1.2 MTManual41,881 km1st OwnerPetrolWB-08₹11,151/month ₹1,42,600 downpayment₹7,13,000Acropolis Mall, Kolkata₹31,000off2010 Hyundai i20MAGNA 1.2Manual87,845 km1st OwnerPetrolWB-06₹2,893/month ₹37,000 downpayment₹1,85,000₹2,16,000Acropolis Mall, Kolkata₹19,000off2010 Maruti SwiftLXIManual71,156 km2nd OwnerPetrolWB-38₹2,502/month ₹32,000 downpayment₹1,60,000₹1,79,000Barasat, KolkataUsed cars in Kolkata by fuel typePetrolDieselCNG2018 Hyundai Grand i10SPORTZ 1.2 KAPPA VTVTManual33,168 km1st OwnerPetrolWB-20₹6,882/month ₹88,000 downpayment₹4,40,000Acropolis Mall, Kolkata₹14,000off2010 Maruti A StarLXIManual54,501 km1st OwnerPetrolWB-24₹2,111/month ₹27,000 downpayment₹1,35,000₹1,49,000Acropolis Mall, Kolkata₹70,000off2016 Maruti Alto 800LXIManual36,270 km1st OwnerPetrolWB-02₹3,269/month ₹41,800 downpayment₹2,09,000₹2,79,000Barasat, KolkataUsed cars in Kolkata by budgetbetween 2 to 5 lakhsbetween 5 to 10 lakhsunder 2 lakhsabove 10 lakhs₹65,000off2019 Maruti Alto 800LXIManual2,707 km1st OwnerPetrolWB-02₹4,223/month ₹54,000 downpayment₹2,70,000₹3,35,000Barasat, Kolkata₹12,000off2015 Hyundai EonD-LITE+Manual19,090 km1st OwnerPetrolWB-24₹2,987/month ₹38,200 downpayment₹1,91,000₹2,03,000Barasat, Kolkata2022 Maruti SwiftVXIManual1,775 km1st OwnerPetrolWB-24₹10,072/month ₹1,28,800 downpayment₹6,44,000Barasat, KolkataUsed cars in Kolkata by modelMaruti AltoHyundai i10Maruti SwiftHonda CityHyundai i20Maruti Wagon RMaruti DzireMaruti CelerioMaruti BalenoHonda AmazeHyundai SantroRenault KwidTata TiagoMaruti CiazKIA SELTOSHyundai EonFord EcosportHyundai VENUEHyundai VernaMahindra XUV 3OO₹1,42,000off2018 Maruti CiazDELTA 1.5 SHVS MT PETROLManual52,130 km1st OwnerPetrolWB-02₹8,758/month ₹1,12,000 downpayment₹5,60,000₹7,02,000Barasat, Kolkata₹16,000off2010 Maruti Wagon RVXI MINORManual76,672 km3rd OwnerPetrolWB-06₹2,143/month ₹27,400 downpayment₹1,37,000₹1,53,000Barasat, Kolkata₹18,000off2010 Hyundai i10SPORTZ 1.2Manual60,585 km1st OwnerPetrolWB-06₹2,596/month ₹33,200 downpayment₹1,66,000₹1,84,000Acropolis Mall, KolkataHomeUsed CarsKolkata45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions KolkataWhat are the most popular brands available for 2nd hand cars in Kolkata?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Kolkata of your choice on CARS24.What body types are available for 2nd hand cars in Kolkata?Used cars in Kolkata are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Kolkata?Of Course yes, you can buy used cars online in Kolkata from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in KolkataWhat to check before buying a second hand car in Kolkata?Important things to check  before buying a second hand car in Kolkata are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Kolkata?You can buy used cars in Kolkata from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Kolkata?You can check second hand cars in Kolkata using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in KolkataHow many second hand cars are available in Kolkata?225 used cars are available in Kolkata of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in KolkataUsed Hyundai Cars in KolkataUsed Honda Cars in KolkataUsed Tata Cars in KolkataUsed Mahindra Cars in KolkataUsed Renault Cars in KolkataUsed Toyota Cars in KolkataUsed KIA Cars in KolkataUsed Ford Cars in KolkataUsed Datsun Cars in KolkataUsed Volkswagen Cars in KolkataUsed Skoda Cars in KolkataUsed Nissan Cars in KolkataUsed MG Cars in KolkataUsed Jeep Cars in KolkataUsed Jaguar Cars in KolkataBody :Used Hatchback Cars in KolkataUsed Sedan Cars in KolkataUsed SUV Cars in KolkataUsed Luxury SUV Cars in KolkataUsed Luxury Sedan Cars in KolkataFuel :Used Petrol Cars in KolkataUsed Diesel Cars in KolkataUsed CNG Cars in KolkataBudget :Used Cars between 2 to 5 lakhs in KolkataUsed Cars between 5 to 10 lakhs in KolkataUsed Cars under 2 lakhs in KolkataUsed Cars above 10 lakhs in KolkataModel :Used Maruti Alto Cars in KolkataUsed Hyundai i10 Cars in KolkataUsed Maruti Swift Cars in KolkataUsed Honda City Cars in KolkataUsed Hyundai i20 Cars in KolkataUsed Maruti Wagon R Cars in KolkataUsed Maruti Dzire Cars in KolkataUsed Maruti Celerio Cars in KolkataUsed Maruti Baleno Cars in KolkataUsed Honda Amaze Cars in KolkataUsed Hyundai Santro Cars in KolkataUsed Renault Kwid Cars in KolkataUsed Tata Tiago Cars in KolkataUsed Maruti Ciaz Cars in KolkataUsed KIA SELTOS Cars in KolkataUsed Hyundai Eon Cars in KolkataUsed Ford Ecosport Cars in KolkataUsed Hyundai VENUE Cars in KolkataUsed Hyundai Verna Cars in KolkataUsed Mahindra XUV 3OO Cars in KolkataTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [70]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)

In [71]:
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2015', '2015', '2017', '2016', '2019', '2015', '2015', '2018', '2020', '2010', '2010', '2018', '2010', '2016', '2019', '2015', '2022', '2018', '2010', '2010']
[[' Hyundai', ' Verna'], [' Maruti', ' Alto', ' 800'], [' Hyundai', ' Eon'], [' Maruti', ' Alto', ' 800'], [' Hyundai', ' Verna'], [' Maruti', ' Alto', ' K10'], [' Maruti', ' Baleno'], [' Hyundai', ' Elite', ' i20'], [' Hyundai', ' NEW', ' I20'], [' Hyundai', ' i20'], [' Maruti', ' Swift'], [' Hyundai', ' Grand', ' i10'], [' Maruti', ' A', ' Star'], [' Maruti', ' Alto', ' 800'], [' Maruti', ' Alto', ' 800'], [' Hyundai', ' Eon'], [' Maruti', ' Swift'], [' Maruti', ' Ciaz'], [' Maruti', ' Wagon', ' R'], [' Hyundai', ' i10']]
['Barasat, Kolkata', 'Barasat, Kolkata', 'Barasat, Kolkata', 'Barasat, Kolkata', 'Barasat, Kolkata', 'Barasat, Kolkata', 'Acropolis Mall, Kolkata', 'Barasat, Kolkata', 'Acropolis Mall, Kolkata', 'Acropolis Mall, Kolkata', 'Barasat, Kolkata', 'Acropolis Mall, Kolkata', 'Acropolis Mall, Kolkata', 'Barasat, Kolkata', 'Barasat, Kolkata', 'Barasat, Kolkata', 'Barasat, Kolkata', 'Barasat, Kolkata', 'Barasat, Kolkata', 'Acropolis Mall, Kolkata']
[['79,281'], ['38,595'], ['42,874'], ['27,186'], ['26,288'], ['31,316'], ['75,441'], ['66,485'], ['41,881'], ['87,845'], ['71,156'], ['33,168'], ['54,501'], ['36,270'], ['2,707'], ['19,090'], ['1,775'], ['52,130'], ['76,672'], ['60,585']]
[['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['431000', '213000', '289000', '267000', '837000', '215000', '389000', '569000', '713000', '185000', '160000', '440000', '135000', '209000', '270000', '191000', '644000', '560000', '137000', '166000']

In [72]:
dicto10 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [73]:
kmt1 = []
dicto10["Kmt run"]
for i in dicto10["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto10n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto10n

{'Name of Cars': [[' Hyundai', ' Verna'],
  [' Maruti', ' Alto', ' 800'],
  [' Hyundai', ' Eon'],
  [' Maruti', ' Alto', ' 800'],
  [' Hyundai', ' Verna'],
  [' Maruti', ' Alto', ' K10'],
  [' Maruti', ' Baleno'],
  [' Hyundai', ' Elite', ' i20'],
  [' Hyundai', ' NEW', ' I20'],
  [' Hyundai', ' i20'],
  [' Maruti', ' Swift'],
  [' Hyundai', ' Grand', ' i10'],
  [' Maruti', ' A', ' Star'],
  [' Maruti', ' Alto', ' 800'],
  [' Maruti', ' Alto', ' 800'],
  [' Hyundai', ' Eon'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Ciaz'],
  [' Maruti', ' Wagon', ' R'],
  [' Hyundai', ' i10']],
 'Registration Year': ['2015',
  '2015',
  '2017',
  '2016',
  '2019',
  '2015',
  '2015',
  '2018',
  '2020',
  '2010',
  '2010',
  '2018',
  '2010',
  '2016',
  '2019',
  '2015',
  '2022',
  '2018',
  '2010',
  '2010'],
 'Kmt run': [79281,
  38595,
  42874,
  27186,
  26288,
  31316,
  75441,
  66485,
  41881,
  87845,
  71156,
  33168,
  54501,
  36270,
  2707,
  19090,
  1775,
  52130,
  76672,
  60585],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['431000',
  '213000',
  '289000',
  '267000',
  '837000',
  '215000',
  '389000',
  '569000',
  '713000',
  '185000',
  '160000',
  '440000',
  '135000',
  '209000',
  '270000',
  '191000',
  '644000',
  '560000',
  '137000',
  '166000'],
 'Location of car': ['Barasat, Kolkata',
  'Barasat, Kolkata',
  'Barasat, Kolkata',
  'Barasat, Kolkata',
  'Barasat, Kolkata',
  'Barasat, Kolkata',
  'Acropolis Mall, Kolkata',
  'Barasat, Kolkata',
  'Acropolis Mall, Kolkata',
  'Acropolis Mall, Kolkata',
  'Barasat, Kolkata',
  'Acropolis Mall, Kolkata',
  'Acropolis Mall, Kolkata',
  'Barasat, Kolkata',
  'Barasat, Kolkata',
  'Barasat, Kolkata',
  'Barasat, Kolkata',
  'Barasat, Kolkata',
  'Barasat, Kolkata',
  'Acropolis Mall, Kolkata']}

In [74]:
url11= "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=6356&pinId=682001"

In [75]:
new11 = req.get(url11)
new11

In [76]:
soup = BeautifulSoup(new11.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n164 Used Cars in Kochi - Second Hand Cars for Sale\n\n KochiBuy a carPopular makesMarutiHyundaiTataHondaRenaultDatsunMahindraFordVolkswagenNissanView all makesPopular ModelsHyundai i10Maruti AltoHyundai i20Maruti SwiftMaruti BalenoTata TiagoMaruti Wagon RHyundai SantroDatsun Redi GoRenault KwidView all modelsBody typeHatchbackSUVSedanLuxury SUVLuxury SedanFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsHyundai Grand i10 (16)Maruti Swift (13)Maruti Baleno (13)Tata Tiago (12)Hyundai Elite i20 (10)Maruti Alto 800 (10)ALL BRANDSMaruti (70)Hyundai (65)Tata (29)Honda (20)Renault (18)Datsun (12)Mahindra (10)Ford (8)Volkswagen (6)Nissan (4)MG (2)Skoda (1)Jeep (1)Toyota (1)KIA (0)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Volvo (0)Jaguar (0)Budget₹ 1,00,000₹ 20,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear All164 Used cars in KochiSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New2011 Hyundai i20MAGNA 1.4 CRDIManual81,095 km2nd OwnerDieselKL-23₹3,801/month ₹48,600 downpayment₹2,43,000Kakkanad, Kochi₹36,000off2020 Tata NEXONXZ PLUS PETROLManual75,840 km1st OwnerPetrolKL-02₹13,994/month ₹1,83,800 downpayment₹9,19,000₹9,55,000Kakkanad, KochiNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹15,000off2010 Maruti Zen EstiloLXIManual91,626 km1st OwnerPetrolKL-01₹2,315/month ₹29,600 downpayment₹1,48,000₹1,63,000Kakkanad, Kochi₹6,000off2012 Hyundai i20MAGNA 1.4 CRDIManual93,134 km2nd OwnerDieselKL-02₹4,614/month ₹59,000 downpayment₹2,95,000₹3,01,000Kakkanad, Kochi₹53,000off2015 Maruti Swift DzireVDI ABSManual54,780 km1st OwnerDieselKL-31₹8,602/month ₹1,10,000 downpayment₹5,50,000₹6,03,000Kakkanad, KochiUsed cars in Kochi by brandMarutiHyundaiTataHondaRenaultDatsunMahindraFordVolkswagenNissanMGJeepToyotaSkodaBMWKIA₹15,000off2011 Maruti SwiftVDIManual99,490 km2nd OwnerDieselKL-01₹4,489/month ₹57,400 downpayment₹2,87,000₹3,02,000Kakkanad, Kochi₹24,000off2015 Maruti CelerioVXI AMTAutomatic99,277 km1st OwnerPetrolKL-02₹6,522/month ₹83,400 downpayment₹4,17,000₹4,41,000Kakkanad, Kochi₹26,000off2017 Maruti CelerioVXIManual97,978 km1st OwnerPetrolKL-27₹5,818/month ₹74,400 downpayment₹3,72,000₹3,98,000Kakkanad, KochiUsed cars in Kochi by body typeHatchbackSUVSedanLuxury SedanLuxury SUV₹13,000off2010 Maruti Alto K10LXIManual86,618 km1st OwnerPetrolKL-05₹2,800/month ₹35,800 downpayment₹1,79,000₹1,92,000Kakkanad, Kochi₹7,000off2018 Hyundai EonERA +Manual37,518 km1st OwnerPetrolKL-20₹4,989/month ₹63,800 downpayment₹3,19,000₹3,26,000Kakkanad, Kochi₹15,000off2010 Hyundai i10MAGNA 1.2Manual97,307 km2nd OwnerPetrolKL-27₹3,097/month ₹39,600 downpayment₹1,98,000₹2,13,000Kakkanad, KochiUsed cars in Kochi by fuel typePetrolDieselCNG₹37,000off2017 Hyundai Grand i10SPORTZ 1.2 KAPPA VTVTManual50,347 km1st OwnerPetrolKL-27₹7,413/month ₹94,800 downpayment₹4,74,000₹5,11,000Kakkanad, Kochi₹69,000off2018 Hyundai Verna1.6 VTVT SXManual87,005 km2nd OwnerPetrolKL-32₹10,917/month ₹1,39,600 downpayment₹6,98,000₹7,67,000Kakkanad, Kochi₹43,000off2018 Tata TiagoXT PETROLManual98,088 km1st OwnerPetrolKL-40₹5,959/month ₹76,200 downpayment₹3,81,000₹4,24,000Kakkanad, KochiUsed cars in Kochi by budgetbetween 2 to 5 lakhsbetween 5 to 10 lakhsabove 10 lakhsunder 2 lakhs₹19,000off2013 Maruti Alto K10LXIManual78,187 km1st OwnerPetrolKL-08₹3,347/month ₹42,800 downpayment₹2,14,000₹2,33,000Kakkanad, Kochi₹11,000off2012 Maruti Alto K10VXIManual55,837 km1st OwnerPetrolKL-22₹3,707/month ₹47,400 downpayment₹2,37,000₹2,48,000Kakkanad, Kochi₹17,000off2011 Maruti RitzLXIManual1,06,880 km3rd OwnerPetrolKL-08₹3,644/month ₹46,600 downpayment₹2,33,000₹2,50,000Kakkanad, KochiUsed cars in Kochi by modelHyundai i10Maruti AltoHyundai i20Maruti SwiftMaruti BalenoTata TiagoMaruti Wagon RDatsun Redi GoHyundai SantroRenault KwidHonda CityHyundai EonTata NEXONTata ALTROZMaruti DzireRenault TRIBERHonda JazzTata TIGORRenault DusterMaruti Celerio₹30,000off2017 Maruti Wagon R 1.0LXIManual45,376 km1st OwnerPetrolKL-66₹5,740/month ₹73,400 downpayment₹3,67,000₹3,97,000Kakkanad, Kochi₹18,000off2018 Tata TiagoXZ PETROLManual1,20,667 km1st OwnerPetrolKL-07₹5,802/month ₹74,200 downpayment₹3,71,000₹3,89,000Kakkanad, Kochi₹39,000off2018 Maruti Wagon R 1.0VXI AMTAutomatic35,649 km1st OwnerPetrolKL-24₹6,788/month ₹86,800 downpayment₹4,34,000₹4,73,000Kakkanad, KochiHomeUsed CarsKochi45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions KochiWhat are the most popular brands available for 2nd hand cars in Kochi?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Kochi of your choice on CARS24.What body types are available for 2nd hand cars in Kochi?Used cars in Kochi are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Kochi?Of Course yes, you can buy used cars online in Kochi from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in KochiWhat to check before buying a second hand car in Kochi?Important things to check  before buying a second hand car in Kochi are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Kochi?You can buy used cars in Kochi from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Kochi?You can check second hand cars in Kochi using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in KochiHow many second hand cars are available in Kochi?164 used cars are available in Kochi of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in KochiUsed Hyundai Cars in KochiUsed Tata Cars in KochiUsed Honda Cars in KochiUsed Renault Cars in KochiUsed Datsun Cars in KochiUsed Mahindra Cars in KochiUsed Ford Cars in KochiUsed Volkswagen Cars in KochiUsed Nissan Cars in KochiUsed MG Cars in KochiUsed Jeep Cars in KochiUsed Toyota Cars in KochiUsed Skoda Cars in KochiUsed BMW Cars in KochiUsed KIA Cars in KochiBody :Used Hatchback Cars in KochiUsed SUV Cars in KochiUsed Sedan Cars in KochiUsed Luxury Sedan Cars in KochiUsed Luxury SUV Cars in KochiFuel :Used Petrol Cars in KochiUsed Diesel Cars in KochiUsed CNG Cars in KochiBudget :Used Cars between 2 to 5 lakhs in KochiUsed Cars between 5 to 10 lakhs in KochiUsed Cars above 10 lakhs in KochiUsed Cars under 2 lakhs in KochiModel :Used Hyundai i10 Cars in KochiUsed Maruti Alto Cars in KochiUsed Hyundai i20 Cars in KochiUsed Maruti Swift Cars in KochiUsed Maruti Baleno Cars in KochiUsed Tata Tiago Cars in KochiUsed Maruti Wagon R Cars in KochiUsed Datsun Redi Go Cars in KochiUsed Hyundai Santro Cars in KochiUsed Renault Kwid Cars in KochiUsed Honda City Cars in KochiUsed Hyundai Eon Cars in KochiUsed Tata NEXON Cars in KochiUsed Tata ALTROZ Cars in KochiUsed Maruti Dzire Cars in KochiUsed Renault TRIBER Cars in KochiUsed Honda Jazz Cars in KochiUsed Tata TIGOR Cars in KochiUsed Renault Duster Cars in KochiUsed Maruti Celerio Cars in KochiTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n"

In [77]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2011', '2020', '2010', '2012', '2015', '2011', '2015', '2017', '2010', '2018', '2010', '2017', '2018', '2018', '2013', '2012', '2011', '2017', '2018', '2018']
[[' Hyundai', ' i20'], [' Tata', ' NEXON'], [' Maruti', ' Zen', ' Estilo'], [' Hyundai', ' i20'], [' Maruti', ' Swift', ' Dzire'], [' Maruti', ' Swift'], [' Maruti', ' Celerio'], [' Maruti', ' Celerio'], [' Maruti', ' Alto', ' K10'], [' Hyundai', ' Eon'], [' Hyundai', ' i10'], [' Hyundai', ' Grand', ' i10'], [' Hyundai', ' Verna'], [' Tata', ' Tiago'], [' Maruti', ' Alto', ' K10'], [' Maruti', ' Alto', ' K10'], [' Maruti', ' Ritz'], [' Maruti', ' Wagon', ' R', ' 1'], [' Tata', ' Tiago'], [' Maruti', ' Wagon', ' R', ' 1']]
['Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi', 'Kakkanad, Kochi']
[['81,095'], ['75,840'], ['91,626'], ['93,134'], ['54,780'], ['99,490'], ['99,277'], ['97,978'], ['86,618'], ['37,518'], ['97,307'], ['50,347'], ['87,005'], ['98,088'], ['78,187'], ['55,837'], ['1,06', ',880'], ['45,376'], ['1,20', ',667'], ['35,649']]
[['Diesel'], ['Petrol'], ['Petrol'], ['Diesel'], ['Diesel'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic']]
['243000', '919000', '148000', '295000', '550000', '287000', '417000', '372000', '179000', '319000', '198000', '474000', '698000', '381000', '214000', '237000', '233000', '367000', '371000', '434000']

In [78]:
dicto11 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [79]:
kmt1 = []
dicto11["Kmt run"]
for i in dicto11["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto11n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto11n

{'Name of Cars': [[' Hyundai', ' i20'],
  [' Tata', ' NEXON'],
  [' Maruti', ' Zen', ' Estilo'],
  [' Hyundai', ' i20'],
  [' Maruti', ' Swift', ' Dzire'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Celerio'],
  [' Maruti', ' Celerio'],
  [' Maruti', ' Alto', ' K10'],
  [' Hyundai', ' Eon'],
  [' Hyundai', ' i10'],
  [' Hyundai', ' Grand', ' i10'],
  [' Hyundai', ' Verna'],
  [' Tata', ' Tiago'],
  [' Maruti', ' Alto', ' K10'],
  [' Maruti', ' Alto', ' K10'],
  [' Maruti', ' Ritz'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Tata', ' Tiago'],
  [' Maruti', ' Wagon', ' R', ' 1']],
 'Registration Year': ['2011',
  '2020',
  '2010',
  '2012',
  '2015',
  '2011',
  '2015',
  '2017',
  '2010',
  '2018',
  '2010',
  '2017',
  '2018',
  '2018',
  '2013',
  '2012',
  '2011',
  '2017',
  '2018',
  '2018'],
 'Kmt run': [81095,
  75840,
  91626,
  93134,
  54780,
  99490,
  99277,
  97978,
  86618,
  37518,
  97307,
  50347,
  87005,
  98088,
  78187,
  55837,
  106880,
  45376,
  120667,
  35649],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic']],
 'Fuel type': [['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Diesel'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['243000',
  '919000',
  '148000',
  '295000',
  '550000',
  '287000',
  '417000',
  '372000',
  '179000',
  '319000',
  '198000',
  '474000',
  '698000',
  '381000',
  '214000',
  '237000',
  '233000',
  '367000',
  '371000',
  '434000'],
 'Location of car': ['Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi',
  'Kakkanad, Kochi']}

In [80]:
url12="https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=290&pinId=226001"

In [81]:
new12 = req.get(url12)
new12

In [82]:
soup = BeautifulSoup(new12.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n133 Used Cars in Lucknow - Second Hand Cars for Sale\n\n LucknowBuy a carPopular makesMarutiHyundaiHondaToyotaFordTataRenaultMahindraVolkswagenNissanView all makesPopular ModelsHyundai i10Maruti SwiftMaruti Wagon RMaruti DzireHonda CityMaruti BrezzaMaruti AltoHyundai i20Maruti IGNISFord EcosportView all modelsBody typeHatchbackSUVSedanFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Swift (14)Hyundai Grand i10 (11)Honda City (9)Maruti Vitara Brezza (9)Maruti New Wagon-R (8)Ford Ecosport (7)ALL BRANDSMaruti (80)Hyundai (45)Honda (19)Toyota (9)Ford (8)Tata (8)Renault (7)Mahindra (5)Skoda (2)Nissan (2)Volkswagen (2)KIA (1)Datsun (1)BMW (0)Mercedes Benz (0)Audi (0)Jeep (0)Fiat (0)MG (0)Volvo (0)Jaguar (0)Budget₹ 1,50,000₹ 15,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear All133 Used cars in LucknowSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New2015 Maruti Swift DzireZXIManual94,408 km2nd OwnerPetrolUP-32₹7,069/month ₹90,400 downpayment₹4,52,000Ansal Golf City, Lucknow₹54,000off2019 Hyundai CretaSX AT 1.6 DIESELAutomatic60,455 km1st OwnerDieselUP-78₹17,222/month ₹2,26,200 downpayment₹11,31,000₹11,85,000Ansal Golf City, LucknowNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹46,000off2019 Maruti SwiftVXIManual67,829 km1st OwnerPetrolUP-32₹9,009/month ₹1,15,200 downpayment₹5,76,000₹6,22,000Ansal Golf City, Lucknow₹23,000off2016 Maruti Swift DzireLXI (O)Manual97,063 km1st OwnerPetrolUP-32₹5,865/month ₹75,000 downpayment₹3,75,000₹3,98,000Ansal Golf City, Lucknow₹52,000off2011 Hyundai i10ASTA 1.2Manual97,351 km1st OwnerPetrolUP-32₹3,065/month ₹39,200 downpayment₹1,96,000₹2,48,000Ansal Golf City, LucknowUsed cars in Lucknow by brandMarutiHyundaiHondaToyotaTataFordRenaultMahindraVolkswagenNissanSkodaKIADatsunAudiJeepMG₹37,000off2013 Maruti SwiftVDIManual1,17,343 km1st OwnerDieselUP-32₹4,551/month ₹58,200 downpayment₹2,91,000₹3,28,000Ansal Golf City, Lucknow2015 Hyundai Grand i10SPORTZ 1.1 CRDIManual1,13,638 km2nd OwnerDieselUP-32₹4,645/month ₹59,400 downpayment₹2,97,000Ansal Golf City, Lucknow₹1,17,000off2017 Hyundai Elite i20SPORTZ 1.2Manual64,362 km2nd OwnerPetrolUP-53₹7,382/month ₹94,400 downpayment₹4,72,000₹5,89,000Ansal Golf City, LucknowUsed cars in Lucknow by body typeHatchbackSUVSedanLuxury SUVLuxury Sedan₹15,000off2012 Hyundai i10ERA 1.1Manual37,947 km2nd OwnerPetrolUP-32₹3,065/month ₹39,200 downpayment₹1,96,000₹2,11,000Ansal Golf City, Lucknow₹38,000off2018 Tata TiagoXT PETROLManual38,017 km1st OwnerPetrolUP-32₹5,959/month ₹76,200 downpayment₹3,81,000₹4,19,000Ansal Golf City, Lucknow₹52,000off2017 Hyundai Verna1.6 VTVT SXManual45,853 km1st OwnerPetrolUP-32₹12,231/month ₹1,56,400 downpayment₹7,82,000₹8,34,000Ansal Golf City, LucknowUsed cars in Lucknow by fuel typePetrolDieselCNG2018 Hyundai Verna1.6 VTVT SXManual50,588 km2nd OwnerPetrolUP-78₹11,449/month ₹1,46,400 downpayment₹7,32,000Ansal Golf City, Lucknow₹1,06,000off2019 Maruti SwiftZXI PLUSManual65,772 km1st OwnerPetrolUP-40₹8,774/month ₹1,12,200 downpayment₹5,61,000₹6,67,000Ansal Golf City, Lucknow₹66,000off2014 Maruti CelerioVXI AMTAutomatic65,187 km1st OwnerPetrolUP-78₹4,160/month ₹53,200 downpayment₹2,66,000₹3,32,000Ansal Golf City, LucknowUsed cars in Lucknow by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhsunder 2 lakhs₹8,000off2014 Maruti Swift DzireVDIManual98,693 km1st OwnerDieselUP-32₹6,131/month ₹78,400 downpayment₹3,92,000₹4,00,000Ansal Golf City, Lucknow₹11,000off2020 Maruti S PRESSOVXIManual8,449 km1st OwnerPetrolUP-32₹6,819/month ₹87,200 downpayment₹4,36,000₹4,47,000Ansal Golf City, Lucknow₹82,000off2018 Maruti Wagon R 1.0VXIManual52,419 km1st OwnerPetrolUP-42₹5,505/month ₹70,400 downpayment₹3,52,000₹4,34,000Ansal Golf City, LucknowUsed cars in Lucknow by modelHyundai i10Maruti SwiftMaruti Wagon RMaruti DzireMaruti AltoHonda CityHyundai i20Maruti BrezzaFord EcosportMaruti IGNISMaruti BalenoTata TiagoHyundai CretaRenault KwidHonda AmazeMaruti CelerioHonda WR-VHyundai XcentMaruti S CrossMaruti S PRESSO₹82,000off2016 Maruti Vitara BrezzaZDI PLUSManual64,794 km1st OwnerDieselUP-14₹9,806/month ₹1,25,400 downpayment₹6,27,000₹7,09,000Ansal Golf City, Lucknow₹78,000off2020 Maruti New Wagon-RVXI 1.0Manual67,952 km1st OwnerPetrolUP-32₹7,054/month ₹90,200 downpayment₹4,51,000₹5,29,000Ansal Golf City, Lucknow₹18,000off2022 Maruti AltoLXI OManual3,890 km1st OwnerPetrolUP-32₹6,444/month ₹82,400 downpayment₹4,12,000₹4,30,000Ansal Golf City, LucknowHomeUsed CarsLucknow45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions LucknowWhat are the most popular brands available for 2nd hand cars in Lucknow?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Lucknow of your choice on CARS24.What body types are available for 2nd hand cars in Lucknow?Used cars in Lucknow are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Lucknow?Of Course yes, you can buy used cars online in Lucknow from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in LucknowWhat to check before buying a second hand car in Lucknow?Important things to check  before buying a second hand car in Lucknow are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Lucknow?You can buy used cars in Lucknow from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Lucknow?You can check second hand cars in Lucknow using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in LucknowHow many second hand cars are available in Lucknow?133 used cars are available in Lucknow of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in LucknowUsed Hyundai Cars in LucknowUsed Honda Cars in LucknowUsed Toyota Cars in LucknowUsed Tata Cars in LucknowUsed Ford Cars in LucknowUsed Renault Cars in LucknowUsed Mahindra Cars in LucknowUsed Volkswagen Cars in LucknowUsed Nissan Cars in LucknowUsed Skoda Cars in LucknowUsed KIA Cars in LucknowUsed Datsun Cars in LucknowUsed Audi Cars in LucknowUsed Jeep Cars in LucknowUsed MG Cars in LucknowBody :Used Hatchback Cars in LucknowUsed SUV Cars in LucknowUsed Sedan Cars in LucknowUsed Luxury SUV Cars in LucknowUsed Luxury Sedan Cars in LucknowFuel :Used Petrol Cars in LucknowUsed Diesel Cars in LucknowUsed CNG Cars in LucknowBudget :Used Cars between 5 to 10 lakhs in LucknowUsed Cars between 2 to 5 lakhs in LucknowUsed Cars above 10 lakhs in LucknowUsed Cars under 2 lakhs in LucknowModel :Used Hyundai i10 Cars in LucknowUsed Maruti Swift Cars in LucknowUsed Maruti Wagon R Cars in LucknowUsed Maruti Dzire Cars in LucknowUsed Maruti Alto Cars in LucknowUsed Honda City Cars in LucknowUsed Hyundai i20 Cars in LucknowUsed Maruti Brezza Cars in LucknowUsed Ford Ecosport Cars in LucknowUsed Maruti IGNIS Cars in LucknowUsed Maruti Baleno Cars in LucknowUsed Tata Tiago Cars in LucknowUsed Hyundai Creta Cars in LucknowUsed Renault Kwid Cars in LucknowUsed Honda Amaze Cars in LucknowUsed Maruti Celerio Cars in LucknowUsed Honda WR-V Cars in LucknowUsed Hyundai Xcent Cars in LucknowUsed Maruti S Cross Cars in LucknowUsed Maruti S PRESSO Cars in LucknowTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [83]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2015', '2019', '2019', '2016', '2011', '2013', '2015', '2017', '2012', '2018', '2017', '2018', '2019', '2014', '2014', '2020', '2018', '2016', '2020', '2022']
[[' Maruti', ' Swift', ' Dzire'], [' Hyundai', ' Creta'], [' Maruti', ' Swift'], [' Maruti', ' Swift', ' Dzire'], [' Hyundai', ' i10'], [' Maruti', ' Swift'], [' Hyundai', ' Grand', ' i10'], [' Hyundai', ' Elite', ' i20'], [' Hyundai', ' i10'], [' Tata', ' Tiago'], [' Hyundai', ' Verna'], [' Hyundai', ' Verna'], [' Maruti', ' Swift'], [' Maruti', ' Celerio'], [' Maruti', ' Swift', ' Dzire'], [' Maruti', ' S', ' PRESSO'], [' Maruti', ' Wagon', ' R', ' 1'], [' Maruti', ' Vitara', ' Brezza'], [' Maruti', ' New', ' Wagon'], [' Maruti', ' Alto']]
['Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow', 'Ansal Golf City, Lucknow']
[['94,408'], ['60,455'], ['67,829'], ['97,063'], ['97,351'], ['1,17', ',343'], ['1,13', ',638'], ['64,362'], ['37,947'], ['38,017'], ['45,853'], ['50,588'], ['65,772'], ['65,187'], ['98,693'], ['8,449'], ['52,419'], ['64,794'], ['67,952'], ['3,890']]
[['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol']]
[['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['452000', '1131000', '576000', '375000', '196000', '291000', '297000', '472000', '196000', '381000', '782000', '732000', '561000', '266000', '392000', '436000', '352000', '627000', '451000', '412000']

In [84]:
dicto12 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [85]:
kmt1 = []
dicto12["Kmt run"]
for i in dicto12["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto12n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto12n

{'Name of Cars': [[' Maruti', ' Swift', ' Dzire'],
  [' Hyundai', ' Creta'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Swift', ' Dzire'],
  [' Hyundai', ' i10'],
  [' Maruti', ' Swift'],
  [' Hyundai', ' Grand', ' i10'],
  [' Hyundai', ' Elite', ' i20'],
  [' Hyundai', ' i10'],
  [' Tata', ' Tiago'],
  [' Hyundai', ' Verna'],
  [' Hyundai', ' Verna'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Celerio'],
  [' Maruti', ' Swift', ' Dzire'],
  [' Maruti', ' S', ' PRESSO'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Maruti', ' Vitara', ' Brezza'],
  [' Maruti', ' New', ' Wagon'],
  [' Maruti', ' Alto']],
 'Registration Year': ['2015',
  '2019',
  '2019',
  '2016',
  '2011',
  '2013',
  '2015',
  '2017',
  '2012',
  '2018',
  '2017',
  '2018',
  '2019',
  '2014',
  '2014',
  '2020',
  '2018',
  '2016',
  '2020',
  '2022'],
 'Kmt run': [94408,
  60455,
  67829,
  97063,
  97351,
  117343,
  113638,
  64362,
  37947,
  38017,
  45853,
  50588,
  65772,
  65187,
  98693,
  8449,
  52419,
  64794,
  67952,
  3890],
 'Transmission': [['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['452000',
  '1131000',
  '576000',
  '375000',
  '196000',
  '291000',
  '297000',
  '472000',
  '196000',
  '381000',
  '782000',
  '732000',
  '561000',
  '266000',
  '392000',
  '436000',
  '352000',
  '627000',
  '451000',
  '412000'],
 'Location of car': ['Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow',
  'Ansal Golf City, Lucknow']}

In [86]:
url13 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=2378&pinId=400001"

In [87]:
new13 = req.get(url13)
new13

In [88]:
soup = BeautifulSoup(new13.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n632 Used Cars in Mumbai - Second Hand Cars for Sale\n\n MumbaiBuy a carPopular makesMarutiHyundaiHondaTataRenaultToyotaVolkswagenMahindraFordDatsunView all makesPopular ModelsMaruti Wagon RHyundai i20Honda CityHyundai i10Maruti BalenoMaruti DzireMaruti AltoMaruti CelerioHyundai CretaMaruti ErtigaView all modelsBody typeHatchbackSedanSUVLuxury SUVLuxury SedanFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsHonda City (62)Maruti Wagon R 1.0 (62)Maruti Baleno (50)Hyundai Elite i20 (43)Maruti Celerio (35)Hyundai Grand i10 (33)ALL BRANDSMaruti (355)Hyundai (213)Honda (110)Tata (64)Renault (32)Mahindra (24)Toyota (24)Volkswagen (23)Ford (19)Datsun (6)Skoda (5)Jeep (5)Nissan (4)KIA (2)MG (1)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Volvo (0)Jaguar (0)Budget₹ 1,00,000₹ 25,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear All632 Used cars in MumbaiSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New2013 Maruti Swift DzireVDIManual26,698 km1st OwnerDieselMH-05₹11,144/month ₹1,05,800 downpayment₹5,29,000Rupa Renaissance, Navi Mumbai₹1,19,000off2018 Hyundai Verna1.6 VTVT SX OManual61,662 km2nd OwnerPetrolMH-15₹11,761/month ₹1,50,400 downpayment₹7,52,000₹8,71,000Mulund\nNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹29,000off2015 Maruti Swift DzireVXIManual1,10,540 km1st OwnerPetrolMH-46₹7,385/month ₹83,000 downpayment₹4,15,000₹4,44,000Goregaon, Mumbai₹69,000off2020 Tata TiagoXZ PLUS PETROLManual45,638 km1st OwnerPetrolMH-47₹8,086/month ₹1,03,400 downpayment₹5,17,000₹5,86,000Rupa Renaissance, Navi Mumbai₹41,000off2015 Hyundai Grand i10MAGNA 1.2 KAPPA VTVTManual41,378 km1st OwnerPetrolMH-48₹5,630/month ₹72,000 downpayment₹3,60,000₹4,01,000Goregaon, MumbaiUsed cars in Mumbai by brandMarutiHyundaiHondaTataRenaultToyotaVolkswagenMahindraFordSkodaDatsunJeepNissanKIAMGBMWJaguarMercedes BenzFiat₹10,000off2014 Maruti Wagon R 1.0VXIManual78,118 km3rd OwnerCNGMH-02₹5,456/month ₹51,800 downpayment₹2,59,000₹2,69,000Rupa Renaissance, Navi Mumbai₹15,000off2013 Hyundai VernaFLUIDIC 1.6 EX CRDI ATAutomatic87,172 km3rd OwnerDieselMH-48₹8,300/month ₹78,800 downpayment₹3,94,000₹4,09,000Goregaon, Mumbai₹7,000off2017 Tata TiagoXZ PETROLManual48,059 km2nd OwnerPetrolMH-02₹5,677/month ₹72,600 downpayment₹3,63,000₹3,70,000Mulund\nUsed cars in Mumbai by body typeHatchbackSedanSUVLuxury SUVLuxury Sedan₹13,000off2012 Maruti Zen EstiloLXI CNGManual69,120 km2nd OwnerCNGMH-02₹6,967/month ₹37,000 downpayment₹1,85,000₹1,98,000Mulund\n₹14,000off2016 Maruti CelerioZXIManual85,307 km3rd OwnerPetrolMH-03₹4,692/month ₹60,000 downpayment₹3,00,000₹3,14,000Mulund\n₹15,000off2010 Maruti Alto K10VXIManual59,489 km2nd OwnerPetrolMH-04₹5,498/month ₹29,200 downpayment₹1,46,000₹1,61,000Rupa Renaissance, Navi MumbaiUsed cars in Mumbai by fuel typePetrolDieselCNG₹41,200off2019 Hyundai VENUESX PLUS 1.0 TURBO DCTAutomatic40,462 km1st OwnerPetrolMH-47₹15,239/month ₹2,00,160 downpayment₹10,00,800₹10,42,000Mulund\n₹47,000off2014 Maruti SwiftVXIManual32,135 km1st OwnerPetrolMH-05₹5,787/month ₹74,000 downpayment₹3,70,000₹4,17,000Mulund\n₹13,000off2012 Maruti Alto 800LXIManual27,275 km2nd OwnerPetrolMH-06₹3,897/month ₹37,000 downpayment₹1,85,000₹1,98,000Mulund\nUsed cars in Mumbai by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhsunder 2 lakhs₹60,000off2017 Maruti DzireZDI PLUSManual78,569 km1st OwnerDieselMH-48₹9,994/month ₹1,27,800 downpayment₹6,39,000₹6,99,000Rupa Renaissance, Navi Mumbai2020 Maruti CiazALPHA  AT 1.5 SHVS PETROLAutomatic10,096 km2nd OwnerPetrolMH-05₹15,364/month ₹2,01,800 downpayment₹10,09,000Rupa Renaissance, Navi Mumbai₹12,000off2014 Maruti Wagon R 1.0LXI CNGManual76,560 km3rd OwnerCNGMH-46₹6,088/month ₹57,800 downpayment₹2,89,000₹3,01,000Rupa Renaissance, Navi MumbaiUsed cars in Mumbai by modelMaruti Wagon RHyundai i20Honda CityHyundai i10Maruti BalenoMaruti DzireMaruti AltoMaruti CelerioHyundai CretaMaruti ErtigaMaruti SwiftMaruti CiazHyundai VernaTata NEXONTata TiagoRenault KwidHonda AmazeVolkswagen PoloFord EcosportHonda Jazz₹70,000off2019 Tata NEXONXM PETROLManual28,058 km3rd OwnerCNGMH-01₹9,666/month ₹1,23,600 downpayment₹6,18,000₹6,88,000Mulund\n₹33,000off2015 Hyundai Elite i20SPORTZ 1.2Manual50,117 km1st OwnerPetrolMH-47₹7,210/month ₹92,200 downpayment₹4,61,000₹4,94,000Rupa Renaissance, Navi Mumbai₹83,500off2021 Tata ALTROZXM PLUS PETROLManual10,199 km1st OwnerPetrolMH-46₹9,611/month ₹1,22,900 downpayment₹6,14,500₹6,98,000Mulund\nHomeUsed CarsMumbai45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions MumbaiWhat are the most popular brands available for 2nd hand cars in Mumbai?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Mumbai of your choice on CARS24.What body types are available for 2nd hand cars in Mumbai?Used cars in Mumbai are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Mumbai?Of Course yes, you can buy used cars online in Mumbai from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in MumbaiWhat to check before buying a second hand car in Mumbai?Important things to check  before buying a second hand car in Mumbai are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Mumbai?You can buy used cars in Mumbai from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Mumbai?You can check second hand cars in Mumbai using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in MumbaiHow many second hand cars are available in Mumbai?632 used cars are available in Mumbai of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in MumbaiUsed Hyundai Cars in MumbaiUsed Honda Cars in MumbaiUsed Tata Cars in MumbaiUsed Renault Cars in MumbaiUsed Toyota Cars in MumbaiUsed Volkswagen Cars in MumbaiUsed Mahindra Cars in MumbaiUsed Ford Cars in MumbaiUsed Skoda Cars in MumbaiUsed Datsun Cars in MumbaiUsed Jeep Cars in MumbaiUsed Nissan Cars in MumbaiUsed KIA Cars in MumbaiUsed MG Cars in MumbaiUsed BMW Cars in MumbaiUsed Jaguar Cars in MumbaiUsed Mercedes Benz Cars in MumbaiUsed Fiat Cars in MumbaiBody :Used Hatchback Cars in MumbaiUsed Sedan Cars in MumbaiUsed SUV Cars in MumbaiUsed Luxury SUV Cars in MumbaiUsed Luxury Sedan Cars in MumbaiFuel :Used Petrol Cars in MumbaiUsed Diesel Cars in MumbaiUsed CNG Cars in MumbaiBudget :Used Cars between 5 to 10 lakhs in MumbaiUsed Cars between 2 to 5 lakhs in MumbaiUsed Cars above 10 lakhs in MumbaiUsed Cars under 2 lakhs in MumbaiModel :Used Maruti Wagon R Cars in MumbaiUsed Hyundai i20 Cars in MumbaiUsed Honda City Cars in MumbaiUsed Hyundai i10 Cars in MumbaiUsed Maruti Baleno Cars in MumbaiUsed Maruti Dzire Cars in MumbaiUsed Maruti Alto Cars in MumbaiUsed Maruti Celerio Cars in MumbaiUsed Hyundai Creta Cars in MumbaiUsed Maruti Ertiga Cars in MumbaiUsed Maruti Swift Cars in MumbaiUsed Maruti Ciaz Cars in MumbaiUsed Hyundai Verna Cars in MumbaiUsed Tata NEXON Cars in MumbaiUsed Tata Tiago Cars in MumbaiUsed Renault Kwid Cars in MumbaiUsed Honda Amaze Cars in MumbaiUsed Volkswagen Polo Cars in MumbaiUsed Ford Ecosport Cars in MumbaiUsed Honda Jazz Cars in MumbaiTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [89]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2013', '2018', '2015', '2020', '2015', '2014', '2013', '2017', '2012', '2016', '2010', '2019', '2014', '2012', '2017', '2020', '2014', '2019', '2015', '2021']
[[' Maruti', ' Swift', ' Dzire'], [' Hyundai', ' Verna'], [' Maruti', ' Swift', ' Dzire'], [' Tata', ' Tiago'], [' Hyundai', ' Grand', ' i10'], [' Maruti', ' Wagon', ' R', ' 1'], [' Hyundai', ' Verna'], [' Tata', ' Tiago'], [' Maruti', ' Zen', ' Estilo'], [' Maruti', ' Celerio'], [' Maruti', ' Alto', ' K10'], [' Hyundai', ' VENUE'], [' Maruti', ' Swift'], [' Maruti', ' Alto', ' 800'], [' Maruti', ' Dzire'], [' Maruti', ' Ciaz'], [' Maruti', ' Wagon', ' R', ' 1'], [' Tata', ' NEXON'], [' Hyundai', ' Elite', ' i20'], [' Tata', ' ALTROZ']]
['Rupa Renaissance, Navi Mumbai', 'Mulund\n', 'Goregaon, Mumbai', 'Rupa Renaissance, Navi Mumbai', 'Goregaon, Mumbai', 'Rupa Renaissance, Navi Mumbai', 'Goregaon, Mumbai', 'Mulund\n', 'Mulund\n', 'Mulund\n', 'Rupa Renaissance, Navi Mumbai', 'Mulund\n', 'Mulund\n', 'Mulund\n', 'Rupa Renaissance, Navi Mumbai', 'Rupa Renaissance, Navi Mumbai', 'Rupa Renaissance, Navi Mumbai', 'Mulund\n', 'Rupa Renaissance, Navi Mumbai', 'Mulund\n']
[['26,698'], ['61,662'], ['1,10', ',540'], ['45,638'], ['41,378'], ['78,118'], ['87,172'], ['48,059'], ['69,120'], ['85,307'], ['59,489'], ['40,462'], ['32,135'], ['27,275'], ['78,569'], ['10,096'], ['76,560'], ['28,058'], ['50,117'], ['10,199']]
[['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], nan, ['Diesel'], ['Petrol'], nan, ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], nan, nan, ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['529000', '752000', '415000', '517000', '360000', '259000', '394000', '363000', '185000', '300000', '146000', '1000800', '370000', '185000', '639000', '1009000', '289000', '618000', '461000', '614500']

In [90]:
dicto13 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [91]:
kmt1 = []
dicto13["Kmt run"]
for i in dicto13["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto13n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto13n

{'Name of Cars': [[' Maruti', ' Swift', ' Dzire'],
  [' Hyundai', ' Verna'],
  [' Maruti', ' Swift', ' Dzire'],
  [' Tata', ' Tiago'],
  [' Hyundai', ' Grand', ' i10'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Hyundai', ' Verna'],
  [' Tata', ' Tiago'],
  [' Maruti', ' Zen', ' Estilo'],
  [' Maruti', ' Celerio'],
  [' Maruti', ' Alto', ' K10'],
  [' Hyundai', ' VENUE'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Alto', ' 800'],
  [' Maruti', ' Dzire'],
  [' Maruti', ' Ciaz'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Tata', ' NEXON'],
  [' Hyundai', ' Elite', ' i20'],
  [' Tata', ' ALTROZ']],
 'Registration Year': ['2013',
  '2018',
  '2015',
  '2020',
  '2015',
  '2014',
  '2013',
  '2017',
  '2012',
  '2016',
  '2010',
  '2019',
  '2014',
  '2012',
  '2017',
  '2020',
  '2014',
  '2019',
  '2015',
  '2021'],
 'Kmt run': [26698,
  61662,
  110540,
  45638,
  41378,
  78118,
  87172,
  48059,
  69120,
  85307,
  59489,
  40462,
  32135,
  27275,
  78569,
  10096,
  76560,
  28058,
  50117,
  10199],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  nan,
  ['Diesel'],
  ['Petrol'],
  nan,
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  nan,
  nan,
  ['Petrol'],
  ['Petrol']],
 'Price': ['529000',
  '752000',
  '415000',
  '517000',
  '360000',
  '259000',
  '394000',
  '363000',
  '185000',
  '300000',
  '146000',
  '1000800',
  '370000',
  '185000',
  '639000',
  '1009000',
  '289000',
  '618000',
  '461000',
  '614500'],
 'Location of car': ['Rupa Renaissance, Navi Mumbai',
  'Mulund\n',
  'Goregaon, Mumbai',
  'Rupa Renaissance, Navi Mumbai',
  'Goregaon, Mumbai',
  'Rupa Renaissance, Navi Mumbai',
  'Goregaon, Mumbai',
  'Mulund\n',
  'Mulund\n',
  'Mulund\n',
  'Rupa Renaissance, Navi Mumbai',
  'Mulund\n',
  'Mulund\n',
  'Mulund\n',
  'Rupa Renaissance, Navi Mumbai',
  'Rupa Renaissance, Navi Mumbai',
  'Rupa Renaissance, Navi Mumbai',
  'Mulund\n',
  'Rupa Renaissance, Navi Mumbai',
  'Mulund\n']}

In [92]:
url14 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata%3AOR%3Amake%3A%3D%3Ahonda%3AOR%3Amake%3A%3D%3Arenault%3AOR%3Amake%3A%3D%3Atoyota%3AOR%3Amake%3A%3D%3Aford%3AOR%3Amake%3A%3D%3Amahindra%3AOR%3Amake%3A%3D%3Avolkswagen%3AOR%3Amake%3A%3D%3Adatsun%3AOR%3Amake%3A%3D%3Akia%3AOR%3Amake%3A%3D%3Anissan%3AOR%3Amake%3A%3D%3Ajeep%3AOR%3Amake%3A%3D%3Askoda&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&listingSource=TabFilter&storeCityId=134&pinId=201301"

In [93]:
new14 = req.get(url14)
new14

In [94]:
soup = BeautifulSoup(new14.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n1953 Used Cars in Noida - Second Hand Cars for Sale\n\n NoidaBuy a carPopular makesMarutiHyundaiHondaTataToyotaRenaultVolkswagenDatsunFordMahindraView all makesPopular ModelsHyundai i10Maruti SwiftMaruti BalenoHyundai i20Honda CityMaruti AltoHonda AmazeMaruti DzireMaruti Wagon RMaruti CiazView all modelsBody typeHatchbackSedanSUVLuxury SUVLuxury SedanFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Baleno (161)Maruti Swift (125)Honda City (108)Honda Amaze (89)Maruti Wagon R 1.0 (76)Hyundai Grand i10 (65)ALL BRANDSMaruti (817)Hyundai (423)Honda (266)Tata (99)Renault (72)Toyota (62)Mahindra (43)Ford (41)Volkswagen (32)Datsun (28)KIA (25)Nissan (19)Jeep (16)Skoda (10)MG (5)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Volvo (0)Jaguar (0)Budget₹ 1,00,000₹ 30,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear AllShow More 1953 Used cars in NoidaSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹34,000off2020 Hyundai AURAS 1.2 CNGManual67,853 km2nd OwnerCNGUP-13₹10,448/month ₹1,33,600 downpayment₹6,68,000₹7,02,000Sector-18, Noida₹19,000off2019 Maruti Vitara BrezzaVDIManual55,523 km1st OwnerDieselHR-30₹12,182/month ₹1,60,000 downpayment₹8,00,000₹8,19,000M3M Urbana, Golf Course Ext., GurugramNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹41,000off2015 Maruti SwiftVDI ABSManual1,17,499 km1st OwnerDieselHR-30₹5,881/month ₹75,200 downpayment₹3,76,000₹4,17,000Spaze Platinum, Sohna Road, Gurugram₹23,000off2018 Maruti SwiftVXIManual91,534 km2nd OwnerPetrolHR-50₹8,039/month ₹1,02,800 downpayment₹5,14,000₹5,37,000M3M Urbana, Golf Course Ext., Gurugram₹37,000off2019 Maruti Vitara BrezzaVDIManual50,767 km1st OwnerDieselHR-29₹12,231/month ₹1,56,400 downpayment₹7,82,000₹8,19,000M3M Urbana, Golf Course Ext., GurugramUsed cars in Noida by brandMarutiHyundaiHondaToyotaTataRenaultDatsunVolkswagenFordMahindraKIANissanJeepSkodaMGAudi2015 Maruti Alto 800LXIManual35,843 km3rd OwnerPetrolHR-29₹3,660/month ₹46,800 downpayment₹2,34,000Spaze Platinum, Sohna Road, Gurugram₹72,000off2019 Maruti BalenoDELTA PETROL 1.2Manual97,494 km1st OwnerPetrolHR-30₹7,210/month ₹92,200 downpayment₹4,61,000₹5,33,000Spaze Platinum, Sohna Road, Gurugram₹33,000off2019 Honda Amaze1.2L I-VTEC SManual43,184 km1st OwnerCNGHR-30₹9,947/month ₹1,27,200 downpayment₹6,36,000₹6,69,000Chhatarpur, Delhi\nUsed cars in Noida by body typeHatchbackSedanSUVLuxury SUVLuxury Sedan₹34,000off2019 Maruti New Wagon-RLXI CNG 1.0Manual48,404 km1st OwnerCNGHR-29₹7,210/month ₹92,200 downpayment₹4,61,000₹4,95,000Metro Walk, Rohini, New Delhi2014 Maruti Wagon R 1.0VXIManual97,752 km1st OwnerPetrolHR-30₹4,583/month ₹58,600 downpayment₹2,93,000Spaze Platinum, Sohna Road, Gurugram₹1,02,000off2019 Toyota GlanzaV CVTAutomatic37,778 km1st OwnerPetrolHR-87₹12,152/month ₹1,55,400 downpayment₹7,77,000₹8,79,000Parsvnath City Mall, FaridabadUsed cars in Noida by fuel typePetrolDieselCNG₹31,000off2014 Maruti Wagon R 1.0VXIManual79,204 km2nd OwnerPetrolHR-30₹3,894/month ₹49,800 downpayment₹2,49,000₹2,80,000Spaze Platinum, Sohna Road, Gurugram₹45,000off2018 Maruti Vitara BrezzaVDIManual30,549 km1st OwnerDieselHR-30₹10,995/month ₹1,40,600 downpayment₹7,03,000₹7,48,000Parsvnath City Mall, Faridabad₹5,000off2010 Maruti Wagon R 1.0VXIManual61,569 km2nd OwnerPetrolHR-50₹2,831/month ₹36,200 downpayment₹1,81,000₹1,86,000Chhatarpur, Delhi\nUsed cars in Noida by budgetbetween 2 to 5 lakhsbetween 5 to 10 lakhsabove 10 lakhsunder 2 lakhs₹23,000off2019 Honda Amaze1.2L I-VTEC SManual37,783 km1st OwnerPetrolHR-30₹9,916/month ₹1,26,800 downpayment₹6,34,000₹6,57,000M3M Urbana, Golf Course Ext., Gurugram2019 Maruti AltoLXIManual18,475 km1st OwnerPetrolHR-29₹5,318/month ₹68,000 downpayment₹3,40,000GIP Mall, Noida₹32,000off2018 Ford EcosportTITANIUM 1.5L DIESELManual79,371 km1st OwnerDieselHR-30₹9,838/month ₹1,25,800 downpayment₹6,29,000₹6,61,000Metro Walk, Rohini, New DelhiUsed cars in Noida by modelHyundai i10Maruti SwiftMaruti BalenoHyundai i20Maruti AltoHonda CityHonda AmazeMaruti DzireMaruti Wagon RMaruti CiazMaruti CelerioHyundai CretaHyundai VernaHonda WR-VRenault KwidFord EcosportDatsun Redi GoVolkswagen VentoTata NEXONHyundai Santro₹15,000off2020 Maruti SwiftLXIManual44,817 km2nd OwnerPetrolHR-36₹8,227/month ₹1,05,200 downpayment₹5,26,000₹5,41,000Metro Walk, Rohini, New Delhi₹1,53,000off2021 Renault KigerRXZ MT DUAL TONEManual45,459 km1st OwnerPetrolHR-76₹10,620/month ₹1,35,800 downpayment₹6,79,000₹8,32,000Metro Walk, Rohini, New Delhi₹22,000off2014 Maruti Alto K10VXIManual47,899 km1st OwnerPetrolHR-36₹3,801/month ₹48,600 downpayment₹2,43,000₹2,65,000Spaze Platinum, Sohna Road, GurugramHomeUsed CarsNoida45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions NoidaWhat are the most popular brands available for 2nd hand cars in Noida?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Noida of your choice on CARS24.What body types are available for 2nd hand cars in Noida?Used cars in Noida are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Noida?Of Course yes, you can buy used cars online in Noida from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in NoidaWhat to check before buying a second hand car in Noida?Important things to check  before buying a second hand car in Noida are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Noida?You can buy used cars in Noida from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Noida?You can check second hand cars in Noida using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in NoidaHow many second hand cars are available in Noida?1953 used cars are available in Noida of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in NoidaUsed Hyundai Cars in NoidaUsed Honda Cars in NoidaUsed Toyota Cars in NoidaUsed Tata Cars in NoidaUsed Renault Cars in NoidaUsed Datsun Cars in NoidaUsed Volkswagen Cars in NoidaUsed Ford Cars in NoidaUsed Mahindra Cars in NoidaUsed KIA Cars in NoidaUsed Nissan Cars in NoidaUsed Jeep Cars in NoidaUsed Skoda Cars in NoidaUsed MG Cars in NoidaUsed Audi Cars in NoidaBody :Used Hatchback Cars in NoidaUsed Sedan Cars in NoidaUsed SUV Cars in NoidaUsed Luxury SUV Cars in NoidaUsed Luxury Sedan Cars in NoidaFuel :Used Petrol Cars in NoidaUsed Diesel Cars in NoidaUsed CNG Cars in NoidaBudget :Used Cars between 2 to 5 lakhs in NoidaUsed Cars between 5 to 10 lakhs in NoidaUsed Cars above 10 lakhs in NoidaUsed Cars under 2 lakhs in NoidaModel :Used Hyundai i10 Cars in NoidaUsed Maruti Swift Cars in NoidaUsed Maruti Baleno Cars in NoidaUsed Hyundai i20 Cars in NoidaUsed Maruti Alto Cars in NoidaUsed Honda City Cars in NoidaUsed Honda Amaze Cars in NoidaUsed Maruti Dzire Cars in NoidaUsed Maruti Wagon R Cars in NoidaUsed Maruti Ciaz Cars in NoidaUsed Maruti Celerio Cars in NoidaUsed Hyundai Creta Cars in NoidaUsed Hyundai Verna Cars in NoidaUsed Honda WR-V Cars in NoidaUsed Renault Kwid Cars in NoidaUsed Ford Ecosport Cars in NoidaUsed Datsun Redi Go Cars in NoidaUsed Volkswagen Vento Cars in NoidaUsed Tata NEXON Cars in NoidaUsed Hyundai Santro Cars in NoidaTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n"

In [95]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2020', '2019', '2015', '2018', '2019', '2015', '2019', '2019', '2019', '2014', '2019', '2014', '2018', '2010', '2019', '2019', '2018', '2020', '2021', '2014']
[[' Hyundai', ' AURA'], [' Maruti', ' Vitara', ' Brezza'], [' Maruti', ' Swift'], [' Maruti', ' Swift'], [' Maruti', ' Vitara', ' Brezza'], [' Maruti', ' Alto', ' 800'], [' Maruti', ' Baleno'], [' Honda', ' Amaze'], [' Maruti', ' New', ' Wagon'], [' Maruti', ' Wagon', ' R', ' 1'], [' Toyota', ' Glanza'], [' Maruti', ' Wagon', ' R', ' 1'], [' Maruti', ' Vitara', ' Brezza'], [' Maruti', ' Wagon', ' R', ' 1'], [' Honda', ' Amaze'], [' Maruti', ' Alto'], [' Ford', ' Ecosport'], [' Maruti', ' Swift'], [' Renault', ' Kiger'], [' Maruti', ' Alto', ' K10']]
['Sector-18, Noida', 'M3M Urbana, Golf Course Ext., Gurugram', 'Spaze Platinum, Sohna Road, Gurugram', 'M3M Urbana, Golf Course Ext., Gurugram', 'M3M Urbana, Golf Course Ext., Gurugram', 'Spaze Platinum, Sohna Road, Gurugram', 'Spaze Platinum, Sohna Road, Gurugram', 'Chhatarpur, Delhi\n', 'Metro Walk, Rohini, New Delhi', 'Spaze Platinum, Sohna Road, Gurugram', 'Parsvnath City Mall, Faridabad', 'Spaze Platinum, Sohna Road, Gurugram', 'Parsvnath City Mall, Faridabad', 'Chhatarpur, Delhi\n', 'M3M Urbana, Golf Course Ext., Gurugram', 'GIP Mall, Noida', 'Metro Walk, Rohini, New Delhi', 'Metro Walk, Rohini, New Delhi', 'Metro Walk, Rohini, New Delhi', 'Spaze Platinum, Sohna Road, Gurugram']
[['67,853'], ['55,523'], ['1,17', ',499'], ['91,534'], ['50,767'], ['35,843'], ['97,494'], ['43,184'], ['48,404'], ['97,752'], ['37,778'], ['79,204'], ['30,549'], ['61,569'], ['37,783'], ['18,475'], ['79,371'], ['44,817'], ['45,459'], ['47,899']]
[nan, ['Diesel'], ['Diesel'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], nan, nan, ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['668000', '800000', '376000', '514000', '782000', '234000', '461000', '636000', '461000', '293000', '777000', '249000', '703000', '181000', '634000', '340000', '629000', '526000', '679000', '243000']

In [96]:
dicto14 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [97]:
kmt1 = []
dicto14["Kmt run"]
for i in dicto14["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto14n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto14n

{'Name of Cars': [[' Hyundai', ' AURA'],
  [' Maruti', ' Vitara', ' Brezza'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Vitara', ' Brezza'],
  [' Maruti', ' Alto', ' 800'],
  [' Maruti', ' Baleno'],
  [' Honda', ' Amaze'],
  [' Maruti', ' New', ' Wagon'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Toyota', ' Glanza'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Maruti', ' Vitara', ' Brezza'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Honda', ' Amaze'],
  [' Maruti', ' Alto'],
  [' Ford', ' Ecosport'],
  [' Maruti', ' Swift'],
  [' Renault', ' Kiger'],
  [' Maruti', ' Alto', ' K10']],
 'Registration Year': ['2020',
  '2019',
  '2015',
  '2018',
  '2019',
  '2015',
  '2019',
  '2019',
  '2019',
  '2014',
  '2019',
  '2014',
  '2018',
  '2010',
  '2019',
  '2019',
  '2018',
  '2020',
  '2021',
  '2014'],
 'Kmt run': [67853,
  55523,
  117499,
  91534,
  50767,
  35843,
  97494,
  43184,
  48404,
  97752,
  37778,
  79204,
  30549,
  61569,
  37783,
  18475,
  79371,
  44817,
  45459,
  47899],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [nan,
  ['Diesel'],
  ['Diesel'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  nan,
  nan,
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['668000',
  '800000',
  '376000',
  '514000',
  '782000',
  '234000',
  '461000',
  '636000',
  '461000',
  '293000',
  '777000',
  '249000',
  '703000',
  '181000',
  '634000',
  '340000',
  '629000',
  '526000',
  '679000',
  '243000'],
 'Location of car': ['Sector-18, Noida',
  'M3M Urbana, Golf Course Ext., Gurugram',
  'Spaze Platinum, Sohna Road, Gurugram',
  'M3M Urbana, Golf Course Ext., Gurugram',
  'M3M Urbana, Golf Course Ext., Gurugram',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Chhatarpur, Delhi\n',
  'Metro Walk, Rohini, New Delhi',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Parsvnath City Mall, Faridabad',
  'Spaze Platinum, Sohna Road, Gurugram',
  'Parsvnath City Mall, Faridabad',
  'Chhatarpur, Delhi\n',
  'M3M Urbana, Golf Course Ext., Gurugram',
  'GIP Mall, Noida',
  'Metro Walk, Rohini, New Delhi',
  'Metro Walk, Rohini, New Delhi',
  'Metro Walk, Rohini, New Delhi',
  'Spaze Platinum, Sohna Road, Gurugram']}

In [98]:
url15 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata%3AOR%3Amake%3A%3D%3Ahonda%3AOR%3Amake%3A%3D%3Arenault%3AOR%3Amake%3A%3D%3Atoyota%3AOR%3Amake%3A%3D%3Aford%3AOR%3Amake%3A%3D%3Amahindra%3AOR%3Amake%3A%3D%3Avolkswagen%3AOR%3Amake%3A%3D%3Adatsun%3AOR%3Amake%3A%3D%3Akia%3AOR%3Amake%3A%3D%3Anissan%3AOR%3Amake%3A%3D%3Ajeep%3AOR%3Amake%3A%3D%3Askoda&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=2423&pinId=411001"

In [99]:
new15 = req.get(url15)
new15

In [100]:
soup = BeautifulSoup(new15.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n704 Used Cars in Pune - Second Hand Cars for Sale\n\n PuneBuy a carPopular makesMarutiHyundaiHondaTataRenaultFordVolkswagenMahindraSkodaKIAView all makesPopular ModelsHyundai i10Maruti Wagon RMaruti SwiftMaruti BalenoMaruti AltoHonda CityHyundai i20Maruti CelerioMaruti DzireMaruti CiazView all modelsBody typeHatchbackSedanSUVLuxury SUVLuxury SedanFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Swift (39)Maruti Baleno (39)Honda City (32)Maruti Wagon R 1.0 (32)Hyundai Grand i10 (30)Maruti Celerio (28)ALL BRANDSMaruti (281)Hyundai (165)Honda (87)Tata (47)Renault (34)Volkswagen (18)Ford (17)Mahindra (16)Skoda (10)KIA (9)Toyota (7)Jeep (6)Nissan (4)Datsun (3)MG (2)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Volvo (0)Jaguar (0)Budget₹ 1,50,000₹ 25,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear AllShow More 704 Used cars in PuneSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New2011 Hyundai i10MAGNA 1.2Manual65,515 km1st OwnerPetrolMH-12₹7,945/month ₹59,800 downpayment₹2,99,000Undri, Pune₹20,000off2014 Hyundai EonMAGNA +Manual29,202 km2nd OwnerPetrolMH-04₹3,456/month ₹44,200 downpayment₹2,21,000₹2,41,000Tathawade, PuneNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility 2017 Honda WR-V1.2L I-VTEC VX MTManual79,548 km1st OwnerPetrolMH-14₹10,479/month ₹1,34,000 downpayment₹6,70,000Undri, Pune₹70,000off2020 KIA SELTOSHTK PLUS 1.5Manual34,513 km2nd OwnerPetrolMH-12₹14,816/month ₹1,94,600 downpayment₹9,73,000₹10,43,000Tathawade, Pune2016 Volkswagen PoloTRENDLINE 1.2L PETROLManual67,471 km2nd OwnerPetrolMH-12₹6,929/month ₹88,600 downpayment₹4,43,000Undri, PuneUsed cars in Pune by brandMarutiHyundaiHondaTataRenaultFordVolkswagenMahindraSkodaKIAToyotaJeepNissanDatsunMGMercedes Benz₹7,000off2016 Renault KwidRXT 1.0Manual58,103 km2nd OwnerPetrolMH-20₹4,364/month ₹55,800 downpayment₹2,79,000₹2,86,000Tathawade, Pune₹95,000off2014 Maruti ErtigaVXI CNGManual58,042 km2nd OwnerCNGMH-01₹12,619/month ₹1,19,800 downpayment₹5,99,000₹6,94,000Tathawade, Pune2014 Maruti Eeco7 STRManual47,079 km1st OwnerPetrolMH-14₹6,256/month ₹80,000 downpayment₹4,00,000Undri, PuneUsed cars in Pune by body typeHatchbackSedanSUVLuxury SUVLuxury Sedan₹26,000off2012 Maruti Alto 800LXIManual63,748 km2nd OwnerPetrolMH-48₹3,813/month ₹36,200 downpayment₹1,81,000₹2,07,000Undri, Pune₹30,000off2017 Mahindra XUV500W6Manual90,963 km2nd OwnerDieselMH-04₹12,324/month ₹1,57,600 downpayment₹7,88,000₹8,18,000Tathawade, Pune2019 Hyundai Grand i10SPORTZ 1.2 KAPPA VTVTManual40,352 km1st OwnerPetrolMH-06₹9,071/month ₹1,16,000 downpayment₹5,80,000Undri, PuneUsed cars in Pune by fuel typePetrolDieselCNG₹38,000off2011 Hyundai i10ERA 1.1Manual48,863 km1st OwnerPetrolMH-20₹5,447/month ₹41,000 downpayment₹2,05,000₹2,43,000Tathawade, Pune₹66,000off2014 Honda CRV2.4L 2WD ATAutomatic84,498 km2nd OwnerPetrolMH-12₹11,073/month ₹1,41,600 downpayment₹7,08,000₹7,74,000Tathawade, Pune₹95,000off2021 Nissan MAGNITEXV MTManual42,454 km1st OwnerPetrolMH-20₹10,651/month ₹1,36,200 downpayment₹6,81,000₹7,76,000Undri, PuneUsed cars in Pune by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhsunder 2 lakhs₹41,000off2010 Maruti Wagon R 1.0LXIManual36,113 km1st OwnerPetrolMH-02₹7,532/month ₹40,000 downpayment₹2,00,000₹2,41,000Undri, Pune₹90,000off2017 Tata TiagoWIZZ EDITION PETROLManual61,157 km1st OwnerPetrolMH-12₹6,287/month ₹80,400 downpayment₹4,02,000₹4,92,000Tathawade, Pune₹37,000off2017 Maruti DzireVXIManual40,277 km2nd OwnerPetrolMH-12₹10,041/month ₹1,28,400 downpayment₹6,42,000₹6,79,000Undri, PuneUsed cars in Pune by modelHyundai i10Maruti Wagon RMaruti BalenoMaruti SwiftMaruti AltoHonda CityHyundai i20Maruti CelerioMaruti DzireMaruti CiazHonda AmazeHyundai CretaRenault KwidHyundai SantroTata TiagoHyundai VernaMaruti ErtigaHonda WR-VTata NEXONFord Ecosport₹16,000off2011 Hyundai EonERAManual66,145 km3rd OwnerPetrolMH-12₹4,809/month ₹36,200 downpayment₹1,81,000₹1,97,000Tathawade, Pune₹83,000off2017 Hyundai Elite i20ASTA 1.2 (O)Manual1,14,848 km1st OwnerPetrolMH-40₹9,610/month ₹1,08,000 downpayment₹5,40,000₹6,23,000Undri, Pune₹41,000off2016 Maruti Alto K10VXIManual42,591 km3rd OwnerPetrolMH-14₹4,285/month ₹54,800 downpayment₹2,74,000₹3,15,000Undri, PuneHomeUsed CarsPune45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions PuneWhat are the most popular brands available for 2nd hand cars in Pune?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Pune of your choice on CARS24.What body types are available for 2nd hand cars in Pune?Used cars in Pune are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Pune?Of Course yes, you can buy used cars online in Pune from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in PuneWhat to check before buying a second hand car in Pune?Important things to check  before buying a second hand car in Pune are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Pune?You can buy used cars in Pune from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Pune?You can check second hand cars in Pune using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in PuneHow many second hand cars are available in Pune?704 used cars are available in Pune of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in PuneUsed Hyundai Cars in PuneUsed Honda Cars in PuneUsed Tata Cars in PuneUsed Renault Cars in PuneUsed Ford Cars in PuneUsed Volkswagen Cars in PuneUsed Mahindra Cars in PuneUsed Skoda Cars in PuneUsed KIA Cars in PuneUsed Toyota Cars in PuneUsed Jeep Cars in PuneUsed Nissan Cars in PuneUsed Datsun Cars in PuneUsed MG Cars in PuneUsed Mercedes Benz Cars in PuneBody :Used Hatchback Cars in PuneUsed Sedan Cars in PuneUsed SUV Cars in PuneUsed Luxury SUV Cars in PuneUsed Luxury Sedan Cars in PuneFuel :Used Petrol Cars in PuneUsed Diesel Cars in PuneUsed CNG Cars in PuneBudget :Used Cars between 5 to 10 lakhs in PuneUsed Cars between 2 to 5 lakhs in PuneUsed Cars above 10 lakhs in PuneUsed Cars under 2 lakhs in PuneModel :Used Hyundai i10 Cars in PuneUsed Maruti Wagon R Cars in PuneUsed Maruti Baleno Cars in PuneUsed Maruti Swift Cars in PuneUsed Maruti Alto Cars in PuneUsed Honda City Cars in PuneUsed Hyundai i20 Cars in PuneUsed Maruti Celerio Cars in PuneUsed Maruti Dzire Cars in PuneUsed Maruti Ciaz Cars in PuneUsed Honda Amaze Cars in PuneUsed Hyundai Creta Cars in PuneUsed Renault Kwid Cars in PuneUsed Hyundai Santro Cars in PuneUsed Tata Tiago Cars in PuneUsed Hyundai Verna Cars in PuneUsed Maruti Ertiga Cars in PuneUsed Honda WR-V Cars in PuneUsed Tata NEXON Cars in PuneUsed Ford Ecosport Cars in PuneTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [101]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2011', '2014', '2017', '2020', '2016', '2016', '2014', '2014', '2012', '2017', '2019', '2011', '2014', '2021', '2010', '2017', '2017', '2011', '2017', '2016']
[[' Hyundai', ' i10'], [' Hyundai', ' Eon'], [' Honda', ' WR'], [' KIA', ' SELTOS'], [' Volkswagen', ' Polo'], [' Renault', ' Kwid'], [' Maruti', ' Ertiga'], [' Maruti', ' Eeco'], [' Maruti', ' Alto', ' 800'], [' Mahindra', ' XUV500'], [' Hyundai', ' Grand', ' i10'], [' Hyundai', ' i10'], [' Honda', ' CRV'], [' Nissan', ' MAGNITE'], [' Maruti', ' Wagon', ' R', ' 1'], [' Tata', ' Tiago'], [' Maruti', ' Dzire'], [' Hyundai', ' Eon'], [' Hyundai', ' Elite', ' i20'], [' Maruti', ' Alto', ' K10']]
['Undri, Pune', 'Tathawade, Pune', 'Undri, Pune', 'Tathawade, Pune', 'Undri, Pune', 'Tathawade, Pune', 'Tathawade, Pune', 'Undri, Pune', 'Undri, Pune', 'Tathawade, Pune', 'Undri, Pune', 'Tathawade, Pune', 'Tathawade, Pune', 'Undri, Pune', 'Undri, Pune', 'Tathawade, Pune', 'Undri, Pune', 'Tathawade, Pune', 'Undri, Pune', 'Undri, Pune']
[['65,515'], ['29,202'], ['79,548'], ['34,513'], ['67,471'], ['58,103'], ['58,042'], ['47,079'], ['63,748'], ['90,963'], ['40,352'], ['48,863'], ['84,498'], ['42,454'], ['36,113'], ['61,157'], ['40,277'], ['66,145'], ['1,14', ',848'], ['42,591']]
[['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], nan, ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['299000', '221000', '670000', '973000', '443000', '279000', '599000', '400000', '181000', '788000', '580000', '205000', '708000', '681000', '200000', '402000', '642000', '181000', '540000', '274000']

In [102]:
dicto15 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [103]:
kmt1 = []
dicto15["Kmt run"]
for i in dicto15["Kmt run"]:
    
    if i:
        a = str(i).replace('[','')
        b = a.replace(' ','')
        c = b.replace(',','')
        d = c.replace(']','')
        e = d.replace("''",'')
        kmt1.append((e.strip("'")))
    else:
        kmt1.append(' ')
        
dicto15n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto15n

{'Name of Cars': [[' Hyundai', ' i10'],
  [' Hyundai', ' Eon'],
  [' Honda', ' WR'],
  [' KIA', ' SELTOS'],
  [' Volkswagen', ' Polo'],
  [' Renault', ' Kwid'],
  [' Maruti', ' Ertiga'],
  [' Maruti', ' Eeco'],
  [' Maruti', ' Alto', ' 800'],
  [' Mahindra', ' XUV500'],
  [' Hyundai', ' Grand', ' i10'],
  [' Hyundai', ' i10'],
  [' Honda', ' CRV'],
  [' Nissan', ' MAGNITE'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Tata', ' Tiago'],
  [' Maruti', ' Dzire'],
  [' Hyundai', ' Eon'],
  [' Hyundai', ' Elite', ' i20'],
  [' Maruti', ' Alto', ' K10']],
 'Registration Year': ['2011',
  '2014',
  '2017',
  '2020',
  '2016',
  '2016',
  '2014',
  '2014',
  '2012',
  '2017',
  '2019',
  '2011',
  '2014',
  '2021',
  '2010',
  '2017',
  '2017',
  '2011',
  '2017',
  '2016'],
 'Kmt run': ['65515',
  '29202',
  '79548',
  '34513',
  '67471',
  '58103',
  '58042',
  '47079',
  '63748',
  '90963',
  '40352',
  '48863',
  '84498',
  '42454',
  '36113',
  '61157',
  '40277',
  '66145',
  '114848',
  '42591'],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  nan,
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['299000',
  '221000',
  '670000',
  '973000',
  '443000',
  '279000',
  '599000',
  '400000',
  '181000',
  '788000',
  '580000',
  '205000',
  '708000',
  '681000',
  '200000',
  '402000',
  '642000',
  '181000',
  '540000',
  '274000'],
 'Location of car': ['Undri, Pune',
  'Tathawade, Pune',
  'Undri, Pune',
  'Tathawade, Pune',
  'Undri, Pune',
  'Tathawade, Pune',
  'Tathawade, Pune',
  'Undri, Pune',
  'Undri, Pune',
  'Tathawade, Pune',
  'Undri, Pune',
  'Tathawade, Pune',
  'Tathawade, Pune',
  'Undri, Pune',
  'Undri, Pune',
  'Tathawade, Pune',
  'Undri, Pune',
  'Tathawade, Pune',
  'Undri, Pune',
  'Undri, Pune']}

In [104]:
url16 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata%3AOR%3Amake%3A%3D%3Ahonda%3AOR%3Amake%3A%3D%3Arenault%3AOR%3Amake%3A%3D%3Atoyota%3AOR%3Amake%3A%3D%3Aford%3AOR%3Amake%3A%3D%3Amahindra%3AOR%3Amake%3A%3D%3Avolkswagen%3AOR%3Amake%3A%3D%3Adatsun%3AOR%3Amake%3A%3D%3Akia%3AOR%3Amake%3A%3D%3Anissan%3AOR%3Amake%3A%3D%3Ajeep%3AOR%3Amake%3A%3D%3Askoda&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=136&pinId=202124"

In [105]:
new16 = req.get(url16)
new16

In [106]:
soup = BeautifulSoup(new16.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n53 Used Cars in Agra - Second Hand Cars for Sale\n\n AgraBuy a carPopular makesMarutiHyundaiHondaRenaultTataFordView all makesPopular ModelsMaruti DzireHyundai i10Maruti SwiftHonda CityHyundai i20Maruti BalenoMaruti Wagon RMaruti BrezzaMaruti IGNISMaruti CiazView all modelsBody typeHatchbackSedanSUVLuxury SedanFuel typePetrolDieselTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Swift Dzire (6)Hyundai Grand i10 (6)Maruti Swift (4)Honda City (4)Maruti Baleno (3)Hyundai Elite i20 (3)ALL BRANDSMaruti (28)Hyundai (16)Honda (6)Ford (1)Tata (1)Renault (1)KIA (0)Datsun (0)BMW (0)Mercedes Benz (0)Skoda (0)Audi (0)Mahindra (0)Jeep (0)Fiat (0)Toyota (0)MG (0)Nissan (0)Volkswagen (0)Volvo (0)Jaguar (0)Budget₹ 1,50,000₹ 15,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear AllShow More 53 Used cars in AgraSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹1,11,000off2017 Maruti SwiftVDIManual1,24,644 km1st OwnerDieselUP-16₹6,115/month ₹78,200 downpayment₹3,91,000₹5,02,000Maharishi Puram, Agra\n2011 Hyundai i10ERA 1.1Manual40,596 km1st OwnerPetrolUP-80₹2,831/month ₹36,200 downpayment₹1,81,000Maharishi Puram, Agra\nNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility 2013 Maruti Wagon R 1.0LXIManual87,208 km1st OwnerPetrolUP-85₹3,910/month ₹50,000 downpayment₹2,50,000Maharishi Puram, Agra\n₹43,000off2018 Maruti IGNISALPHA 1.2Manual1,23,617 km1st OwnerPetrolUP-80₹5,834/month ₹74,600 downpayment₹3,73,000₹4,16,000Maharishi Puram, Agra\n2018 Renault KwidRXT 1.0 AMT (O)Automatic31,124 km2nd OwnerPetrolUP-15₹5,365/month ₹68,600 downpayment₹3,43,000Maharishi Puram, Agra\nUsed cars in Agra by brandMarutiHyundaiHondaFordRenaultTataMahindraToyota₹15,000off2014 Maruti Swift DzireVXIManual55,756 km2nd OwnerPetrolUP-80₹5,818/month ₹74,400 downpayment₹3,72,000₹3,87,000Maharishi Puram, Agra\n₹12,000off2017 Maruti Vitara BrezzaVDI (O)Manual1,20,160 km1st OwnerDieselUP-80₹10,182/month ₹1,30,200 downpayment₹6,51,000₹6,63,000Maharishi Puram, Agra\n₹5,000off2018 Maruti SwiftZXI AMTAutomatic1,11,670 km1st OwnerPetrolUP-85₹8,493/month ₹1,08,600 downpayment₹5,43,000₹5,48,000Maharishi Puram, Agra\nUsed cars in Agra by body typeHatchbackSedanSUVLuxury Sedan₹35,000off2018 Hyundai Elite i20SPORTZ 1.2Manual38,600 km2nd OwnerPetrolUP-80₹9,212/month ₹1,17,800 downpayment₹5,89,000₹6,24,000Maharishi Puram, Agra\n₹5,000off2015 Hyundai Elite i20MAGNA 1.2Manual51,837 km2nd OwnerPetrolUP-80₹7,210/month ₹92,200 downpayment₹4,61,000₹4,66,000Maharishi Puram, Agra\n₹5,000off2013 Hyundai VernaFLUIDIC 1.6 VTVT SXManual50,765 km1st OwnerPetrolUP-80₹6,976/month ₹89,200 downpayment₹4,46,000₹4,51,000Maharishi Puram, Agra\nUsed cars in Agra by fuel typePetrolDieselCNG₹600off2018 Maruti Alto K10VXIManual32,992 km1st OwnerPetrolUP-81₹5,527/month ₹70,680 downpayment₹3,53,400₹3,54,000Maharishi Puram, Agra\n2014 Hyundai i20SPORTZ 1.4 CRDIManual90,360 km2nd OwnerDieselUP-80₹4,958/month ₹63,400 downpayment₹3,17,000Maharishi Puram, Agra\n2015 Maruti CelerioVXIManual35,915 km1st OwnerPetrolUP-86₹5,505/month ₹70,400 downpayment₹3,52,000Maharishi Puram, Agra\nUsed cars in Agra by budgetbetween 2 to 5 lakhsbetween 5 to 10 lakhsunder 2 lakhsabove 10 lakhs₹47,000off2018 Hyundai New Elantra2.0 SX(O) AT PETROLAutomatic36,899 km1st OwnerPetrolUP-80₹18,912/month ₹2,48,400 downpayment₹12,42,000₹12,89,000Maharishi Puram, Agra\n2013 Maruti SwiftVXIManual88,991 km1st OwnerPetrolUP-80₹5,271/month ₹67,400 downpayment₹3,37,000Maharishi Puram, Agra\n₹36,000off2017 Maruti IGNISZETA 1.2Manual77,184 km1st OwnerPetrolUP-80₹6,319/month ₹80,800 downpayment₹4,04,000₹4,40,000Maharishi Puram, Agra\nUsed cars in Agra by modelMaruti DzireHyundai i10Hyundai i20Honda CityMaruti SwiftMaruti Wagon RMaruti BalenoMaruti BrezzaMaruti AltoMaruti CiazMaruti IGNISHonda JazzMaruti ErtigaHyundai New ElantraHyundai EonFord EcosportRenault KwidHyundai VernaHonda AmazeHyundai Santro₹10,000off2014 Honda City1.5L I-VTEC VX CVTAutomatic72,953 km1st OwnerPetrolUP-80₹8,884/month ₹1,13,600 downpayment₹5,68,000₹5,78,000Maharishi Puram, Agra\n2018 Maruti DzireVXIManual48,368 km3rd OwnerPetrolUP-80₹9,134/month ₹1,16,800 downpayment₹5,84,000Maharishi Puram, Agra\n₹8,000off2014 Maruti Swift DzireVDIManual1,07,539 km1st OwnerDieselUP-81₹5,912/month ₹75,600 downpayment₹3,78,000₹3,86,000Maharishi Puram, Agra\nHomeUsed CarsAgra45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions AgraWhat are the most popular brands available for 2nd hand cars in Agra?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Agra of your choice on CARS24.What body types are available for 2nd hand cars in Agra?Used cars in Agra are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Agra?Of Course yes, you can buy used cars online in Agra from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in AgraWhat to check before buying a second hand car in Agra?Important things to check  before buying a second hand car in Agra are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Agra?You can buy used cars in Agra from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Agra?You can check second hand cars in Agra using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in AgraHow many second hand cars are available in Agra?53 used cars are available in Agra of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in AgraUsed Hyundai Cars in AgraUsed Honda Cars in AgraUsed Ford Cars in AgraUsed Renault Cars in AgraUsed Tata Cars in AgraUsed Mahindra Cars in AgraUsed Toyota Cars in AgraBody :Used Hatchback Cars in AgraUsed Sedan Cars in AgraUsed SUV Cars in AgraUsed Luxury Sedan Cars in AgraFuel :Used Petrol Cars in AgraUsed Diesel Cars in AgraUsed CNG Cars in AgraBudget :Used Cars between 2 to 5 lakhs in AgraUsed Cars between 5 to 10 lakhs in AgraUsed Cars under 2 lakhs in AgraUsed Cars above 10 lakhs in AgraModel :Used Maruti Dzire Cars in AgraUsed Hyundai i10 Cars in AgraUsed Hyundai i20 Cars in AgraUsed Honda City Cars in AgraUsed Maruti Swift Cars in AgraUsed Maruti Wagon R Cars in AgraUsed Maruti Baleno Cars in AgraUsed Maruti Brezza Cars in AgraUsed Maruti Alto Cars in AgraUsed Maruti Ciaz Cars in AgraUsed Maruti IGNIS Cars in AgraUsed Honda Jazz Cars in AgraUsed Maruti Ertiga Cars in AgraUsed Hyundai New Elantra Cars in AgraUsed Hyundai Eon Cars in AgraUsed Ford Ecosport Cars in AgraUsed Renault Kwid Cars in AgraUsed Hyundai Verna Cars in AgraUsed Honda Amaze Cars in AgraUsed Hyundai Santro Cars in AgraTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [107]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2017', '2011', '2013', '2018', '2018', '2014', '2017', '2018', '2018', '2015', '2013', '2018', '2014', '2015', '2018', '2013', '2017', '2014', '2018', '2014']
[[' Maruti', ' Swift'], [' Hyundai', ' i10'], [' Maruti', ' Wagon', ' R', ' 1'], [' Maruti', ' IGNIS'], [' Renault', ' Kwid'], [' Maruti', ' Swift', ' Dzire'], [' Maruti', ' Vitara', ' Brezza'], [' Maruti', ' Swift'], [' Hyundai', ' Elite', ' i20'], [' Hyundai', ' Elite', ' i20'], [' Hyundai', ' Verna'], [' Maruti', ' Alto', ' K10'], [' Hyundai', ' i20'], [' Maruti', ' Celerio'], [' Hyundai', ' New', ' Elantra'], [' Maruti', ' Swift'], [' Maruti', ' IGNIS'], [' Honda', ' City'], [' Maruti', ' Dzire'], [' Maruti', ' Swift', ' Dzire']]
['Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n', 'Maharishi Puram, Agra\n']
[['1,24', ',644'], ['40,596'], ['87,208'], ['1,23', ',617'], ['31,124'], ['55,756'], ['1,20', ',160'], ['1,11', ',670'], ['38,600'], ['51,837'], ['50,765'], ['32,992'], ['90,360'], ['35,915'], ['36,899'], ['88,991'], ['77,184'], ['72,953'], ['48,368'], ['1,07', ',539']]
[['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual']]
['391000', '181000', '250000', '373000', '343000', '372000', '651000', '543000', '589000', '461000', '446000', '353400', '317000', '352000', '1242000', '337000', '404000', '568000', '584000', '378000']

In [108]:
dicto16 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [109]:
kmt1 = []
dicto16["Kmt run"]
for i in dicto16["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto16n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto16n

{'Name of Cars': [[' Maruti', ' Swift'],
  [' Hyundai', ' i10'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Maruti', ' IGNIS'],
  [' Renault', ' Kwid'],
  [' Maruti', ' Swift', ' Dzire'],
  [' Maruti', ' Vitara', ' Brezza'],
  [' Maruti', ' Swift'],
  [' Hyundai', ' Elite', ' i20'],
  [' Hyundai', ' Elite', ' i20'],
  [' Hyundai', ' Verna'],
  [' Maruti', ' Alto', ' K10'],
  [' Hyundai', ' i20'],
  [' Maruti', ' Celerio'],
  [' Hyundai', ' New', ' Elantra'],
  [' Maruti', ' Swift'],
  [' Maruti', ' IGNIS'],
  [' Honda', ' City'],
  [' Maruti', ' Dzire'],
  [' Maruti', ' Swift', ' Dzire']],
 'Registration Year': ['2017',
  '2011',
  '2013',
  '2018',
  '2018',
  '2014',
  '2017',
  '2018',
  '2018',
  '2015',
  '2013',
  '2018',
  '2014',
  '2015',
  '2018',
  '2013',
  '2017',
  '2014',
  '2018',
  '2014'],
 'Kmt run': [124644,
  40596,
  87208,
  123617,
  31124,
  55756,
  120160,
  111670,
  38600,
  51837,
  50765,
  32992,
  90360,
  35915,
  36899,
  88991,
  77184,
  72953,
  48368,
  107539],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel']],
 'Price': ['391000',
  '181000',
  '250000',
  '373000',
  '343000',
  '372000',
  '651000',
  '543000',
  '589000',
  '461000',
  '446000',
  '353400',
  '317000',
  '352000',
  '1242000',
  '337000',
  '404000',
  '568000',
  '584000',
  '378000'],
 'Location of car': ['Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n',
  'Maharishi Puram, Agra\n']}

In [110]:
url17 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata%3AOR%3Amake%3A%3D%3Ahonda%3AOR%3Amake%3A%3D%3Arenault%3AOR%3Amake%3A%3D%3Atoyota%3AOR%3Amake%3A%3D%3Aford%3AOR%3Amake%3A%3D%3Amahindra%3AOR%3Amake%3A%3D%3Avolkswagen%3AOR%3Amake%3A%3D%3Adatsun%3AOR%3Amake%3A%3D%3Akia%3AOR%3Amake%3A%3D%3Anissan%3AOR%3Amake%3A%3D%3Ajeep%3AOR%3Amake%3A%3D%3Askoda&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=769&pinId=134101"

In [111]:
new17 = req.get(url17)
new17

In [112]:
soup = BeautifulSoup(new17.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n300 Used Cars in Chandigarh - Second Hand Cars for Sale\n\n ChandigarhBuy a carPopular makesMarutiHyundaiHondaTataRenaultMahindraToyotaFordVolkswagenNissanView all makesPopular ModelsMaruti AltoHyundai i10Maruti SwiftMaruti BrezzaMaruti BalenoMaruti DzireHonda CityHyundai i20Hyundai SantroMaruti Wagon RView all modelsBody typeHatchbackSUVSedanLuxury SUVLuxury SedanFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Swift (21)Maruti Alto K10 (20)Maruti Vitara Brezza (17)Maruti Baleno (15)Hyundai Grand i10 (11)Hyundai NEW SANTRO (10)ALL BRANDSMaruti (140)Hyundai (68)Honda (24)Tata (14)Renault (11)Mahindra (10)Toyota (9)Ford (8)Nissan (4)Volkswagen (4)KIA (3)Datsun (2)Skoda (2)Jeep (1)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)MG (0)Volvo (0)Jaguar (0)Budget₹ 1,50,000₹ 25,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear AllShow More 300 Used cars in ChandigarhSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹10,000off2010 Hyundai i10MAGNA 1.2Manual80,727 km1st OwnerPetrolCH-01₹2,659/month ₹34,000 downpayment₹1,70,000₹1,80,000Paras Downtown Square, Chandigarh₹41,000off2019 Hyundai VENUES 1.2Manual42,118 km1st OwnerPetrolPB-10₹11,089/month ₹1,41,800 downpayment₹7,09,000₹7,50,000Wave Mall, LudhianaNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility 2019 Maruti SwiftLXIManual1,06,184 km1st OwnerPetrolCH-01₹8,508/month ₹1,08,800 downpayment₹5,44,000Paras Downtown Square, Chandigarh₹37,000off2015 Honda City1.5L I-VTEC V MTManual96,379 km2nd OwnerPetrolCH-01₹7,711/month ₹98,600 downpayment₹4,93,000₹5,30,000Paras Downtown Square, Chandigarh₹32,000off2022 Tata TIGORXZ CNGManual44,564 km1st OwnerCNGPB-87₹12,197/month ₹1,60,200 downpayment₹8,01,000₹8,33,000Paras Downtown Square, ChandigarhUsed cars in Chandigarh by brandMarutiHyundaiHondaTataRenaultMahindraToyotaFordVolkswagenKIANissanSkodaJeepDatsunMGBMW2021 Hyundai GRAND I10 NIOSMAGNA 1.2 KAPPA VTVTManual27,381 km2nd OwnerPetrolPB-18₹9,494/month ₹1,21,400 downpayment₹6,07,000Paras Downtown Square, Chandigarh2019 Volkswagen AmeoTRENDLINE 1.0LManual48,295 km1st OwnerPetrolPB-02₹7,804/month ₹99,800 downpayment₹4,99,000Paras Downtown Square, Chandigarh₹42,000off2018 Honda Amaze1.2L I-VTEC SManual31,904 km1st OwnerPetrolPB-08₹8,680/month ₹1,11,000 downpayment₹5,55,000₹5,97,000Paras Downtown Square, ChandigarhUsed cars in Chandigarh by body typeHatchbackSUVSedanLuxury SedanLuxury SUV2017 Datsun Go PlusTManual57,422 km1st OwnerPetrolCH-01₹4,567/month ₹58,400 downpayment₹2,92,000Paras Downtown Square, Chandigarh₹40,000off2014 Mahindra XUV500W8Manual89,077 km1st OwnerDieselHR-03₹8,461/month ₹1,08,200 downpayment₹5,41,000₹5,81,000Paras Downtown Square, Chandigarh₹70,000off2014 Maruti SwiftVDIManual78,352 km2nd OwnerDieselHR-29₹5,161/month ₹66,000 downpayment₹3,30,000₹4,00,000Paras Downtown Square, ChandigarhUsed cars in Chandigarh by fuel typePetrolDieselCNG₹88,000off2019 Maruti AltoLXIManual27,760 km1st OwnerPetrolHR-19₹4,411/month ₹56,400 downpayment₹2,82,000₹3,70,000Paras Downtown Square, Chandigarh₹1,01,000off2020 Volkswagen PoloTRENDLINE 1.0LManual45,550 km1st OwnerPetrolHR-02₹7,726/month ₹98,800 downpayment₹4,94,000₹5,95,000Paras Downtown Square, Chandigarh₹82,000off2015 Maruti BalenoDELTA DIESEL 1.3Manual52,311 km1st OwnerDieselHR-51₹5,709/month ₹73,000 downpayment₹3,65,000₹4,47,000Paras Downtown Square, ChandigarhUsed cars in Chandigarh by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhsunder 2 lakhs₹40,000off2015 Maruti Alto K10VXIManual46,785 km2nd OwnerPetrolPB-09₹3,691/month ₹47,200 downpayment₹2,36,000₹2,76,000Paras Downtown Square, Chandigarh2022 Maruti AltoVXIManual14,180 km1st OwnerPetrolHR-71₹6,225/month ₹79,600 downpayment₹3,98,000Paras Downtown Square, Chandigarh₹29,000off2013 Maruti SwiftVDIManual90,533 km2nd OwnerDieselHR-29₹4,583/month ₹58,600 downpayment₹2,93,000₹3,22,000Paras Downtown Square, ChandigarhUsed cars in Chandigarh by modelMaruti AltoHyundai i10Maruti SwiftMaruti BrezzaMaruti BalenoMaruti DzireHonda CityHyundai i20Hyundai SantroMaruti Wagon RFord EcosportMaruti CiazMaruti CelerioRenault TRIBERTata NEXONHyundai CretaHyundai AURAMaruti S PRESSOHonda BrioToyota YARIS₹75,000off2016 Toyota EtiosCROSS 1.4 VDManual74,075 km2nd OwnerDieselHR-29₹6,209/month ₹79,400 downpayment₹3,97,000₹4,72,000Paras Downtown Square, Chandigarh₹50,000off2013 Maruti SwiftVDIManual85,724 km3rd OwnerDieselHR-19₹4,833/month ₹61,800 downpayment₹3,09,000₹3,59,000Paras Downtown Square, Chandigarh₹31,000off2010 Maruti SwiftVXIManual92,322 km1st OwnerPetrolHR-03₹3,425/month ₹43,800 downpayment₹2,19,000₹2,50,000Paras Downtown Square, ChandigarhHomeUsed CarsChandigarh45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions ChandigarhWhat are the most popular brands available for 2nd hand cars in Chandigarh?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Chandigarh of your choice on CARS24.What body types are available for 2nd hand cars in Chandigarh?Used cars in Chandigarh are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Chandigarh?Of Course yes, you can buy used cars online in Chandigarh from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in ChandigarhWhat to check before buying a second hand car in Chandigarh?Important things to check  before buying a second hand car in Chandigarh are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Chandigarh?You can buy used cars in Chandigarh from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Chandigarh?You can check second hand cars in Chandigarh using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in ChandigarhHow many second hand cars are available in Chandigarh?300 used cars are available in Chandigarh of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in ChandigarhUsed Hyundai Cars in ChandigarhUsed Honda Cars in ChandigarhUsed Tata Cars in ChandigarhUsed Renault Cars in ChandigarhUsed Mahindra Cars in ChandigarhUsed Toyota Cars in ChandigarhUsed Ford Cars in ChandigarhUsed Volkswagen Cars in ChandigarhUsed KIA Cars in ChandigarhUsed Nissan Cars in ChandigarhUsed Skoda Cars in ChandigarhUsed Jeep Cars in ChandigarhUsed Datsun Cars in ChandigarhUsed MG Cars in ChandigarhUsed BMW Cars in ChandigarhBody :Used Hatchback Cars in ChandigarhUsed SUV Cars in ChandigarhUsed Sedan Cars in ChandigarhUsed Luxury Sedan Cars in ChandigarhUsed Luxury SUV Cars in ChandigarhFuel :Used Petrol Cars in ChandigarhUsed Diesel Cars in ChandigarhUsed CNG Cars in ChandigarhBudget :Used Cars between 5 to 10 lakhs in ChandigarhUsed Cars between 2 to 5 lakhs in ChandigarhUsed Cars above 10 lakhs in ChandigarhUsed Cars under 2 lakhs in ChandigarhModel :Used Maruti Alto Cars in ChandigarhUsed Hyundai i10 Cars in ChandigarhUsed Maruti Swift Cars in ChandigarhUsed Maruti Brezza Cars in ChandigarhUsed Maruti Baleno Cars in ChandigarhUsed Maruti Dzire Cars in ChandigarhUsed Honda City Cars in ChandigarhUsed Hyundai i20 Cars in ChandigarhUsed Hyundai Santro Cars in ChandigarhUsed Maruti Wagon R Cars in ChandigarhUsed Ford Ecosport Cars in ChandigarhUsed Maruti Ciaz Cars in ChandigarhUsed Maruti Celerio Cars in ChandigarhUsed Renault TRIBER Cars in ChandigarhUsed Tata NEXON Cars in ChandigarhUsed Hyundai Creta Cars in ChandigarhUsed Hyundai AURA Cars in ChandigarhUsed Maruti S PRESSO Cars in ChandigarhUsed Honda Brio Cars in ChandigarhUsed Toyota YARIS Cars in ChandigarhTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [113]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2010', '2019', '2019', '2015', '2022', '2021', '2019', '2018', '2017', '2014', '2014', '2019', '2020', '2015', '2015', '2022', '2013', '2016', '2013', '2010']
[[' Hyundai', ' i10'], [' Hyundai', ' VENUE'], [' Maruti', ' Swift'], [' Honda', ' City'], [' Tata', ' TIGOR'], [' Hyundai', ' GRAND', ' I10', ' NIOS'], [' Volkswagen', ' Ameo'], [' Honda', ' Amaze'], [' Datsun', ' Go', ' Plus'], [' Mahindra', ' XUV500'], [' Maruti', ' Swift'], [' Maruti', ' Alto'], [' Volkswagen', ' Polo'], [' Maruti', ' Baleno'], [' Maruti', ' Alto', ' K10'], [' Maruti', ' Alto'], [' Maruti', ' Swift'], [' Toyota', ' Etios'], [' Maruti', ' Swift'], [' Maruti', ' Swift']]
['Paras Downtown Square, Chandigarh', 'Wave Mall, Ludhiana', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh']
[['80,727'], ['42,118'], ['1,06', ',184'], ['96,379'], ['44,564'], ['27,381'], ['48,295'], ['31,904'], ['57,422'], ['89,077'], ['78,352'], ['27,760'], ['45,550'], ['52,311'], ['46,785'], ['14,180'], ['90,533'], ['74,075'], ['85,724'], ['92,322']]
[['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], nan, ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Diesel'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Diesel'], ['Diesel'], ['Diesel'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['170000', '709000', '544000', '493000', '801000', '607000', '499000', '555000', '292000', '541000', '330000', '282000', '494000', '365000', '236000', '398000', '293000', '397000', '309000', '219000']

In [114]:
dicto17 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [115]:
kmt1 = []
dicto17["Kmt run"]
for i in dicto17["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto17n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto17n

{'Name of Cars': [[' Hyundai', ' i10'],
  [' Hyundai', ' VENUE'],
  [' Maruti', ' Swift'],
  [' Honda', ' City'],
  [' Tata', ' TIGOR'],
  [' Hyundai', ' GRAND', ' I10', ' NIOS'],
  [' Volkswagen', ' Ameo'],
  [' Honda', ' Amaze'],
  [' Datsun', ' Go', ' Plus'],
  [' Mahindra', ' XUV500'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Alto'],
  [' Volkswagen', ' Polo'],
  [' Maruti', ' Baleno'],
  [' Maruti', ' Alto', ' K10'],
  [' Maruti', ' Alto'],
  [' Maruti', ' Swift'],
  [' Toyota', ' Etios'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Swift']],
 'Registration Year': ['2010',
  '2019',
  '2019',
  '2015',
  '2022',
  '2021',
  '2019',
  '2018',
  '2017',
  '2014',
  '2014',
  '2019',
  '2020',
  '2015',
  '2015',
  '2022',
  '2013',
  '2016',
  '2013',
  '2010'],
 'Kmt run': [80727,
  42118,
  106184,
  96379,
  44564,
  27381,
  48295,
  31904,
  57422,
  89077,
  78352,
  27760,
  45550,
  52311,
  46785,
  14180,
  90533,
  74075,
  85724,
  92322],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  nan,
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Diesel'],
  ['Diesel'],
  ['Petrol']],
 'Price': ['170000',
  '709000',
  '544000',
  '493000',
  '801000',
  '607000',
  '499000',
  '555000',
  '292000',
  '541000',
  '330000',
  '282000',
  '494000',
  '365000',
  '236000',
  '398000',
  '293000',
  '397000',
  '309000',
  '219000'],
 'Location of car': ['Paras Downtown Square, Chandigarh',
  'Wave Mall, Ludhiana',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh']}

In [116]:
url18 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata%3AOR%3Amake%3A%3D%3Ahonda%3AOR%3Amake%3A%3D%3Arenault%3AOR%3Amake%3A%3D%3Atoyota%3AOR%3Amake%3A%3D%3Aford%3AOR%3Amake%3A%3D%3Amahindra%3AOR%3Amake%3A%3D%3Avolkswagen%3AOR%3Amake%3A%3D%3Adatsun%3AOR%3Amake%3A%3D%3Akia%3AOR%3Amake%3A%3D%3Anissan%3AOR%3Amake%3A%3D%3Ajeep%3AOR%3Amake%3A%3D%3Askoda&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=6105&pinId=641001"

In [117]:
new18 = req.get(url18)
new18

In [118]:
soup = BeautifulSoup(new18.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n102 Used Cars in Coimbatore - Second Hand Cars for Sale\n\n CoimbatoreBuy a carPopular makesMarutiRenaultTataHyundaiHondaFordMahindraDatsunVolkswagenJeepView all makesPopular ModelsRenault TRIBERRenault KwidMaruti BalenoTata TiagoTata ALTROZFord EcosportHonda AmazeMaruti SwiftMaruti AltoHyundai EonView all modelsBody typeHatchbackSUVSedanLuxury SUVFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsRenault Kwid (7)Renault TRIBER (7)Tata Tiago (6)Maruti Baleno (6)Tata ALTROZ (5)Ford Ecosport (5)ALL BRANDSMaruti (23)Tata (15)Renault (15)Hyundai (14)Honda (9)Ford (8)Mahindra (5)Datsun (4)Volkswagen (4)KIA (2)Jeep (2)Skoda (1)MG (1)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Toyota (0)Nissan (0)Volvo (0)Jaguar (0)Budget₹ 2,00,000₹ 25,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear AllShow More 102 Used cars in CoimbatoreSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New2017 Tata NEXONXZ PLUS PETROLManual88,138 km2nd OwnerPetrolTN-39₹10,276/month ₹1,31,400 downpayment₹6,57,000Singanallur, Coimbatore₹61,000off2015 Maruti SwiftVXIManual68,094 km2nd OwnerPetrolTN-13₹7,445/month ₹95,200 downpayment₹4,76,000₹5,37,000Singanallur, CoimbatoreNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹86,000off2018 Tata NEXONXT PETROLManual53,039 km1st OwnerPetrolTN-59₹9,853/month ₹1,26,000 downpayment₹6,30,000₹7,16,000Singanallur, Coimbatore₹40,000off2022 Volkswagen VIRTUSTOPLINE TSI 1.0 ATAutomatic14,829 km1st OwnerPetrolTN-39₹25,490/month ₹3,34,800 downpayment₹16,74,000₹17,14,000Singanallur, Coimbatore₹17,500off2013 Maruti Alto 800LXIManual78,476 km2nd OwnerPetrolTN-55₹3,668/month ₹46,900 downpayment₹2,34,500₹2,52,000Singanallur, CoimbatoreUsed cars in Coimbatore by brandMarutiRenaultTataHyundaiHondaFordMahindraDatsunVolkswagenKIAJeepSkodaMGToyotaNissan₹70,000off2017 Honda Amaze1.2L I-VTEC SManual90,332 km2nd OwnerPetrolTN-45₹6,944/month ₹88,800 downpayment₹4,44,000₹5,14,000Singanallur, Coimbatore₹52,000off2015 Honda BrioS MTManual1,20,127 km3rd OwnerPetrolTN-86₹5,146/month ₹65,800 downpayment₹3,29,000₹3,81,000Singanallur, Coimbatore₹10,000off2018 Maruti Alto K10VXI (O)Manual43,447 km2nd OwnerPetrolTN-03₹5,677/month ₹72,600 downpayment₹3,63,000₹3,73,000Singanallur, CoimbatoreUsed cars in Coimbatore by body typeHatchbackSUVSedanLuxury SUVLuxury Sedan₹1,14,000off2017 Maruti BalenoZETA CVT PETROL 1.2Automatic44,254 km1st OwnerPetrolTN-13₹9,275/month ₹1,18,600 downpayment₹5,93,000₹7,07,000Singanallur, Coimbatore₹59,000off2016 Maruti BalenoZETA CVT PETROL 1.2Automatic71,475 km1st OwnerPetrolTN-30₹9,494/month ₹1,21,400 downpayment₹6,07,000₹6,66,000Singanallur, Coimbatore₹95,000off2017 Honda City1.5L I-VTEC V MTManual1,06,831 km2nd OwnerPetrolTN-34₹10,432/month ₹1,33,400 downpayment₹6,67,000₹7,62,000Singanallur, CoimbatoreUsed cars in Coimbatore by fuel typePetrolDieselCNG₹55,000off2017 Maruti DzireVXI AMTAutomatic33,550 km2nd OwnerPetrolTN-14₹9,619/month ₹1,23,000 downpayment₹6,15,000₹6,70,000Singanallur, Coimbatore2018 Volkswagen PoloGT TSI ATAutomatic77,471 km2nd OwnerPetrolTN-37₹12,199/month ₹1,56,000 downpayment₹7,80,000Singanallur, Coimbatore₹85,000off2020 Ford EcosportTREND 1.5L PETROLManual26,364 km1st OwnerPetrolTN-12₹10,072/month ₹1,28,800 downpayment₹6,44,000₹7,29,000Singanallur, CoimbatoreUsed cars in Coimbatore by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhs₹37,000off2019 Datsun Go PlusTManual18,689 km1st OwnerPetrolTN-82₹7,664/month ₹98,000 downpayment₹4,90,000₹5,27,000Singanallur, Coimbatore₹27,000off2018 Renault KwidRXT 1.0Manual80,003 km1st OwnerPetrolTN-39₹5,443/month ₹69,600 downpayment₹3,48,000₹3,75,000Singanallur, Coimbatore₹47,000off2015 Maruti CelerioVXIManual1,14,529 km1st OwnerPetrolTN-14₹5,552/month ₹71,000 downpayment₹3,55,000₹4,02,000Singanallur, CoimbatoreUsed cars in Coimbatore by modelRenault TRIBERMaruti BalenoRenault KwidTata TiagoFord EcosportMaruti SwiftTata ALTROZHonda AmazeMaruti AltoTata NEXONMahindra XUV 3OOHyundai i10Datsun Go PlusHyundai EonHyundai CretaMaruti BrezzaVolkswagen VIRTUSHyundai VENUEKIA SONETMaruti Dzire₹46,000off2018 Datsun Go PlusTManual10,216 km1st OwnerPetrolTN-30₹6,491/month ₹83,000 downpayment₹4,15,000₹4,61,000Singanallur, Coimbatore₹1,34,000off2021 Skoda RapidAMBITION TSIManual39,753 km1st OwnerPetrolTN-32₹13,217/month ₹1,73,600 downpayment₹8,68,000₹10,02,000Singanallur, Coimbatore₹36,000off2017 Maruti DzireVXIManual29,753 km2nd OwnerPetrolTN-30₹9,963/month ₹1,27,400 downpayment₹6,37,000₹6,73,000Singanallur, CoimbatoreHomeUsed CarsCoimbatore45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions CoimbatoreWhat are the most popular brands available for 2nd hand cars in Coimbatore?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Coimbatore of your choice on CARS24.What body types are available for 2nd hand cars in Coimbatore?Used cars in Coimbatore are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Coimbatore?Of Course yes, you can buy used cars online in Coimbatore from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in CoimbatoreWhat to check before buying a second hand car in Coimbatore?Important things to check  before buying a second hand car in Coimbatore are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Coimbatore?You can buy used cars in Coimbatore from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Coimbatore?You can check second hand cars in Coimbatore using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in CoimbatoreHow many second hand cars are available in Coimbatore?102 used cars are available in Coimbatore of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in CoimbatoreUsed Renault Cars in CoimbatoreUsed Tata Cars in CoimbatoreUsed Hyundai Cars in CoimbatoreUsed Honda Cars in CoimbatoreUsed Ford Cars in CoimbatoreUsed Mahindra Cars in CoimbatoreUsed Datsun Cars in CoimbatoreUsed Volkswagen Cars in CoimbatoreUsed KIA Cars in CoimbatoreUsed Jeep Cars in CoimbatoreUsed Skoda Cars in CoimbatoreUsed MG Cars in CoimbatoreUsed Toyota Cars in CoimbatoreUsed Nissan Cars in CoimbatoreBody :Used Hatchback Cars in CoimbatoreUsed SUV Cars in CoimbatoreUsed Sedan Cars in CoimbatoreUsed Luxury SUV Cars in CoimbatoreUsed Luxury Sedan Cars in CoimbatoreFuel :Used Petrol Cars in CoimbatoreUsed Diesel Cars in CoimbatoreUsed CNG Cars in CoimbatoreBudget :Used Cars between 5 to 10 lakhs in CoimbatoreUsed Cars between 2 to 5 lakhs in CoimbatoreUsed Cars above 10 lakhs in CoimbatoreModel :Used Renault TRIBER Cars in CoimbatoreUsed Maruti Baleno Cars in CoimbatoreUsed Renault Kwid Cars in CoimbatoreUsed Tata Tiago Cars in CoimbatoreUsed Ford Ecosport Cars in CoimbatoreUsed Maruti Swift Cars in CoimbatoreUsed Tata ALTROZ Cars in CoimbatoreUsed Honda Amaze Cars in CoimbatoreUsed Maruti Alto Cars in CoimbatoreUsed Tata NEXON Cars in CoimbatoreUsed Mahindra XUV 3OO Cars in CoimbatoreUsed Hyundai i10 Cars in CoimbatoreUsed Datsun Go Plus Cars in CoimbatoreUsed Hyundai Eon Cars in CoimbatoreUsed Hyundai Creta Cars in CoimbatoreUsed Maruti Brezza Cars in CoimbatoreUsed Volkswagen VIRTUS Cars in CoimbatoreUsed Hyundai VENUE Cars in CoimbatoreUsed KIA SONET Cars in CoimbatoreUsed Maruti Dzire Cars in CoimbatoreTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [119]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2017', '2015', '2018', '2022', '2013', '2017', '2015', '2018', '2017', '2016', '2017', '2017', '2018', '2020', '2019', '2018', '2015', '2018', '2021', '2017']
[[' Tata', ' NEXON'], [' Maruti', ' Swift'], [' Tata', ' NEXON'], [' Volkswagen', ' VIRTUS'], [' Maruti', ' Alto', ' 800'], [' Honda', ' Amaze'], [' Honda', ' Brio'], [' Maruti', ' Alto', ' K10'], [' Maruti', ' Baleno'], [' Maruti', ' Baleno'], [' Honda', ' City'], [' Maruti', ' Dzire'], [' Volkswagen', ' Polo'], [' Ford', ' Ecosport'], [' Datsun', ' Go', ' Plus'], [' Renault', ' Kwid'], [' Maruti', ' Celerio'], [' Datsun', ' Go', ' Plus'], [' Skoda', ' Rapid'], [' Maruti', ' Dzire']]
['Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore', 'Singanallur, Coimbatore']
[['88,138'], ['68,094'], ['53,039'], ['14,829'], ['78,476'], ['90,332'], ['1,20', ',127'], ['43,447'], ['44,254'], ['71,475'], ['1,06', ',831'], ['33,550'], ['77,471'], ['26,364'], ['18,689'], ['80,003'], ['1,14', ',529'], ['10,216'], ['39,753'], ['29,753']]
[['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Automatic'], ['Manual'], ['Automatic'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['657000', '476000', '630000', '1674000', '234500', '444000', '329000', '363000', '593000', '607000', '667000', '615000', '780000', '644000', '490000', '348000', '355000', '415000', '868000', '637000']

In [120]:
dicto18 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [121]:
kmt1 = []
dicto18["Kmt run"]
for i in dicto18["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto18n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto18n

{'Name of Cars': [[' Tata', ' NEXON'],
  [' Maruti', ' Swift'],
  [' Tata', ' NEXON'],
  [' Volkswagen', ' VIRTUS'],
  [' Maruti', ' Alto', ' 800'],
  [' Honda', ' Amaze'],
  [' Honda', ' Brio'],
  [' Maruti', ' Alto', ' K10'],
  [' Maruti', ' Baleno'],
  [' Maruti', ' Baleno'],
  [' Honda', ' City'],
  [' Maruti', ' Dzire'],
  [' Volkswagen', ' Polo'],
  [' Ford', ' Ecosport'],
  [' Datsun', ' Go', ' Plus'],
  [' Renault', ' Kwid'],
  [' Maruti', ' Celerio'],
  [' Datsun', ' Go', ' Plus'],
  [' Skoda', ' Rapid'],
  [' Maruti', ' Dzire']],
 'Registration Year': ['2017',
  '2015',
  '2018',
  '2022',
  '2013',
  '2017',
  '2015',
  '2018',
  '2017',
  '2016',
  '2017',
  '2017',
  '2018',
  '2020',
  '2019',
  '2018',
  '2015',
  '2018',
  '2021',
  '2017'],
 'Kmt run': [88138,
  68094,
  53039,
  14829,
  78476,
  90332,
  120127,
  43447,
  44254,
  71475,
  106831,
  33550,
  77471,
  26364,
  18689,
  80003,
  114529,
  10216,
  39753,
  29753],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Automatic'],
  ['Manual'],
  ['Automatic'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['657000',
  '476000',
  '630000',
  '1674000',
  '234500',
  '444000',
  '329000',
  '363000',
  '593000',
  '607000',
  '667000',
  '615000',
  '780000',
  '644000',
  '490000',
  '348000',
  '355000',
  '415000',
  '868000',
  '637000'],
 'Location of car': ['Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore',
  'Singanallur, Coimbatore']}

In [122]:
url19 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata%3AOR%3Amake%3A%3D%3Ahonda%3AOR%3Amake%3A%3D%3Arenault%3AOR%3Amake%3A%3D%3Atoyota%3AOR%3Amake%3A%3D%3Aford%3AOR%3Amake%3A%3D%3Amahindra%3AOR%3Amake%3A%3D%3Avolkswagen%3AOR%3Amake%3A%3D%3Adatsun%3AOR%3Amake%3A%3D%3Akia%3AOR%3Amake%3A%3D%3Anissan%3AOR%3Amake%3A%3D%3Ajeep%3AOR%3Amake%3A%3D%3Askoda&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=2713&pinId=440001"

In [123]:
new19 = req.get(url19)
new19

In [124]:
soup = BeautifulSoup(new19.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n138 Used Cars in Nagpur - Second Hand Cars for Sale\n\n NagpurBuy a carPopular makesMarutiHyundaiHondaRenaultNissanFordTataToyotaVolkswagenMahindraView all makesPopular ModelsMaruti AltoMaruti SwiftHyundai i20Maruti Wagon RMaruti BalenoHyundai i10Maruti DzireHonda CityRenault KwidMaruti CelerioView all modelsBody typeHatchbackSedanSUVLuxury SedanFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Swift (16)Maruti Alto 800 (13)Hyundai Elite i20 (11)Maruti Baleno (10)Honda City (8)Maruti Wagon R 1.0 (7)ALL BRANDSMaruti (74)Hyundai (31)Honda (16)Renault (7)Ford (2)Tata (2)Nissan (2)Skoda (1)Mahindra (1)Toyota (1)Volkswagen (1)KIA (0)Datsun (0)BMW (0)Mercedes Benz (0)Audi (0)Jeep (0)Fiat (0)MG (0)Volvo (0)Jaguar (0)Budget₹ 1,50,000₹ 15,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear AllShow More 138 Used cars in NagpurSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹59,000off2011 Maruti SwiftVDIManual87,743 km2nd OwnerDieselMH-31₹3,894/month ₹49,800 downpayment₹2,49,000₹3,08,000Kharbi, Nagpur₹39,000off2018 Renault KwidRXLManual47,552 km3rd OwnerPetrolMH-36₹4,301/month ₹55,000 downpayment₹2,75,000₹3,14,000Kharbi, NagpurNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹31,000off2012 Maruti Alto K10LXIManual96,133 km2nd OwnerPetrolMH-31₹2,518/month ₹32,200 downpayment₹1,61,000₹1,92,000Kharbi, Nagpur₹45,000off2018 Renault KwidRXLManual1,18,789 km1st OwnerPetrolMH-27₹4,238/month ₹54,200 downpayment₹2,71,000₹3,16,000Kharbi, Nagpur₹61,000off2017 Volkswagen PoloHIGHLINE1.2LManual49,118 km1st OwnerPetrolMH-14₹9,697/month ₹1,24,000 downpayment₹6,20,000₹6,81,000Kharbi, NagpurUsed cars in Nagpur by brandMarutiHyundaiHondaRenaultFordNissanTataVolkswagenToyotaMahindraSkodaMGKIADatsun₹9,000off2012 Honda City1.5L I-VTEC S MTManual84,920 km2nd OwnerPetrolMH-01₹4,770/month ₹61,000 downpayment₹3,05,000₹3,14,000Kharbi, Nagpur₹1,14,000off2017 Hyundai i20 Active1.2 BASEManual88,140 km1st OwnerPetrolMH-49₹7,617/month ₹97,400 downpayment₹4,87,000₹6,01,000Kharbi, Nagpur₹16,000off2010 Hyundai i10ERA 1.1Manual47,443 km3rd OwnerPetrolMH-31₹2,690/month ₹34,400 downpayment₹1,72,000₹1,88,000Kharbi, NagpurUsed cars in Nagpur by body typeHatchbackSedanSUVLuxury SedanLuxury SUV₹25,000off2019 Mahindra XUV 3OOW6 1.5 DIESELManual84,242 km1st OwnerDieselMH-49₹13,111/month ₹1,72,200 downpayment₹8,61,000₹8,86,000Kharbi, Nagpur₹58,000off2015 Maruti CelerioVXI CNGManual8,052 km2nd OwnerCNGMH-46₹4,833/month ₹61,800 downpayment₹3,09,000₹3,67,000Kharbi, Nagpur₹1,19,000off2014 Maruti Swift DzireVDIManual78,872 km2nd OwnerDieselMH-03₹6,553/month ₹83,800 downpayment₹4,19,000₹5,38,000Kharbi, NagpurUsed cars in Nagpur by fuel typePetrolDieselCNG₹15,000off2014 Maruti SwiftVXIManual89,062 km2nd OwnerPetrolMH-05₹5,787/month ₹74,000 downpayment₹3,70,000₹3,85,000Kharbi, Nagpur₹83,000off2014 Honda City1.5L I-DTEC VManual1,09,189 km1st OwnerDieselMH-27₹7,241/month ₹92,600 downpayment₹4,63,000₹5,46,000Kharbi, Nagpur₹49,000off2018 Maruti Alto 800LXIManual79,549 km2nd OwnerPetrolMH-32₹4,301/month ₹55,000 downpayment₹2,75,000₹3,24,000Kharbi, NagpurUsed cars in Nagpur by budgetbetween 2 to 5 lakhsbetween 5 to 10 lakhsunder 2 lakhsabove 10 lakhs₹5,000off2011 Maruti AltoLXIManual29,904 km2nd OwnerPetrolMH-31₹2,440/month ₹31,200 downpayment₹1,56,000₹1,61,000Kharbi, Nagpur₹25,000off2019 Hyundai CretaSX SPORTS EDITION 1.6 PETROLManual42,617 km1st OwnerPetrolMH-14₹16,933/month ₹2,22,400 downpayment₹11,12,000₹11,37,000Kharbi, Nagpur₹25,000off2019 Maruti New Wagon-RLXI CNG 1.0Manual52,297 km2nd OwnerCNGMH-01₹6,882/month ₹88,000 downpayment₹4,40,000₹4,65,000Kharbi, NagpurUsed cars in Nagpur by modelMaruti SwiftMaruti AltoHyundai i20Maruti Wagon RMaruti BalenoHyundai i10Maruti DzireHonda CityMaruti CelerioRenault KwidMaruti CiazHyundai SantroHonda JazzRenault DusterHonda AmazeFord EcosportHonda WR-VHyundai CretaTata TiagoMaruti Ritz₹48,000off2012 Maruti SwiftVXIManual1,00,685 km2nd OwnerPetrolMH-02₹4,520/month ₹57,800 downpayment₹2,89,000₹3,37,000Kharbi, Nagpur₹92,000off2019 Maruti SwiftVXIManual48,034 km1st OwnerPetrolMH-12₹8,540/month ₹1,09,200 downpayment₹5,46,000₹6,38,000Kharbi, Nagpur₹78,000off2012 Maruti SwiftZDIManual1,05,992 km1st OwnerDieselMH-04₹5,521/month ₹70,600 downpayment₹3,53,000₹4,31,000Kharbi, NagpurHomeUsed CarsNagpur45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions NagpurWhat are the most popular brands available for 2nd hand cars in Nagpur?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Nagpur of your choice on CARS24.What body types are available for 2nd hand cars in Nagpur?Used cars in Nagpur are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Nagpur?Of Course yes, you can buy used cars online in Nagpur from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in NagpurWhat to check before buying a second hand car in Nagpur?Important things to check  before buying a second hand car in Nagpur are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Nagpur?You can buy used cars in Nagpur from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Nagpur?You can check second hand cars in Nagpur using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in NagpurHow many second hand cars are available in Nagpur?138 used cars are available in Nagpur of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in NagpurUsed Hyundai Cars in NagpurUsed Honda Cars in NagpurUsed Renault Cars in NagpurUsed Ford Cars in NagpurUsed Nissan Cars in NagpurUsed Tata Cars in NagpurUsed Volkswagen Cars in NagpurUsed Toyota Cars in NagpurUsed Mahindra Cars in NagpurUsed Skoda Cars in NagpurUsed MG Cars in NagpurUsed KIA Cars in NagpurUsed Datsun Cars in NagpurBody :Used Hatchback Cars in NagpurUsed Sedan Cars in NagpurUsed SUV Cars in NagpurUsed Luxury Sedan Cars in NagpurUsed Luxury SUV Cars in NagpurFuel :Used Petrol Cars in NagpurUsed Diesel Cars in NagpurUsed CNG Cars in NagpurBudget :Used Cars between 2 to 5 lakhs in NagpurUsed Cars between 5 to 10 lakhs in NagpurUsed Cars under 2 lakhs in NagpurUsed Cars above 10 lakhs in NagpurModel :Used Maruti Swift Cars in NagpurUsed Maruti Alto Cars in NagpurUsed Hyundai i20 Cars in NagpurUsed Maruti Wagon R Cars in NagpurUsed Maruti Baleno Cars in NagpurUsed Hyundai i10 Cars in NagpurUsed Maruti Dzire Cars in NagpurUsed Honda City Cars in NagpurUsed Maruti Celerio Cars in NagpurUsed Renault Kwid Cars in NagpurUsed Maruti Ciaz Cars in NagpurUsed Hyundai Santro Cars in NagpurUsed Honda Jazz Cars in NagpurUsed Renault Duster Cars in NagpurUsed Honda Amaze Cars in NagpurUsed Ford Ecosport Cars in NagpurUsed Honda WR-V Cars in NagpurUsed Hyundai Creta Cars in NagpurUsed Tata Tiago Cars in NagpurUsed Maruti Ritz Cars in NagpurTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [125]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2011', '2018', '2012', '2018', '2017', '2012', '2017', '2010', '2019', '2015', '2014', '2014', '2014', '2018', '2011', '2019', '2019', '2012', '2019', '2012']
[[' Maruti', ' Swift'], [' Renault', ' Kwid'], [' Maruti', ' Alto', ' K10'], [' Renault', ' Kwid'], [' Volkswagen', ' Polo'], [' Honda', ' City'], [' Hyundai', ' i20', ' Active'], [' Hyundai', ' i10'], [' Mahindra', ' XUV', ' 3OO'], [' Maruti', ' Celerio'], [' Maruti', ' Swift', ' Dzire'], [' Maruti', ' Swift'], [' Honda', ' City'], [' Maruti', ' Alto', ' 800'], [' Maruti', ' Alto'], [' Hyundai', ' Creta'], [' Maruti', ' New', ' Wagon'], [' Maruti', ' Swift'], [' Maruti', ' Swift'], [' Maruti', ' Swift']]
['Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur', 'Kharbi, Nagpur']
[['87,743'], ['47,552'], ['96,133'], ['1,18', ',789'], ['49,118'], ['84,920'], ['88,140'], ['47,443'], ['84,242'], ['8,052'], ['78,872'], ['89,062'], ['1,09', ',189'], ['79,549'], ['29,904'], ['42,617'], ['52,297'], ['1,00', ',685'], ['48,034'], ['1,05', ',992']]
[['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], nan, ['Diesel'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], nan, ['Petrol'], ['Petrol'], ['Diesel']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['249000', '275000', '161000', '271000', '620000', '305000', '487000', '172000', '861000', '309000', '419000', '370000', '463000', '275000', '156000', '1112000', '440000', '289000', '546000', '353000']

In [126]:
dicto19 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [127]:
kmt1 = []
dicto19["Kmt run"]
for i in dicto19["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto19n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto19n

{'Name of Cars': [[' Maruti', ' Swift'],
  [' Renault', ' Kwid'],
  [' Maruti', ' Alto', ' K10'],
  [' Renault', ' Kwid'],
  [' Volkswagen', ' Polo'],
  [' Honda', ' City'],
  [' Hyundai', ' i20', ' Active'],
  [' Hyundai', ' i10'],
  [' Mahindra', ' XUV', ' 3OO'],
  [' Maruti', ' Celerio'],
  [' Maruti', ' Swift', ' Dzire'],
  [' Maruti', ' Swift'],
  [' Honda', ' City'],
  [' Maruti', ' Alto', ' 800'],
  [' Maruti', ' Alto'],
  [' Hyundai', ' Creta'],
  [' Maruti', ' New', ' Wagon'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Swift']],
 'Registration Year': ['2011',
  '2018',
  '2012',
  '2018',
  '2017',
  '2012',
  '2017',
  '2010',
  '2019',
  '2015',
  '2014',
  '2014',
  '2014',
  '2018',
  '2011',
  '2019',
  '2019',
  '2012',
  '2019',
  '2012'],
 'Kmt run': [87743,
  47552,
  96133,
  118789,
  49118,
  84920,
  88140,
  47443,
  84242,
  8052,
  78872,
  89062,
  109189,
  79549,
  29904,
  42617,
  52297,
  100685,
  48034,
  105992],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  nan,
  ['Diesel'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  nan,
  ['Petrol'],
  ['Petrol'],
  ['Diesel']],
 'Price': ['249000',
  '275000',
  '161000',
  '271000',
  '620000',
  '305000',
  '487000',
  '172000',
  '861000',
  '309000',
  '419000',
  '370000',
  '463000',
  '275000',
  '156000',
  '1112000',
  '440000',
  '289000',
  '546000',
  '353000'],
 'Location of car': ['Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur',
  'Kharbi, Nagpur']}

In [128]:
url20 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata%3AOR%3Amake%3A%3D%3Ahonda%3AOR%3Amake%3A%3D%3Arenault%3AOR%3Amake%3A%3D%3Atoyota%3AOR%3Amake%3A%3D%3Aford%3AOR%3Amake%3A%3D%3Amahindra%3AOR%3Amake%3A%3D%3Avolkswagen%3AOR%3Amake%3A%3D%3Adatsun%3AOR%3Amake%3A%3D%3Akia%3AOR%3Amake%3A%3D%3Anissan%3AOR%3Amake%3A%3D%3Ajeep%3AOR%3Amake%3A%3D%3Askoda&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=2598&pinId=422001"

In [129]:
new20 = req.get(url20)
new20

In [130]:
soup = BeautifulSoup(new20.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n89 Used Cars in Nashik - Second Hand Cars for Sale\n\n NashikBuy a carPopular makesMarutiHyundaiHondaRenaultFordVolkswagenSkodaDatsunMGNissanView all makesPopular ModelsMaruti Wagon RHyundai i20Renault KwidHyundai i10Maruti DzireMaruti BalenoFord EcosportMaruti SwiftMaruti CelerioMaruti AltoView all modelsBody typeHatchbackSedanSUVFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Wagon R 1.0 (12)Renault Kwid (6)Maruti Swift (5)Maruti Baleno (5)Ford Ecosport (5)Hyundai Grand i10 (4)ALL BRANDSMaruti (40)Hyundai (15)Honda (11)Renault (6)Ford (5)Volkswagen (4)Skoda (3)Datsun (2)Tata (1)Mahindra (1)MG (1)Nissan (1)KIA (0)BMW (0)Mercedes Benz (0)Audi (0)Jeep (0)Fiat (0)Toyota (0)Volvo (0)Jaguar (0)Budget₹ 2,00,000₹ 20,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear AllShow More 89 Used cars in NashikSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹10,000off2016 Tata TiagoXT PETROLManual51,816 km1st OwnerPetrolMH-01₹5,787/month ₹74,000 downpayment₹3,70,000₹3,80,000Adgaon, Nasik₹36,000off2012 Hyundai i20MAGNA (O) 1.2Manual44,933 km2nd OwnerPetrolMH-05₹4,020/month ₹51,400 downpayment₹2,57,000₹2,93,000Adgaon, NasikNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹22,000off2013 Volkswagen VentoHIGHLINE DIESEL 1.6Manual1,10,430 km2nd OwnerDieselMH-04₹4,332/month ₹55,400 downpayment₹2,77,000₹2,99,000Adgaon, Nasik₹44,000off2013 Honda Amaze1.2L I-VTEC SManual61,999 km2nd OwnerPetrolMH-01₹4,473/month ₹57,200 downpayment₹2,86,000₹3,30,000Adgaon, Nasik2019 Hyundai Elite i20SPORTZ PLUS 1.2Manual25,225 km1st OwnerPetrolMH-15₹11,855/month ₹1,51,600 downpayment₹7,58,000Adgaon, NasikUsed cars in Nashik by brandMarutiHyundaiHondaRenaultFordVolkswagenSkodaDatsunTataMGMahindraNissanToyota₹14,000off2014 Maruti CelerioZXI (O)Manual95,988 km1st OwnerPetrolMH-43₹5,568/month ₹71,200 downpayment₹3,56,000₹3,70,000Adgaon, Nasik₹40,000off2013 Honda BrioS MTManual35,781 km2nd OwnerPetrolMH-05₹3,754/month ₹48,000 downpayment₹2,40,000₹2,80,000Adgaon, Nasik₹10,000off2016 Renault KwidRXT 0.8Manual84,647 km1st OwnerPetrolMH-12₹3,801/month ₹48,600 downpayment₹2,43,000₹2,53,000Adgaon, NasikUsed cars in Nashik by body typeHatchbackSedanSUVLuxury SUV₹24,000off2012 Maruti Wagon R 1.0LXIManual80,563 km3rd OwnerPetrolMH-15₹3,738/month ₹47,800 downpayment₹2,39,000₹2,63,000Adgaon, Nasik₹10,000off2014 Ford EcosportTITANIUM 1.0L ECOBOOSTManual80,576 km1st OwnerPetrolMH-03₹7,116/month ₹91,000 downpayment₹4,55,000₹4,65,000Adgaon, Nasik₹78,000off2016 Hyundai Verna1.6 CRDI SXManual57,406 km2nd OwnerDieselMH-01₹10,354/month ₹1,32,400 downpayment₹6,62,000₹7,40,000Adgaon, NasikUsed cars in Nashik by fuel typePetrolDieselCNG₹66,500off2017 Maruti SwiftVXIManual79,070 km2nd OwnerPetrolMH-06₹6,983/month ₹89,300 downpayment₹4,46,500₹5,13,000Adgaon, Nasik₹41,000off2018 Maruti Wagon R 1.0LXI CNGManual92,055 km1st OwnerCNGMH-46₹5,990/month ₹76,600 downpayment₹3,83,000₹4,24,000Adgaon, Nasik₹34,000off2018 Mahindra TUV300T8Manual94,011 km2nd OwnerDieselMH-16₹11,417/month ₹1,46,000 downpayment₹7,30,000₹7,64,000Adgaon, NasikUsed cars in Nashik by budgetbetween 2 to 5 lakhsbetween 5 to 10 lakhsabove 10 lakhsunder 2 lakhs₹90,000off2018 Maruti DzireVDIManual57,457 km1st OwnerDieselMH-20₹10,760/month ₹1,37,600 downpayment₹6,88,000₹7,78,000Adgaon, Nasik₹54,000off2018 Maruti Wagon R 1.0LXI CNGManual78,901 km1st OwnerCNGMH-05₹6,100/month ₹78,000 downpayment₹3,90,000₹4,44,000Adgaon, Nasik₹41,000off2017 Skoda RapidSTYLE 1.6 MPIManual57,583 km1st OwnerPetrolMH-20₹10,870/month ₹1,39,000 downpayment₹6,95,000₹7,36,000Adgaon, NasikUsed cars in Nashik by modelMaruti Wagon RHyundai i20Renault KwidMaruti SwiftMaruti DzireFord EcosportMaruti BalenoHyundai i10Maruti CelerioHonda JazzHonda CityMaruti AltoVolkswagen VentoSkoda SLAVIADatsun Redi GoHonda AmazeVolkswagen PoloHonda BrioHonda WR-VMaruti Ciaz₹15,000off2017 Maruti DzireVXI AMTAutomatic88,651 km1st OwnerPetrolMH-02₹8,274/month ₹1,05,800 downpayment₹5,29,000₹5,44,000Adgaon, Nasik₹47,000off2017 Maruti Vitara BrezzaLDI (O)Manual62,590 km1st OwnerDieselMH-12₹11,167/month ₹1,42,800 downpayment₹7,14,000₹7,61,000Adgaon, Nasik₹5,000off2016 Maruti Alto 800LXIManual68,709 km1st OwnerPetrolMH-12₹4,520/month ₹57,800 downpayment₹2,89,000₹2,94,000Adgaon, NasikHomeUsed CarsNashik45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions NashikWhat are the most popular brands available for 2nd hand cars in Nashik?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Nashik of your choice on CARS24.What body types are available for 2nd hand cars in Nashik?Used cars in Nashik are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Nashik?Of Course yes, you can buy used cars online in Nashik from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in NashikWhat to check before buying a second hand car in Nashik?Important things to check  before buying a second hand car in Nashik are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Nashik?You can buy used cars in Nashik from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Nashik?You can check second hand cars in Nashik using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in NashikHow many second hand cars are available in Nashik?89 used cars are available in Nashik of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in NashikUsed Hyundai Cars in NashikUsed Honda Cars in NashikUsed Renault Cars in NashikUsed Ford Cars in NashikUsed Volkswagen Cars in NashikUsed Skoda Cars in NashikUsed Datsun Cars in NashikUsed Tata Cars in NashikUsed MG Cars in NashikUsed Mahindra Cars in NashikUsed Nissan Cars in NashikUsed Toyota Cars in NashikBody :Used Hatchback Cars in NashikUsed Sedan Cars in NashikUsed SUV Cars in NashikUsed Luxury SUV Cars in NashikFuel :Used Petrol Cars in NashikUsed Diesel Cars in NashikUsed CNG Cars in NashikBudget :Used Cars between 2 to 5 lakhs in NashikUsed Cars between 5 to 10 lakhs in NashikUsed Cars above 10 lakhs in NashikUsed Cars under 2 lakhs in NashikModel :Used Maruti Wagon R Cars in NashikUsed Hyundai i20 Cars in NashikUsed Renault Kwid Cars in NashikUsed Maruti Swift Cars in NashikUsed Maruti Dzire Cars in NashikUsed Ford Ecosport Cars in NashikUsed Maruti Baleno Cars in NashikUsed Hyundai i10 Cars in NashikUsed Maruti Celerio Cars in NashikUsed Honda Jazz Cars in NashikUsed Honda City Cars in NashikUsed Maruti Alto Cars in NashikUsed Volkswagen Vento Cars in NashikUsed Skoda SLAVIA Cars in NashikUsed Datsun Redi Go Cars in NashikUsed Honda Amaze Cars in NashikUsed Volkswagen Polo Cars in NashikUsed Honda Brio Cars in NashikUsed Honda WR-V Cars in NashikUsed Maruti Ciaz Cars in NashikTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [131]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2016', '2012', '2013', '2013', '2019', '2014', '2013', '2016', '2012', '2014', '2016', '2017', '2018', '2018', '2018', '2018', '2017', '2017', '2017', '2016']
[[' Tata', ' Tiago'], [' Hyundai', ' i20'], [' Volkswagen', ' Vento'], [' Honda', ' Amaze'], [' Hyundai', ' Elite', ' i20'], [' Maruti', ' Celerio'], [' Honda', ' Brio'], [' Renault', ' Kwid'], [' Maruti', ' Wagon', ' R', ' 1'], [' Ford', ' Ecosport'], [' Hyundai', ' Verna'], [' Maruti', ' Swift'], [' Maruti', ' Wagon', ' R', ' 1'], [' Mahindra', ' TUV300'], [' Maruti', ' Dzire'], [' Maruti', ' Wagon', ' R', ' 1'], [' Skoda', ' Rapid'], [' Maruti', ' Dzire'], [' Maruti', ' Vitara', ' Brezza'], [' Maruti', ' Alto', ' 800']]
['Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik', 'Adgaon, Nasik']
[['51,816'], ['44,933'], ['1,10', ',430'], ['61,999'], ['25,225'], ['95,988'], ['35,781'], ['84,647'], ['80,563'], ['80,576'], ['57,406'], ['79,070'], ['92,055'], ['94,011'], ['57,457'], ['78,901'], ['57,583'], ['88,651'], ['62,590'], ['68,709']]
[['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], nan, ['Diesel'], ['Diesel'], nan, ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual']]
['370000', '257000', '277000', '286000', '758000', '356000', '240000', '243000', '239000', '455000', '662000', '446500', '383000', '730000', '688000', '390000', '695000', '529000', '714000', '289000']

In [132]:
dicto20 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [133]:
kmt1 = []
dicto20["Kmt run"]
for i in dicto20["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto20n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto20n

{'Name of Cars': [[' Tata', ' Tiago'],
  [' Hyundai', ' i20'],
  [' Volkswagen', ' Vento'],
  [' Honda', ' Amaze'],
  [' Hyundai', ' Elite', ' i20'],
  [' Maruti', ' Celerio'],
  [' Honda', ' Brio'],
  [' Renault', ' Kwid'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Ford', ' Ecosport'],
  [' Hyundai', ' Verna'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Mahindra', ' TUV300'],
  [' Maruti', ' Dzire'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Skoda', ' Rapid'],
  [' Maruti', ' Dzire'],
  [' Maruti', ' Vitara', ' Brezza'],
  [' Maruti', ' Alto', ' 800']],
 'Registration Year': ['2016',
  '2012',
  '2013',
  '2013',
  '2019',
  '2014',
  '2013',
  '2016',
  '2012',
  '2014',
  '2016',
  '2017',
  '2018',
  '2018',
  '2018',
  '2018',
  '2017',
  '2017',
  '2017',
  '2016'],
 'Kmt run': [51816,
  44933,
  110430,
  61999,
  25225,
  95988,
  35781,
  84647,
  80563,
  80576,
  57406,
  79070,
  92055,
  94011,
  57457,
  78901,
  57583,
  88651,
  62590,
  68709],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  nan,
  ['Diesel'],
  ['Diesel'],
  nan,
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol']],
 'Price': ['370000',
  '257000',
  '277000',
  '286000',
  '758000',
  '356000',
  '240000',
  '243000',
  '239000',
  '455000',
  '662000',
  '446500',
  '383000',
  '730000',
  '688000',
  '390000',
  '695000',
  '529000',
  '714000',
  '289000'],
 'Location of car': ['Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik',
  'Adgaon, Nasik']}

In [134]:
url21 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata%3AOR%3Amake%3A%3D%3Ahonda%3AOR%3Amake%3A%3D%3Arenault%3AOR%3Amake%3A%3D%3Atoyota%3AOR%3Amake%3A%3D%3Aford%3AOR%3Amake%3A%3D%3Amahindra%3AOR%3Amake%3A%3D%3Avolkswagen%3AOR%3Amake%3A%3D%3Adatsun%3AOR%3Amake%3A%3D%3Akia%3AOR%3Amake%3A%3D%3Anissan%3AOR%3Amake%3A%3D%3Ajeep%3AOR%3Amake%3A%3D%3Askoda&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=8184&pinId=800001"

In [135]:
new21 = req.get(url21)
new21

In [136]:
soup = BeautifulSoup(new21.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n248 Used Cars in Patna - Second Hand Cars for Sale\n\n PatnaBuy a carPopular makesMarutiHyundaiHondaRenaultMahindraFordTataDatsunNissanKIAView all makesPopular ModelsMaruti DzireMaruti Wagon RMaruti AltoHyundai i10Hyundai i20Maruti SwiftMaruti BalenoHonda AmazeHyundai CretaMaruti CiazView all modelsBody typeHatchbackSUVSedanLuxury SUVFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Dzire (16)Hyundai Elite i20 (14)Maruti Swift (13)Maruti Wagon R 1.0 (13)Maruti Baleno (13)Hyundai Grand i10 (12)ALL BRANDSMaruti (116)Hyundai (58)Honda (19)Renault (13)Ford (8)Tata (8)Mahindra (8)Datsun (7)Nissan (5)KIA (2)Volkswagen (2)Skoda (1)Toyota (1)BMW (0)Mercedes Benz (0)Audi (0)Jeep (0)Fiat (0)MG (0)Volvo (0)Jaguar (0)Budget₹ 1,00,000₹ 20,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear AllShow More 248 Used cars in PatnaSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New2016 Maruti Swift DzireVXIManual54,557 km2nd OwnerPetrolBR-01₹7,695/month ₹98,400 downpayment₹4,92,000Atal Path, Patna₹1,02,000off2015 Mahindra ScorpioS10Manual56,337 km2nd OwnerDieselBR-06₹12,371/month ₹1,58,200 downpayment₹7,91,000₹8,93,000Atal Path, PatnaNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹1,18,000off2020 Mahindra BoleroB6 (O)Manual60,846 km1st OwnerDieselBR-53₹11,292/month ₹1,44,400 downpayment₹7,22,000₹8,40,000Atal Path, Patna₹65,000off2016 Honda BR-V1.5 i- DTEC VXManual1,05,137 km1st OwnerDieselBR-01₹9,040/month ₹1,15,600 downpayment₹5,78,000₹6,43,000Atal Path, Patna₹33,000off2011 Hyundai Santro XingGL PLUSManual94,852 km1st OwnerPetrolBR-01₹2,018/month ₹25,800 downpayment₹1,29,000₹1,62,000Atal Path, PatnaUsed cars in Patna by brandMarutiHyundaiHondaRenaultTataFordMahindraDatsunNissanKIAVolkswagenToyotaSkodaJeep₹34,000off2017 Tata TiagoXM PETROLManual80,310 km1st OwnerPetrolBR-01₹5,224/month ₹66,800 downpayment₹3,34,000₹3,68,000Patna\n₹67,000off2021 Nissan MAGNITEXV MTManual10,938 km2nd OwnerPetrolBR-06₹9,869/month ₹1,26,200 downpayment₹6,31,000₹6,98,000Atal Path, Patna₹47,000off2017 Mahindra XUV500W6Manual87,622 km1st OwnerDieselBR-01₹11,198/month ₹1,43,200 downpayment₹7,16,000₹7,63,000Patna\nUsed cars in Patna by body typeHatchbackSUVSedanLuxury SUVLuxury Sedan₹87,000off2020 Hyundai AURAS 1.2Manual24,220 km1st OwnerPetrolBR-01₹9,384/month ₹1,20,000 downpayment₹6,00,000₹6,87,000Patna\n₹75,000off2017 Maruti Vitara BrezzaVDIManual36,201 km2nd OwnerDieselBR-02₹8,915/month ₹1,14,000 downpayment₹5,70,000₹6,45,000Atal Path, Patna₹85,000off2019 Mahindra XUV 3OOW6 1.5 DIESELManual66,656 km1st OwnerDieselBR-03₹10,588/month ₹1,35,400 downpayment₹6,77,000₹7,62,000Atal Path, PatnaUsed cars in Patna by fuel typePetrolDieselCNG₹56,000off2021 Mahindra BOLERO NEON 8Manual29,942 km2nd OwnerDieselBR-31₹13,598/month ₹1,78,600 downpayment₹8,93,000₹9,49,000Atal Path, Patna₹34,000off2014 Hyundai Grand i10SPORTZ 1.2 KAPPA VTVTManual75,368 km1st OwnerPetrolBR-06₹4,802/month ₹61,400 downpayment₹3,07,000₹3,41,000Patna\n₹87,000off2021 Nissan MAGNITEXEManual16,088 km1st OwnerPetrolBR-02₹8,258/month ₹1,05,600 downpayment₹5,28,000₹6,15,000Patna\nUsed cars in Patna by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsunder 2 lakhsabove 10 lakhs₹50,000off2021 Maruti DzireVXIManual42,156 km1st OwnerPetrolBR-01₹10,369/month ₹1,32,600 downpayment₹6,63,000₹7,13,000Atal Path, Patna₹8,400off2011 Maruti Alto K10VXIManual43,340 km1st OwnerPetrolBR-01₹2,684/month ₹34,320 downpayment₹1,71,600₹1,80,000Patna\n₹56,000off2015 Hyundai i20 Active1.2 SManual20,231 km2nd OwnerPetrolBR-01₹7,132/month ₹91,200 downpayment₹4,56,000₹5,12,000Atal Path, PatnaUsed cars in Patna by modelMaruti DzireMaruti Wagon RMaruti AltoHyundai i10Hyundai i20Maruti BalenoMaruti SwiftHonda AmazeFord EcosportHyundai CretaMaruti CiazMaruti BrezzaHyundai SantroRenault TRIBERRenault KwidMaruti IGNISNissan MAGNITEHyundai VENUEHonda CityHyundai Eon₹82,000off2018 Maruti SwiftZXI PLUSManual62,515 km1st OwnerPetrolBR-01₹8,602/month ₹1,10,000 downpayment₹5,50,000₹6,32,000Atal Path, Patna₹72,000off2017 Honda City1.5L I-VTEC V MTManual45,271 km1st OwnerPetrolBR-01₹9,931/month ₹1,27,000 downpayment₹6,35,000₹7,07,000Patna\n₹77,000off2018 Maruti SwiftZXI AMTAutomatic28,815 km2nd OwnerPetrolBR-01₹8,008/month ₹1,02,400 downpayment₹5,12,000₹5,89,000Patna\nHomeUsed CarsPatna45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions PatnaWhat are the most popular brands available for 2nd hand cars in Patna?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Patna of your choice on CARS24.What body types are available for 2nd hand cars in Patna?Used cars in Patna are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Patna?Of Course yes, you can buy used cars online in Patna from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in PatnaWhat to check before buying a second hand car in Patna?Important things to check  before buying a second hand car in Patna are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Patna?You can buy used cars in Patna from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Patna?You can check second hand cars in Patna using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in PatnaHow many second hand cars are available in Patna?248 used cars are available in Patna of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in PatnaUsed Hyundai Cars in PatnaUsed Honda Cars in PatnaUsed Renault Cars in PatnaUsed Tata Cars in PatnaUsed Ford Cars in PatnaUsed Mahindra Cars in PatnaUsed Datsun Cars in PatnaUsed Nissan Cars in PatnaUsed KIA Cars in PatnaUsed Volkswagen Cars in PatnaUsed Toyota Cars in PatnaUsed Skoda Cars in PatnaUsed Jeep Cars in PatnaBody :Used Hatchback Cars in PatnaUsed SUV Cars in PatnaUsed Sedan Cars in PatnaUsed Luxury SUV Cars in PatnaUsed Luxury Sedan Cars in PatnaFuel :Used Petrol Cars in PatnaUsed Diesel Cars in PatnaUsed CNG Cars in PatnaBudget :Used Cars between 5 to 10 lakhs in PatnaUsed Cars between 2 to 5 lakhs in PatnaUsed Cars under 2 lakhs in PatnaUsed Cars above 10 lakhs in PatnaModel :Used Maruti Dzire Cars in PatnaUsed Maruti Wagon R Cars in PatnaUsed Maruti Alto Cars in PatnaUsed Hyundai i10 Cars in PatnaUsed Hyundai i20 Cars in PatnaUsed Maruti Baleno Cars in PatnaUsed Maruti Swift Cars in PatnaUsed Honda Amaze Cars in PatnaUsed Ford Ecosport Cars in PatnaUsed Hyundai Creta Cars in PatnaUsed Maruti Ciaz Cars in PatnaUsed Maruti Brezza Cars in PatnaUsed Hyundai Santro Cars in PatnaUsed Renault TRIBER Cars in PatnaUsed Renault Kwid Cars in PatnaUsed Maruti IGNIS Cars in PatnaUsed Nissan MAGNITE Cars in PatnaUsed Hyundai VENUE Cars in PatnaUsed Honda City Cars in PatnaUsed Hyundai Eon Cars in PatnaTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [137]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2016', '2015', '2020', '2016', '2011', '2017', '2021', '2017', '2020', '2017', '2019', '2021', '2014', '2021', '2021', '2011', '2015', '2018', '2017', '2018']
[[' Maruti', ' Swift', ' Dzire'], [' Mahindra', ' Scorpio'], [' Mahindra', ' Bolero'], [' Honda', ' BR'], [' Hyundai', ' Santro', ' Xing'], [' Tata', ' Tiago'], [' Nissan', ' MAGNITE'], [' Mahindra', ' XUV500'], [' Hyundai', ' AURA'], [' Maruti', ' Vitara', ' Brezza'], [' Mahindra', ' XUV', ' 3OO'], [' Mahindra', ' BOLERO', ' NEO'], [' Hyundai', ' Grand', ' i10'], [' Nissan', ' MAGNITE'], [' Maruti', ' Dzire'], [' Maruti', ' Alto', ' K10'], [' Hyundai', ' i20', ' Active'], [' Maruti', ' Swift'], [' Honda', ' City'], [' Maruti', ' Swift']]
['Atal Path, Patna', 'Atal Path, Patna', 'Atal Path, Patna', 'Atal Path, Patna', 'Atal Path, Patna', 'Patna\n', 'Atal Path, Patna', 'Patna\n', 'Patna\n', 'Atal Path, Patna', 'Atal Path, Patna', 'Atal Path, Patna', 'Patna\n', 'Patna\n', 'Atal Path, Patna', 'Patna\n', 'Atal Path, Patna', 'Atal Path, Patna', 'Patna\n', 'Patna\n']
[['54,557'], ['56,337'], ['60,846'], ['1,05', ',137'], ['94,852'], ['80,310'], ['10,938'], ['87,622'], ['24,220'], ['36,201'], ['66,656'], ['29,942'], ['75,368'], ['16,088'], ['42,156'], ['43,340'], ['20,231'], ['62,515'], ['45,271'], ['28,815']]
[['Petrol'], ['Diesel'], ['Diesel'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Diesel'], ['Diesel'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic']]
['492000', '791000', '722000', '578000', '129000', '334000', '631000', '716000', '600000', '570000', '677000', '893000', '307000', '528000', '663000', '171600', '456000', '550000', '635000', '512000']

In [138]:
dicto21 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [139]:
kmt1 = []
dicto21["Kmt run"]
for i in dicto21["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto21n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto21n

{'Name of Cars': [[' Maruti', ' Swift', ' Dzire'],
  [' Mahindra', ' Scorpio'],
  [' Mahindra', ' Bolero'],
  [' Honda', ' BR'],
  [' Hyundai', ' Santro', ' Xing'],
  [' Tata', ' Tiago'],
  [' Nissan', ' MAGNITE'],
  [' Mahindra', ' XUV500'],
  [' Hyundai', ' AURA'],
  [' Maruti', ' Vitara', ' Brezza'],
  [' Mahindra', ' XUV', ' 3OO'],
  [' Mahindra', ' BOLERO', ' NEO'],
  [' Hyundai', ' Grand', ' i10'],
  [' Nissan', ' MAGNITE'],
  [' Maruti', ' Dzire'],
  [' Maruti', ' Alto', ' K10'],
  [' Hyundai', ' i20', ' Active'],
  [' Maruti', ' Swift'],
  [' Honda', ' City'],
  [' Maruti', ' Swift']],
 'Registration Year': ['2016',
  '2015',
  '2020',
  '2016',
  '2011',
  '2017',
  '2021',
  '2017',
  '2020',
  '2017',
  '2019',
  '2021',
  '2014',
  '2021',
  '2021',
  '2011',
  '2015',
  '2018',
  '2017',
  '2018'],
 'Kmt run': [54557,
  56337,
  60846,
  105137,
  94852,
  80310,
  10938,
  87622,
  24220,
  36201,
  66656,
  29942,
  75368,
  16088,
  42156,
  43340,
  20231,
  62515,
  45271,
  28815],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic']],
 'Fuel type': [['Petrol'],
  ['Diesel'],
  ['Diesel'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Diesel'],
  ['Diesel'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['492000',
  '791000',
  '722000',
  '578000',
  '129000',
  '334000',
  '631000',
  '716000',
  '600000',
  '570000',
  '677000',
  '893000',
  '307000',
  '528000',
  '663000',
  '171600',
  '456000',
  '550000',
  '635000',
  '512000'],
 'Location of car': ['Atal Path, Patna',
  'Atal Path, Patna',
  'Atal Path, Patna',
  'Atal Path, Patna',
  'Atal Path, Patna',
  'Patna\n',
  'Atal Path, Patna',
  'Patna\n',
  'Patna\n',
  'Atal Path, Patna',
  'Atal Path, Patna',
  'Atal Path, Patna',
  'Patna\n',
  'Patna\n',
  'Atal Path, Patna',
  'Patna\n',
  'Atal Path, Patna',
  'Atal Path, Patna',
  'Patna\n',
  'Patna\n']}

In [140]:
url22 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata%3AOR%3Amake%3A%3D%3Ahonda%3AOR%3Amake%3A%3D%3Arenault%3AOR%3Amake%3A%3D%3Atoyota%3AOR%3Amake%3A%3D%3Aford%3AOR%3Amake%3A%3D%3Amahindra%3AOR%3Amake%3A%3D%3Avolkswagen%3AOR%3Amake%3A%3D%3Adatsun%3AOR%3Amake%3A%3D%3Akia%3AOR%3Amake%3A%3D%3Anissan%3AOR%3Amake%3A%3D%3Ajeep%3AOR%3Amake%3A%3D%3Askoda&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=666&pinId=141001"

In [141]:
new22 = req.get(url22)
new22

In [142]:
soup = BeautifulSoup(new22.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n300 Used Cars in Ludhiana - Second Hand Cars for Sale\n\n LudhianaBuy a carPopular makesMarutiHyundaiToyotaMahindraFordHondaNissanTataDatsunView all makesPopular ModelsMaruti AltoMaruti DzireHyundai i20Maruti SwiftMaruti BalenoMaruti Wagon RMaruti S PRESSOHyundai VENUEMaruti CiazFord EcosportView all modelsBody typeHatchbackSedanSUVFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Swift (21)Maruti Alto K10 (20)Maruti Vitara Brezza (17)Maruti Baleno (15)Hyundai Grand i10 (11)Hyundai NEW SANTRO (10)ALL BRANDSMaruti (140)Hyundai (68)Honda (24)Tata (14)Renault (11)Mahindra (10)Toyota (9)Ford (8)Nissan (4)Volkswagen (4)KIA (3)Datsun (2)Skoda (2)Jeep (1)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)MG (0)Volvo (0)Jaguar (0)Budget₹ 1,50,000₹ 25,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear AllShow More 300 Used cars in LudhianaSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹10,000off2010 Hyundai i10MAGNA 1.2Manual80,727 km1st OwnerPetrolCH-01₹2,659/month ₹34,000 downpayment₹1,70,000₹1,80,000Paras Downtown Square, Chandigarh₹41,000off2019 Hyundai VENUES 1.2Manual42,118 km1st OwnerPetrolPB-10₹11,089/month ₹1,41,800 downpayment₹7,09,000₹7,50,000Wave Mall, LudhianaNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility 2019 Maruti SwiftLXIManual1,06,184 km1st OwnerPetrolCH-01₹8,508/month ₹1,08,800 downpayment₹5,44,000Paras Downtown Square, Chandigarh₹37,000off2015 Honda City1.5L I-VTEC V MTManual96,379 km2nd OwnerPetrolCH-01₹7,711/month ₹98,600 downpayment₹4,93,000₹5,30,000Paras Downtown Square, Chandigarh₹32,000off2022 Tata TIGORXZ CNGManual44,564 km1st OwnerCNGPB-87₹12,197/month ₹1,60,200 downpayment₹8,01,000₹8,33,000Paras Downtown Square, ChandigarhUsed cars in Ludhiana by brandMarutiHyundaiFordMahindraToyotaHondaDatsunNissanTataSkodaMercedes BenzKIAMGRenaultVolkswagen2021 Hyundai GRAND I10 NIOSMAGNA 1.2 KAPPA VTVTManual27,381 km2nd OwnerPetrolPB-18₹9,494/month ₹1,21,400 downpayment₹6,07,000Paras Downtown Square, Chandigarh2019 Volkswagen AmeoTRENDLINE 1.0LManual48,295 km1st OwnerPetrolPB-02₹7,804/month ₹99,800 downpayment₹4,99,000Paras Downtown Square, Chandigarh₹42,000off2018 Honda Amaze1.2L I-VTEC SManual31,904 km1st OwnerPetrolPB-08₹8,680/month ₹1,11,000 downpayment₹5,55,000₹5,97,000Paras Downtown Square, ChandigarhUsed cars in Ludhiana by body typeHatchbackSedanSUVLuxury SUVLuxury Sedan2017 Datsun Go PlusTManual57,422 km1st OwnerPetrolCH-01₹4,567/month ₹58,400 downpayment₹2,92,000Paras Downtown Square, Chandigarh₹40,000off2014 Mahindra XUV500W8Manual89,077 km1st OwnerDieselHR-03₹8,461/month ₹1,08,200 downpayment₹5,41,000₹5,81,000Paras Downtown Square, Chandigarh₹70,000off2014 Maruti SwiftVDIManual78,352 km2nd OwnerDieselHR-29₹5,161/month ₹66,000 downpayment₹3,30,000₹4,00,000Paras Downtown Square, ChandigarhUsed cars in Ludhiana by fuel typePetrolDieselCNG₹88,000off2019 Maruti AltoLXIManual27,760 km1st OwnerPetrolHR-19₹4,411/month ₹56,400 downpayment₹2,82,000₹3,70,000Paras Downtown Square, Chandigarh₹1,01,000off2020 Volkswagen PoloTRENDLINE 1.0LManual45,550 km1st OwnerPetrolHR-02₹7,726/month ₹98,800 downpayment₹4,94,000₹5,95,000Paras Downtown Square, Chandigarh₹82,000off2015 Maruti BalenoDELTA DIESEL 1.3Manual52,311 km1st OwnerDieselHR-51₹5,709/month ₹73,000 downpayment₹3,65,000₹4,47,000Paras Downtown Square, ChandigarhUsed cars in Ludhiana by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhsunder 2 lakhs₹40,000off2015 Maruti Alto K10VXIManual46,785 km2nd OwnerPetrolPB-09₹3,691/month ₹47,200 downpayment₹2,36,000₹2,76,000Paras Downtown Square, Chandigarh2022 Maruti AltoVXIManual14,180 km1st OwnerPetrolHR-71₹6,225/month ₹79,600 downpayment₹3,98,000Paras Downtown Square, Chandigarh₹29,000off2013 Maruti SwiftVDIManual90,533 km2nd OwnerDieselHR-29₹4,583/month ₹58,600 downpayment₹2,93,000₹3,22,000Paras Downtown Square, ChandigarhUsed cars in Ludhiana by modelMaruti AltoHyundai i20Maruti DzireMaruti SwiftMaruti BalenoHyundai VernaMaruti S PRESSOHyundai SantroMaruti IGNISFord EcosportHyundai VENUEMaruti BrezzaMaruti CelerioMaruti Wagon RMaruti CiazHonda JazzDatsun Redi GoToyota YARISTata HarrierToyota Glanza₹75,000off2016 Toyota EtiosCROSS 1.4 VDManual74,075 km2nd OwnerDieselHR-29₹6,209/month ₹79,400 downpayment₹3,97,000₹4,72,000Paras Downtown Square, Chandigarh₹50,000off2013 Maruti SwiftVDIManual85,724 km3rd OwnerDieselHR-19₹4,833/month ₹61,800 downpayment₹3,09,000₹3,59,000Paras Downtown Square, Chandigarh₹31,000off2010 Maruti SwiftVXIManual92,322 km1st OwnerPetrolHR-03₹3,425/month ₹43,800 downpayment₹2,19,000₹2,50,000Paras Downtown Square, ChandigarhHomeUsed CarsLudhiana45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions LudhianaWhat are the most popular brands available for 2nd hand cars in Ludhiana?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Ludhiana of your choice on CARS24.What body types are available for 2nd hand cars in Ludhiana?Used cars in Ludhiana are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Ludhiana?Of Course yes, you can buy used cars online in Ludhiana from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in LudhianaWhat to check before buying a second hand car in Ludhiana?Important things to check  before buying a second hand car in Ludhiana are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Ludhiana?You can buy used cars in Ludhiana from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Ludhiana?You can check second hand cars in Ludhiana using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in LudhianaHow many second hand cars are available in Ludhiana?300 used cars are available in Ludhiana of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in LudhianaUsed Hyundai Cars in LudhianaUsed Ford Cars in LudhianaUsed Mahindra Cars in LudhianaUsed Toyota Cars in LudhianaUsed Honda Cars in LudhianaUsed Datsun Cars in LudhianaUsed Nissan Cars in LudhianaUsed Tata Cars in LudhianaUsed Skoda Cars in LudhianaUsed Mercedes Benz Cars in LudhianaUsed KIA Cars in LudhianaUsed MG Cars in LudhianaUsed Renault Cars in LudhianaUsed Volkswagen Cars in LudhianaBody :Used Hatchback Cars in LudhianaUsed Sedan Cars in LudhianaUsed SUV Cars in LudhianaUsed Luxury SUV Cars in LudhianaUsed Luxury Sedan Cars in LudhianaFuel :Used Petrol Cars in LudhianaUsed Diesel Cars in LudhianaUsed CNG Cars in LudhianaBudget :Used Cars between 5 to 10 lakhs in LudhianaUsed Cars between 2 to 5 lakhs in LudhianaUsed Cars above 10 lakhs in LudhianaUsed Cars under 2 lakhs in LudhianaModel :Used Maruti Alto Cars in LudhianaUsed Hyundai i20 Cars in LudhianaUsed Maruti Dzire Cars in LudhianaUsed Maruti Swift Cars in LudhianaUsed Maruti Baleno Cars in LudhianaUsed Hyundai Verna Cars in LudhianaUsed Maruti S PRESSO Cars in LudhianaUsed Hyundai Santro Cars in LudhianaUsed Maruti IGNIS Cars in LudhianaUsed Ford Ecosport Cars in LudhianaUsed Hyundai VENUE Cars in LudhianaUsed Maruti Brezza Cars in LudhianaUsed Maruti Celerio Cars in LudhianaUsed Maruti Wagon R Cars in LudhianaUsed Maruti Ciaz Cars in LudhianaUsed Honda Jazz Cars in LudhianaUsed Datsun Redi Go Cars in LudhianaUsed Toyota YARIS Cars in LudhianaUsed Tata Harrier Cars in LudhianaUsed Toyota Glanza Cars in LudhianaTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [143]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2010', '2019', '2019', '2015', '2022', '2021', '2019', '2018', '2017', '2014', '2014', '2019', '2020', '2015', '2015', '2022', '2013', '2016', '2013', '2010']
[[' Hyundai', ' i10'], [' Hyundai', ' VENUE'], [' Maruti', ' Swift'], [' Honda', ' City'], [' Tata', ' TIGOR'], [' Hyundai', ' GRAND', ' I10', ' NIOS'], [' Volkswagen', ' Ameo'], [' Honda', ' Amaze'], [' Datsun', ' Go', ' Plus'], [' Mahindra', ' XUV500'], [' Maruti', ' Swift'], [' Maruti', ' Alto'], [' Volkswagen', ' Polo'], [' Maruti', ' Baleno'], [' Maruti', ' Alto', ' K10'], [' Maruti', ' Alto'], [' Maruti', ' Swift'], [' Toyota', ' Etios'], [' Maruti', ' Swift'], [' Maruti', ' Swift']]
['Paras Downtown Square, Chandigarh', 'Wave Mall, Ludhiana', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh', 'Paras Downtown Square, Chandigarh']
[['80,727'], ['42,118'], ['1,06', ',184'], ['96,379'], ['44,564'], ['27,381'], ['48,295'], ['31,904'], ['57,422'], ['89,077'], ['78,352'], ['27,760'], ['45,550'], ['52,311'], ['46,785'], ['14,180'], ['90,533'], ['74,075'], ['85,724'], ['92,322']]
[['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], nan, ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Diesel'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Diesel'], ['Diesel'], ['Diesel'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['170000', '709000', '544000', '493000', '801000', '607000', '499000', '555000', '292000', '541000', '330000', '282000', '494000', '365000', '236000', '398000', '293000', '397000', '309000', '219000']

In [144]:
dicto22 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [145]:
kmt1 = []
dicto22["Kmt run"]
for i in dicto22["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto22n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto22n

{'Name of Cars': [[' Hyundai', ' i10'],
  [' Hyundai', ' VENUE'],
  [' Maruti', ' Swift'],
  [' Honda', ' City'],
  [' Tata', ' TIGOR'],
  [' Hyundai', ' GRAND', ' I10', ' NIOS'],
  [' Volkswagen', ' Ameo'],
  [' Honda', ' Amaze'],
  [' Datsun', ' Go', ' Plus'],
  [' Mahindra', ' XUV500'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Alto'],
  [' Volkswagen', ' Polo'],
  [' Maruti', ' Baleno'],
  [' Maruti', ' Alto', ' K10'],
  [' Maruti', ' Alto'],
  [' Maruti', ' Swift'],
  [' Toyota', ' Etios'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Swift']],
 'Registration Year': ['2010',
  '2019',
  '2019',
  '2015',
  '2022',
  '2021',
  '2019',
  '2018',
  '2017',
  '2014',
  '2014',
  '2019',
  '2020',
  '2015',
  '2015',
  '2022',
  '2013',
  '2016',
  '2013',
  '2010'],
 'Kmt run': [80727,
  42118,
  106184,
  96379,
  44564,
  27381,
  48295,
  31904,
  57422,
  89077,
  78352,
  27760,
  45550,
  52311,
  46785,
  14180,
  90533,
  74075,
  85724,
  92322],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  nan,
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Diesel'],
  ['Diesel'],
  ['Petrol']],
 'Price': ['170000',
  '709000',
  '544000',
  '493000',
  '801000',
  '607000',
  '499000',
  '555000',
  '292000',
  '541000',
  '330000',
  '282000',
  '494000',
  '365000',
  '236000',
  '398000',
  '293000',
  '397000',
  '309000',
  '219000'],
 'Location of car': ['Paras Downtown Square, Chandigarh',
  'Wave Mall, Ludhiana',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh',
  'Paras Downtown Square, Chandigarh']}

In [146]:
url23 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata%3AOR%3Amake%3A%3D%3Ahonda%3AOR%3Amake%3A%3D%3Arenault%3AOR%3Amake%3A%3D%3Atoyota%3AOR%3Amake%3A%3D%3Aford%3AOR%3Amake%3A%3D%3Amahindra%3AOR%3Amake%3A%3D%3Avolkswagen%3AOR%3Amake%3A%3D%3Adatsun%3AOR%3Amake%3A%3D%3Akia%3AOR%3Amake%3A%3D%3Anissan%3AOR%3Amake%3A%3D%3Ajeep%3AOR%3Amake%3A%3D%3Askoda&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=1674&pinId=390001"

In [147]:
new23 = req.get(url23)
new23

In [148]:
soup = BeautifulSoup(new23.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n106 Used Cars in Vadodara - Second Hand Cars for Sale\n\n VadodaraBuy a carPopular makesMarutiHyundaiTataHondaMGMahindraFordVolkswagenRenaultKIAView all makesPopular ModelsMaruti SwiftHyundai i10Maruti BalenoMaruti AltoMaruti Wagon RHyundai i20Hyundai CretaMG HECTORHyundai SantroHonda CityView all modelsBody typeHatchbackSUVSedanLuxury SUVFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Swift (15)Maruti Baleno (9)Hyundai Grand i10 (8)Maruti Alto 800 (6)Maruti Wagon R 1.0 (4)Hyundai Creta (4)ALL BRANDSMaruti (47)Hyundai (26)Tata (11)Honda (7)MG (4)Ford (3)Renault (3)Mahindra (3)Volkswagen (3)KIA (1)Skoda (1)Jeep (1)Datsun (0)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)Toyota (0)Nissan (0)Volvo (0)Jaguar (0)Budget₹ 1,50,000₹ 20,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear AllShow More 106 Used cars in VadodaraSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹26,000off2018 Tata TIGORXT PETROLManual54,479 km1st OwnerPetrolGJ-11₹6,882/month ₹88,000 downpayment₹4,40,000₹4,66,000New Sama, Vadodara₹23,000off2014 Maruti ErtigaZXIManual78,651 km1st OwnerPetrolGJ-07₹9,024/month ₹1,15,400 downpayment₹5,77,000₹6,00,000New Sama, VadodaraNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹85,000off2019 Renault KwidRXT 1.0 AMT (O)Automatic67,081 km1st OwnerPetrolGJ-05₹5,193/month ₹66,400 downpayment₹3,32,000₹4,17,000New Sama, Vadodara2011 Maruti AltoLXIManual82,340 km1st OwnerCNGGJ-06₹2,659/month ₹34,000 downpayment₹1,70,000New Sama, Vadodara2012 Maruti Wagon R 1.0LXIManual1,12,434 km1st OwnerCNGGJ-06₹4,176/month ₹53,400 downpayment₹2,67,000New Sama, VadodaraUsed cars in Vadodara by brandMarutiHyundaiTataHondaMGMahindraRenaultVolkswagenFordJeepSkodaKIANissanToyotaDatsun₹99,000off2014 Honda CityV MT PETROLManual76,800 km2nd OwnerCNGGJ-26₹7,820/month ₹1,00,000 downpayment₹5,00,000₹5,99,000New Sama, Vadodara₹51,000off2018 Maruti CiazDELTA 1.5 SHVS MT PETROLManual63,911 km2nd OwnerPetrolGJ-06₹11,668/month ₹1,49,200 downpayment₹7,46,000₹7,97,000New Sama, Vadodara₹65,000off2017 Hyundai Verna1.6 SX (O) CRDI MTManual56,700 km2nd OwnerDieselGJ-01₹12,471/month ₹1,63,800 downpayment₹8,19,000₹8,84,000New Sama, VadodaraUsed cars in Vadodara by body typeHatchbackSUVSedanLuxury SUVLuxury Sedan₹13,000off2014 Honda City1.5L I-DTEC SVManual97,177 km1st OwnerDieselGJ-06₹7,585/month ₹97,000 downpayment₹4,85,000₹4,98,000New Sama, Vadodara₹5,000off2015 Maruti SwiftVDI ABSManual96,797 km3rd OwnerDieselGJ-06₹6,428/month ₹82,200 downpayment₹4,11,000₹4,16,000New Sama, Vadodara2013 Maruti Alto 800LXIManual88,798 km2nd OwnerPetrolGJ-23₹3,097/month ₹39,600 downpayment₹1,98,000New Sama, VadodaraUsed cars in Vadodara by fuel typePetrolCNGDiesel2014 Volkswagen PoloCOMFORTLINE 1.2LManual86,874 km2nd OwnerPetrolGJ-06₹5,732/month ₹73,300 downpayment₹3,66,500New Sama, Vadodara2022 Maruti S PRESSOVXI (O) CNGManual13,864 km1st OwnerCNGGJ-06₹8,962/month ₹1,14,600 downpayment₹5,73,000New Sama, Vadodara₹51,000off2021 Maruti SwiftVXIManual23,941 km1st OwnerPetrolGJ-06₹10,526/month ₹1,34,600 downpayment₹6,73,000₹7,24,000New Sama, VadodaraUsed cars in Vadodara by budgetbetween 2 to 5 lakhsbetween 5 to 10 lakhsabove 10 lakhsunder 2 lakhs₹39,000off2020 Hyundai CretaEX 1.5 PETROLManual43,008 km1st OwnerPetrolGJ-06₹16,019/month ₹2,10,400 downpayment₹10,52,000₹10,91,000New Sama, Vadodara₹6,000off2010 Hyundai i10SPORTZ 1.2Manual85,320 km2nd OwnerPetrolGJ-06₹3,425/month ₹43,800 downpayment₹2,19,000₹2,25,000New Sama, Vadodara₹41,000off2017 Mahindra XUV500W10 ATAutomatic91,086 km2nd OwnerDieselGJ-01₹14,953/month ₹1,96,400 downpayment₹9,82,000₹10,23,000New Sama, VadodaraUsed cars in Vadodara by modelMaruti SwiftHyundai i10Maruti BalenoMaruti AltoHyundai i20Maruti Wagon RMG HECTORHyundai CretaTata TiagoMaruti S PRESSOHyundai XcentVolkswagen PoloHonda CityTata NEXONHyundai SantroTata TIGORRenault KwidHonda WR-VFord EcosportMaruti IGNIS₹11,000off2018 Maruti DzireVXI AMTAutomatic88,193 km1st OwnerPetrolGJ-06₹8,899/month ₹1,13,800 downpayment₹5,69,000₹5,80,000New Sama, Vadodara₹13,000off2013 Maruti SwiftLXIManual80,384 km1st OwnerCNGGJ-06₹5,865/month ₹75,000 downpayment₹3,75,000₹3,88,000New Sama, Vadodara₹7,000off2014 Maruti SwiftVXIManual80,580 km2nd OwnerPetrolGJ-06₹6,350/month ₹81,200 downpayment₹4,06,000₹4,13,000New Sama, VadodaraHomeUsed CarsVadodara45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions VadodaraWhat are the most popular brands available for 2nd hand cars in Vadodara?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Vadodara of your choice on CARS24.What body types are available for 2nd hand cars in Vadodara?Used cars in Vadodara are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Vadodara?Of Course yes, you can buy used cars online in Vadodara from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in VadodaraWhat to check before buying a second hand car in Vadodara?Important things to check  before buying a second hand car in Vadodara are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Vadodara?You can buy used cars in Vadodara from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Vadodara?You can check second hand cars in Vadodara using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in VadodaraHow many second hand cars are available in Vadodara?106 used cars are available in Vadodara of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in VadodaraUsed Hyundai Cars in VadodaraUsed Tata Cars in VadodaraUsed Honda Cars in VadodaraUsed MG Cars in VadodaraUsed Mahindra Cars in VadodaraUsed Renault Cars in VadodaraUsed Volkswagen Cars in VadodaraUsed Ford Cars in VadodaraUsed Jeep Cars in VadodaraUsed Skoda Cars in VadodaraUsed KIA Cars in VadodaraUsed Nissan Cars in VadodaraUsed Toyota Cars in VadodaraUsed Datsun Cars in VadodaraBody :Used Hatchback Cars in VadodaraUsed SUV Cars in VadodaraUsed Sedan Cars in VadodaraUsed Luxury SUV Cars in VadodaraUsed Luxury Sedan Cars in VadodaraFuel :Used Petrol Cars in VadodaraUsed CNG Cars in VadodaraUsed Diesel Cars in VadodaraBudget :Used Cars between 2 to 5 lakhs in VadodaraUsed Cars between 5 to 10 lakhs in VadodaraUsed Cars above 10 lakhs in VadodaraUsed Cars under 2 lakhs in VadodaraModel :Used Maruti Swift Cars in VadodaraUsed Hyundai i10 Cars in VadodaraUsed Maruti Baleno Cars in VadodaraUsed Maruti Alto Cars in VadodaraUsed Hyundai i20 Cars in VadodaraUsed Maruti Wagon R Cars in VadodaraUsed MG HECTOR Cars in VadodaraUsed Hyundai Creta Cars in VadodaraUsed Tata Tiago Cars in VadodaraUsed Maruti S PRESSO Cars in VadodaraUsed Hyundai Xcent Cars in VadodaraUsed Volkswagen Polo Cars in VadodaraUsed Honda City Cars in VadodaraUsed Tata NEXON Cars in VadodaraUsed Hyundai Santro Cars in VadodaraUsed Tata TIGOR Cars in VadodaraUsed Renault Kwid Cars in VadodaraUsed Honda WR-V Cars in VadodaraUsed Ford Ecosport Cars in VadodaraUsed Maruti IGNIS Cars in VadodaraTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [149]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2018', '2014', '2019', '2011', '2012', '2014', '2018', '2017', '2014', '2015', '2013', '2014', '2022', '2021', '2020', '2010', '2017', '2018', '2013', '2014']
[[' Tata', ' TIGOR'], [' Maruti', ' Ertiga'], [' Renault', ' Kwid'], [' Maruti', ' Alto'], [' Maruti', ' Wagon', ' R', ' 1'], [' Honda', ' City'], [' Maruti', ' Ciaz'], [' Hyundai', ' Verna'], [' Honda', ' City'], [' Maruti', ' Swift'], [' Maruti', ' Alto', ' 800'], [' Volkswagen', ' Polo'], [' Maruti', ' S', ' PRESSO'], [' Maruti', ' Swift'], [' Hyundai', ' Creta'], [' Hyundai', ' i10'], [' Mahindra', ' XUV500'], [' Maruti', ' Dzire'], [' Maruti', ' Swift'], [' Maruti', ' Swift']]
['New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara', 'New Sama, Vadodara']
[['54,479'], ['78,651'], ['67,081'], ['82,340'], ['1,12', ',434'], ['76,800'], ['63,911'], ['56,700'], ['97,177'], ['96,797'], ['88,798'], ['86,874'], ['13,864'], ['23,941'], ['43,008'], ['85,320'], ['91,086'], ['88,193'], ['80,384'], ['80,580']]
[['Petrol'], ['Petrol'], ['Petrol'], nan, nan, nan, ['Petrol'], ['Diesel'], ['Diesel'], ['Diesel'], ['Petrol'], ['Petrol'], nan, ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], nan, ['Petrol']]
[['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Automatic'], ['Manual'], ['Manual']]
['440000', '577000', '332000', '170000', '267000', '500000', '746000', '819000', '485000', '411000', '198000', '366500', '573000', '673000', '1052000', '219000', '982000', '569000', '375000', '406000']

In [150]:
dicto23 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [151]:
kmt1 = []
dicto23["Kmt run"]
for i in dicto23["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto23n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto23n

{'Name of Cars': [[' Tata', ' TIGOR'],
  [' Maruti', ' Ertiga'],
  [' Renault', ' Kwid'],
  [' Maruti', ' Alto'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Honda', ' City'],
  [' Maruti', ' Ciaz'],
  [' Hyundai', ' Verna'],
  [' Honda', ' City'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Alto', ' 800'],
  [' Volkswagen', ' Polo'],
  [' Maruti', ' S', ' PRESSO'],
  [' Maruti', ' Swift'],
  [' Hyundai', ' Creta'],
  [' Hyundai', ' i10'],
  [' Mahindra', ' XUV500'],
  [' Maruti', ' Dzire'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Swift']],
 'Registration Year': ['2018',
  '2014',
  '2019',
  '2011',
  '2012',
  '2014',
  '2018',
  '2017',
  '2014',
  '2015',
  '2013',
  '2014',
  '2022',
  '2021',
  '2020',
  '2010',
  '2017',
  '2018',
  '2013',
  '2014'],
 'Kmt run': [54479,
  78651,
  67081,
  82340,
  112434,
  76800,
  63911,
  56700,
  97177,
  96797,
  88798,
  86874,
  13864,
  23941,
  43008,
  85320,
  91086,
  88193,
  80384,
  80580],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Automatic'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Petrol'],
  ['Petrol'],
  ['Petrol'],
  nan,
  nan,
  nan,
  ['Petrol'],
  ['Diesel'],
  ['Diesel'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  nan,
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  nan,
  ['Petrol']],
 'Price': ['440000',
  '577000',
  '332000',
  '170000',
  '267000',
  '500000',
  '746000',
  '819000',
  '485000',
  '411000',
  '198000',
  '366500',
  '573000',
  '673000',
  '1052000',
  '219000',
  '982000',
  '569000',
  '375000',
  '406000'],
 'Location of car': ['New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara',
  'New Sama, Vadodara']}

In [152]:
url24 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata%3AOR%3Amake%3A%3D%3Ahonda%3AOR%3Amake%3A%3D%3Arenault%3AOR%3Amake%3A%3D%3Atoyota%3AOR%3Amake%3A%3D%3Aford%3AOR%3Amake%3A%3D%3Amahindra%3AOR%3Amake%3A%3D%3Avolkswagen%3AOR%3Amake%3A%3D%3Adatsun%3AOR%3Amake%3A%3D%3Akia%3AOR%3Amake%3A%3D%3Anissan%3AOR%3Amake%3A%3D%3Ajeep%3AOR%3Amake%3A%3D%3Askoda&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=1605&pinId=394101"

In [153]:
new24 = req.get(url24)
new24

In [154]:
soup = BeautifulSoup(new24.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n153 Used Cars in Surat - Second Hand Cars for Sale\n\n SuratBuy a carPopular makesMarutiHyundaiHondaRenaultVolkswagenFordMahindraTataToyotaDatsunView all makesPopular ModelsHyundai i10Maruti BalenoMaruti SwiftMaruti DzireMaruti AltoHyundai i20Honda BrioHyundai EonMaruti Wagon RHonda CityView all modelsBody typeHatchbackSedanSUVLuxury SUVFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Baleno (11)Maruti Swift (10)Hyundai Grand i10 (10)Hyundai i10 (10)Hyundai Eon (6)Honda Brio (6)ALL BRANDSMaruti (61)Hyundai (39)Honda (21)Renault (6)Ford (5)Volkswagen (5)Tata (4)Mahindra (4)Toyota (4)Datsun (2)KIA (1)Nissan (1)BMW (0)Mercedes Benz (0)Skoda (0)Audi (0)Jeep (0)Fiat (0)MG (0)Volvo (0)Jaguar (0)Budget₹ 1,00,000₹ 25,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear AllShow More 153 Used cars in SuratSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹68,000off2014 Hyundai VernaFLUIDIC 1.6 CRDI SX OPTManual94,372 km3rd OwnerDieselGJ-05₹6,147/month ₹78,600 downpayment₹3,93,000₹4,61,000Sachin Magdalla Road, Surat₹44,000off2017 Honda WR-V1.5L I-DTEC VX MTManual47,235 km1st OwnerDieselGJ-05₹11,011/month ₹1,40,800 downpayment₹7,04,000₹7,48,000Sachin Magdalla Road, SuratNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹1,08,000off2018 Honda Amaze1.2L I-VTEC SManual66,535 km3rd OwnerPetrolGJ-27₹7,413/month ₹94,800 downpayment₹4,74,000₹5,82,000Sachin Magdalla Road, Surat₹8,000off2016 Renault KwidRXT 0.8Manual19,712 km1st OwnerPetrolGJ-05₹3,722/month ₹47,600 downpayment₹2,38,000₹2,46,000Sachin Magdalla Road, Surat₹45,000off2017 Mahindra XUV500W10Manual83,180 km1st OwnerDieselGJ-06₹13,354/month ₹1,75,400 downpayment₹8,77,000₹9,22,000Sachin Magdalla Road, SuratUsed cars in Surat by brandMarutiHyundaiHondaRenaultFordVolkswagenMahindraToyotaTataDatsunNissanKIASkodaMGJeep₹80,000off2012 Hyundai i10SPORTZ 1.2Manual59,322 km3rd OwnerPetrolGJ-21₹3,363/month ₹43,000 downpayment₹2,15,000₹2,95,000Sachin Magdalla Road, Surat₹50,000off2017 Datsun Redi GoT (O)Manual76,982 km1st OwnerPetrolGJ-06₹3,081/month ₹39,400 downpayment₹1,97,000₹2,47,000Sachin Magdalla Road, Surat₹37,000off2010 Hyundai i20SPORTZ 1.2Manual56,738 km1st OwnerPetrolGJ-05₹3,597/month ₹46,000 downpayment₹2,30,000₹2,67,000Sachin Magdalla Road, SuratUsed cars in Surat by body typeHatchbackSedanSUVLuxury SUVLuxury Sedan₹88,000off2017 Toyota Fortuner2.8 4X2 ATAutomatic1,16,742 km3rd OwnerDieselGJ-27₹33,043/month ₹4,34,000 downpayment₹21,70,000₹22,58,000Sachin Magdalla Road, Surat₹1,05,000off2016 Maruti SwiftVXIManual87,531 km2nd OwnerPetrolGJ-05₹6,100/month ₹78,000 downpayment₹3,90,000₹4,95,000Sachin Magdalla Road, Surat₹11,000off2011 Maruti Zen EstiloLXIManual70,006 km2nd OwnerPetrolGJ-15₹2,237/month ₹28,600 downpayment₹1,43,000₹1,54,000Sachin Magdalla Road, SuratUsed cars in Surat by fuel typePetrolDieselCNG₹71,000off2014 Honda City1.5L I-DTEC SVManual94,591 km1st OwnerDieselGJ-05₹6,397/month ₹81,800 downpayment₹4,09,000₹4,80,000Sachin Magdalla Road, Surat₹52,000off2012 Maruti Wagon R 1.0VXIManual78,259 km1st OwnerPetrolGJ-05₹3,503/month ₹44,800 downpayment₹2,24,000₹2,76,000Sachin Magdalla Road, Surat₹58,000off2016 Maruti CelerioVXI AMTAutomatic84,264 km1st OwnerPetrolGJ-05₹4,692/month ₹60,000 downpayment₹3,00,000₹3,58,000Sachin Magdalla Road, SuratUsed cars in Surat by budgetbetween 2 to 5 lakhsbetween 5 to 10 lakhsunder 2 lakhsabove 10 lakhs₹17,000off2018 Hyundai Elite i20MAGNA EXECUTIVE 1.2Manual71,511 km1st OwnerPetrolGJ-03₹8,790/month ₹1,12,400 downpayment₹5,62,000₹5,79,000Sachin Magdalla Road, Surat₹16,000off2018 Hyundai Elite i20SPORTZ 1.2Manual13,141 km1st OwnerPetrolGJ-05₹9,838/month ₹1,25,800 downpayment₹6,29,000₹6,45,000Sachin Magdalla Road, Surat₹44,000off2014 Volkswagen Cross PoloHIGHLINE TDIManual1,23,250 km1st OwnerDieselGJ-0J₹5,052/month ₹64,600 downpayment₹3,23,000₹3,67,000Sachin Magdalla Road, SuratUsed cars in Surat by modelHyundai i10Maruti BalenoMaruti SwiftMaruti DzireMaruti AltoHyundai i20Maruti Wagon RHonda BrioHyundai EonHonda CityFord EcosportMaruti CiazMaruti CelerioHonda WR-VHonda AmazeRenault KwidHyundai SantroMaruti IGNISVolkswagen PoloMaruti Brezza₹57,000off2018 Mahindra KUV 100 NXTK2 P 6 STRManual61,528 km2nd OwnerPetrolGJ-05₹5,083/month ₹65,000 downpayment₹3,25,000₹3,82,000Sachin Magdalla Road, Surat₹10,000off2010 Maruti Zen EstiloVXIManual54,715 km1st OwnerPetrolGJ-06₹2,815/month ₹36,000 downpayment₹1,80,000₹1,90,000Sachin Magdalla Road, Surat₹81,000off2014 Hyundai i20SPORTZ 1.4 ATAutomatic62,428 km1st OwnerPetrolGJ-05₹6,287/month ₹80,400 downpayment₹4,02,000₹4,83,000Sachin Magdalla Road, SuratHomeUsed CarsSurat45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions SuratWhat are the most popular brands available for 2nd hand cars in Surat?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Surat of your choice on CARS24.What body types are available for 2nd hand cars in Surat?Used cars in Surat are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Surat?Of Course yes, you can buy used cars online in Surat from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in SuratWhat to check before buying a second hand car in Surat?Important things to check  before buying a second hand car in Surat are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Surat?You can buy used cars in Surat from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Surat?You can check second hand cars in Surat using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in SuratHow many second hand cars are available in Surat?153 used cars are available in Surat of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in SuratUsed Hyundai Cars in SuratUsed Honda Cars in SuratUsed Renault Cars in SuratUsed Ford Cars in SuratUsed Volkswagen Cars in SuratUsed Mahindra Cars in SuratUsed Toyota Cars in SuratUsed Tata Cars in SuratUsed Datsun Cars in SuratUsed Nissan Cars in SuratUsed KIA Cars in SuratUsed Skoda Cars in SuratUsed MG Cars in SuratUsed Jeep Cars in SuratBody :Used Hatchback Cars in SuratUsed Sedan Cars in SuratUsed SUV Cars in SuratUsed Luxury SUV Cars in SuratUsed Luxury Sedan Cars in SuratFuel :Used Petrol Cars in SuratUsed Diesel Cars in SuratUsed CNG Cars in SuratBudget :Used Cars between 2 to 5 lakhs in SuratUsed Cars between 5 to 10 lakhs in SuratUsed Cars under 2 lakhs in SuratUsed Cars above 10 lakhs in SuratModel :Used Hyundai i10 Cars in SuratUsed Maruti Baleno Cars in SuratUsed Maruti Swift Cars in SuratUsed Maruti Dzire Cars in SuratUsed Maruti Alto Cars in SuratUsed Hyundai i20 Cars in SuratUsed Maruti Wagon R Cars in SuratUsed Honda Brio Cars in SuratUsed Hyundai Eon Cars in SuratUsed Honda City Cars in SuratUsed Ford Ecosport Cars in SuratUsed Maruti Ciaz Cars in SuratUsed Maruti Celerio Cars in SuratUsed Honda WR-V Cars in SuratUsed Honda Amaze Cars in SuratUsed Renault Kwid Cars in SuratUsed Hyundai Santro Cars in SuratUsed Maruti IGNIS Cars in SuratUsed Volkswagen Polo Cars in SuratUsed Maruti Brezza Cars in SuratTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [155]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2014', '2017', '2018', '2016', '2017', '2012', '2017', '2010', '2017', '2016', '2011', '2014', '2012', '2016', '2018', '2018', '2014', '2018', '2010', '2014']
[[' Hyundai', ' Verna'], [' Honda', ' WR'], [' Honda', ' Amaze'], [' Renault', ' Kwid'], [' Mahindra', ' XUV500'], [' Hyundai', ' i10'], [' Datsun', ' Redi', ' Go'], [' Hyundai', ' i20'], [' Toyota', ' Fortuner'], [' Maruti', ' Swift'], [' Maruti', ' Zen', ' Estilo'], [' Honda', ' City'], [' Maruti', ' Wagon', ' R', ' 1'], [' Maruti', ' Celerio'], [' Hyundai', ' Elite', ' i20'], [' Hyundai', ' Elite', ' i20'], [' Volkswagen', ' Cross', ' Polo'], [' Mahindra', ' KUV', ' 100', ' NXT'], [' Maruti', ' Zen', ' Estilo'], [' Hyundai', ' i20']]
['Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat', 'Sachin Magdalla Road, Surat']
[['94,372'], ['47,235'], ['66,535'], ['19,712'], ['83,180'], ['59,322'], ['76,982'], ['56,738'], ['1,16', ',742'], ['87,531'], ['70,006'], ['94,591'], ['78,259'], ['84,264'], ['71,511'], ['13,141'], ['1,23', ',250'], ['61,528'], ['54,715'], ['62,428']]
[['Diesel'], ['Diesel'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], ['Petrol'], ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic']]
['393000', '704000', '474000', '238000', '877000', '215000', '197000', '230000', '2170000', '390000', '143000', '409000', '224000', '300000', '562000', '629000', '323000', '325000', '180000', '402000']

In [156]:
dicto24 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [157]:
kmt1 = []
dicto24["Kmt run"]
for i in dicto24["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto24n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto24n

{'Name of Cars': [[' Hyundai', ' Verna'],
  [' Honda', ' WR'],
  [' Honda', ' Amaze'],
  [' Renault', ' Kwid'],
  [' Mahindra', ' XUV500'],
  [' Hyundai', ' i10'],
  [' Datsun', ' Redi', ' Go'],
  [' Hyundai', ' i20'],
  [' Toyota', ' Fortuner'],
  [' Maruti', ' Swift'],
  [' Maruti', ' Zen', ' Estilo'],
  [' Honda', ' City'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Maruti', ' Celerio'],
  [' Hyundai', ' Elite', ' i20'],
  [' Hyundai', ' Elite', ' i20'],
  [' Volkswagen', ' Cross', ' Polo'],
  [' Mahindra', ' KUV', ' 100', ' NXT'],
  [' Maruti', ' Zen', ' Estilo'],
  [' Hyundai', ' i20']],
 'Registration Year': ['2014',
  '2017',
  '2018',
  '2016',
  '2017',
  '2012',
  '2017',
  '2010',
  '2017',
  '2016',
  '2011',
  '2014',
  '2012',
  '2016',
  '2018',
  '2018',
  '2014',
  '2018',
  '2010',
  '2014'],
 'Kmt run': [94372,
  47235,
  66535,
  19712,
  83180,
  59322,
  76982,
  56738,
  116742,
  87531,
  70006,
  94591,
  78259,
  84264,
  71511,
  13141,
  123250,
  61528,
  54715,
  62428],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic']],
 'Fuel type': [['Diesel'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['393000',
  '704000',
  '474000',
  '238000',
  '877000',
  '215000',
  '197000',
  '230000',
  '2170000',
  '390000',
  '143000',
  '409000',
  '224000',
  '300000',
  '562000',
  '629000',
  '323000',
  '325000',
  '180000',
  '402000'],
 'Location of car': ['Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat',
  'Sachin Magdalla Road, Surat']}

In [158]:
url25 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata%3AOR%3Amake%3A%3D%3Ahonda%3AOR%3Amake%3A%3D%3Arenault%3AOR%3Amake%3A%3D%3Atoyota%3AOR%3Amake%3A%3D%3Aford%3AOR%3Amake%3A%3D%3Amahindra%3AOR%3Amake%3A%3D%3Avolkswagen%3AOR%3Amake%3A%3D%3Adatsun%3AOR%3Amake%3A%3D%3Akia%3AOR%3Amake%3A%3D%3Anissan%3AOR%3Amake%3A%3D%3Ajeep%3AOR%3Amake%3A%3D%3Askoda&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=1606&pinId=360001"

In [159]:
new25 = req.get(url25)
new25

In [160]:
soup = BeautifulSoup(new25.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n149 Used Cars in Rajkot - Second Hand Cars for Sale\n\n RajkotBuy a carPopular makesMarutiHyundaiHondaVolkswagenRenaultMahindraTataNissanFordSkodaView all makesPopular ModelsMaruti AltoHyundai i10Maruti SwiftHyundai i20Honda CityHonda AmazeMaruti BalenoMaruti Wagon RMaruti CiazMaruti DzireView all modelsBody typeHatchbackSedanSUVLuxury SUVFuel typePetrolDieselCNGTransmissionManualAutomaticBudgetCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhCars above 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Swift (11)Honda City (9)Hyundai Grand i10 (9)Hyundai Elite i20 (8)Honda Amaze (8)Maruti Baleno (7)ALL BRANDSMaruti (62)Hyundai (30)Honda (27)Volkswagen (10)Renault (5)Ford (3)Tata (3)Nissan (3)Mahindra (2)Datsun (1)Skoda (1)Jeep (1)Toyota (1)KIA (0)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)MG (0)Volvo (0)Jaguar (0)Budget₹ 2,00,000₹ 20,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear AllShow More 149 Used cars in RajkotSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New₹33,000off2018 Hyundai XcentE+Manual56,674 km2nd OwnerPetrolGJ-37₹7,617/month ₹97,400 downpayment₹4,87,000₹5,20,000Akshar Party, Rajkot₹16,000off2010 Hyundai i10MAGNA 1.2Manual58,135 km2nd OwnerPetrolGJ-10₹3,300/month ₹42,200 downpayment₹2,11,000₹2,27,000Akshar Party, RajkotNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹12,000off2014 Honda City1.5L I-DTEC SVManual80,664 km3rd OwnerDieselGJ-03₹6,678/month ₹85,400 downpayment₹4,27,000₹4,39,000Akshar Party, Rajkot2016 Hyundai Grand i10SPORTZ 1.1 CRDIManual92,407 km2nd OwnerDieselGJ-01₹5,662/month ₹72,400 downpayment₹3,62,000Akshar Party, Rajkot₹15,000off2012 Maruti SwiftVDIManual1,00,448 km2nd OwnerDieselGJ-03₹5,271/month ₹67,400 downpayment₹3,37,000₹3,52,000Akshar Party, RajkotUsed cars in Rajkot by brandMarutiHyundaiHondaVolkswagenRenaultMahindraNissanTataFordToyotaJeepSkodaDatsunKIA₹26,000off2018 Tata TiagoXZ PETROLManual53,673 km1st OwnerPetrolGJ-36₹6,350/month ₹81,200 downpayment₹4,06,000₹4,32,000Akshar Party, Rajkot₹6,000off2010 Maruti Wagon R 1.0VXIManual64,810 km1st OwnerPetrolGJ-03₹3,222/month ₹41,200 downpayment₹2,06,000₹2,12,000Akshar Party, Rajkot₹31,000off2016 Hyundai Elite i20ASTA 1.2 (O)Manual1,00,785 km2nd OwnerCNGGJ-12₹8,227/month ₹1,05,200 downpayment₹5,26,000₹5,57,000Akshar Party, RajkotUsed cars in Rajkot by body typeHatchbackSedanSUVLuxury SUV2021 Hyundai VENUES 1.2Manual24,897 km2nd OwnerPetrolGJ-04₹11,980/month ₹1,53,200 downpayment₹7,66,000Akshar Party, Rajkot₹14,000off2012 Maruti Wagon R 1.0LXIManual56,336 km1st OwnerCNGGJ-03₹4,364/month ₹55,800 downpayment₹2,79,000₹2,93,000Akshar Party, Rajkot2020 Maruti S PRESSOVXI+Manual50,954 km1st OwnerCNGGJ-36₹7,226/month ₹92,400 downpayment₹4,62,000Akshar Party, RajkotUsed cars in Rajkot by fuel typePetrolDieselCNG2020 Hyundai NEW I20SPORTZ 1.5 MTManual57,372 km1st OwnerDieselGJ-03₹12,027/month ₹1,53,800 downpayment₹7,69,000Akshar Party, Rajkot₹19,000off2015 Volkswagen PoloCOMFORTLINE 1.2LManual99,559 km1st OwnerPetrolGJ-03₹5,834/month ₹74,600 downpayment₹3,73,000₹3,92,000Akshar Party, Rajkot₹73,000off2017 Volkswagen PoloHIGHLINE1.2LManual86,604 km2nd OwnerCNGGJ-12₹7,632/month ₹97,600 downpayment₹4,88,000₹5,61,000Akshar Party, RajkotUsed cars in Rajkot by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsabove 10 lakhsunder 2 lakhs₹26,000off2017 Hyundai Grand i10SPORTZ (O) 1.2 KAPPA VTVTManual57,990 km1st OwnerPetrolGJ-12₹7,194/month ₹92,000 downpayment₹4,60,000₹4,86,000Akshar Party, Rajkot₹9,000off2017 Maruti Alto K10VXIManual75,740 km2nd OwnerPetrolGJ-03₹4,614/month ₹59,000 downpayment₹2,95,000₹3,04,000Akshar Party, Rajkot₹12,000off2019 Hyundai Elite i20SPORTZ PLUS 1.2Manual52,314 km1st OwnerPetrolGJ-04₹10,479/month ₹1,34,000 downpayment₹6,70,000₹6,82,000Akshar Party, RajkotUsed cars in Rajkot by modelMaruti AltoHyundai i10Maruti SwiftHyundai i20Honda CityHonda AmazeMaruti BalenoMaruti Wagon RMaruti CiazMaruti DzireVolkswagen PoloRenault KwidMaruti CelerioHonda JazzHyundai SantroHonda WR-VMaruti IGNISHonda BrioHyundai XcentMaruti S PRESSO₹27,000off2015 Maruti SwiftVDI ABSManual1,24,318 km3rd OwnerDieselGJ-03₹5,380/month ₹68,800 downpayment₹3,44,000₹3,71,000Akshar Party, Rajkot₹17,000off2019 Honda Amaze1.2L I-VTEC EManual38,866 km1st OwnerCNGGJ-03₹9,275/month ₹1,18,600 downpayment₹5,93,000₹6,10,000Akshar Party, Rajkot₹39,000off2016 Maruti SwiftZXIManual64,824 km1st OwnerPetrolGJ-04₹7,523/month ₹96,200 downpayment₹4,81,000₹5,20,000Akshar Party, RajkotHomeUsed CarsRajkot45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions RajkotWhat are the most popular brands available for 2nd hand cars in Rajkot?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Rajkot of your choice on CARS24.What body types are available for 2nd hand cars in Rajkot?Used cars in Rajkot are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Rajkot?Of Course yes, you can buy used cars online in Rajkot from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in RajkotWhat to check before buying a second hand car in Rajkot?Important things to check  before buying a second hand car in Rajkot are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Rajkot?You can buy used cars in Rajkot from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Rajkot?You can check second hand cars in Rajkot using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in RajkotHow many second hand cars are available in Rajkot?149 used cars are available in Rajkot of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in RajkotUsed Hyundai Cars in RajkotUsed Honda Cars in RajkotUsed Volkswagen Cars in RajkotUsed Renault Cars in RajkotUsed Mahindra Cars in RajkotUsed Nissan Cars in RajkotUsed Tata Cars in RajkotUsed Ford Cars in RajkotUsed Toyota Cars in RajkotUsed Jeep Cars in RajkotUsed Skoda Cars in RajkotUsed Datsun Cars in RajkotUsed KIA Cars in RajkotBody :Used Hatchback Cars in RajkotUsed Sedan Cars in RajkotUsed SUV Cars in RajkotUsed Luxury SUV Cars in RajkotFuel :Used Petrol Cars in RajkotUsed Diesel Cars in RajkotUsed CNG Cars in RajkotBudget :Used Cars between 5 to 10 lakhs in RajkotUsed Cars between 2 to 5 lakhs in RajkotUsed Cars above 10 lakhs in RajkotUsed Cars under 2 lakhs in RajkotModel :Used Maruti Alto Cars in RajkotUsed Hyundai i10 Cars in RajkotUsed Maruti Swift Cars in RajkotUsed Hyundai i20 Cars in RajkotUsed Honda City Cars in RajkotUsed Honda Amaze Cars in RajkotUsed Maruti Baleno Cars in RajkotUsed Maruti Wagon R Cars in RajkotUsed Maruti Ciaz Cars in RajkotUsed Maruti Dzire Cars in RajkotUsed Volkswagen Polo Cars in RajkotUsed Renault Kwid Cars in RajkotUsed Maruti Celerio Cars in RajkotUsed Honda Jazz Cars in RajkotUsed Hyundai Santro Cars in RajkotUsed Honda WR-V Cars in RajkotUsed Maruti IGNIS Cars in RajkotUsed Honda Brio Cars in RajkotUsed Hyundai Xcent Cars in RajkotUsed Maruti S PRESSO Cars in RajkotTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [161]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2018', '2010', '2014', '2016', '2012', '2018', '2010', '2016', '2021', '2012', '2020', '2020', '2015', '2017', '2017', '2017', '2019', '2015', '2019', '2016']
[[' Hyundai', ' Xcent'], [' Hyundai', ' i10'], [' Honda', ' City'], [' Hyundai', ' Grand', ' i10'], [' Maruti', ' Swift'], [' Tata', ' Tiago'], [' Maruti', ' Wagon', ' R', ' 1'], [' Hyundai', ' Elite', ' i20'], [' Hyundai', ' VENUE'], [' Maruti', ' Wagon', ' R', ' 1'], [' Maruti', ' S', ' PRESSO'], [' Hyundai', ' NEW', ' I20'], [' Volkswagen', ' Polo'], [' Volkswagen', ' Polo'], [' Hyundai', ' Grand', ' i10'], [' Maruti', ' Alto', ' K10'], [' Hyundai', ' Elite', ' i20'], [' Maruti', ' Swift'], [' Honda', ' Amaze'], [' Maruti', ' Swift']]
['Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot', 'Akshar Party, Rajkot']
[['56,674'], ['58,135'], ['80,664'], ['92,407'], ['1,00', ',448'], ['53,673'], ['64,810'], ['1,00', ',785'], ['24,897'], ['56,336'], ['50,954'], ['57,372'], ['99,559'], ['86,604'], ['57,990'], ['75,740'], ['52,314'], ['1,24', ',318'], ['38,866'], ['64,824']]
[['Petrol'], ['Petrol'], ['Diesel'], ['Diesel'], ['Diesel'], ['Petrol'], ['Petrol'], nan, ['Petrol'], nan, nan, ['Diesel'], ['Petrol'], nan, ['Petrol'], ['Petrol'], ['Petrol'], ['Diesel'], nan, ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['487000', '211000', '427000', '362000', '337000', '406000', '206000', '526000', '766000', '279000', '462000', '769000', '373000', '488000', '460000', '295000', '670000', '344000', '593000', '481000']

In [162]:
dicto25 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [163]:
kmt1 = []
dicto25["Kmt run"]
for i in dicto25["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto25n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto25n

{'Name of Cars': [[' Hyundai', ' Xcent'],
  [' Hyundai', ' i10'],
  [' Honda', ' City'],
  [' Hyundai', ' Grand', ' i10'],
  [' Maruti', ' Swift'],
  [' Tata', ' Tiago'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Hyundai', ' Elite', ' i20'],
  [' Hyundai', ' VENUE'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Maruti', ' S', ' PRESSO'],
  [' Hyundai', ' NEW', ' I20'],
  [' Volkswagen', ' Polo'],
  [' Volkswagen', ' Polo'],
  [' Hyundai', ' Grand', ' i10'],
  [' Maruti', ' Alto', ' K10'],
  [' Hyundai', ' Elite', ' i20'],
  [' Maruti', ' Swift'],
  [' Honda', ' Amaze'],
  [' Maruti', ' Swift']],
 'Registration Year': ['2018',
  '2010',
  '2014',
  '2016',
  '2012',
  '2018',
  '2010',
  '2016',
  '2021',
  '2012',
  '2020',
  '2020',
  '2015',
  '2017',
  '2017',
  '2017',
  '2019',
  '2015',
  '2019',
  '2016'],
 'Kmt run': [56674,
  58135,
  80664,
  92407,
  100448,
  53673,
  64810,
  100785,
  24897,
  56336,
  50954,
  57372,
  99559,
  86604,
  57990,
  75740,
  52314,
  124318,
  38866,
  64824],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Petrol'],
  ['Petrol'],
  ['Diesel'],
  ['Diesel'],
  ['Diesel'],
  ['Petrol'],
  ['Petrol'],
  nan,
  ['Petrol'],
  nan,
  nan,
  ['Diesel'],
  ['Petrol'],
  nan,
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Diesel'],
  nan,
  ['Petrol']],
 'Price': ['487000',
  '211000',
  '427000',
  '362000',
  '337000',
  '406000',
  '206000',
  '526000',
  '766000',
  '279000',
  '462000',
  '769000',
  '373000',
  '488000',
  '460000',
  '295000',
  '670000',
  '344000',
  '593000',
  '481000'],
 'Location of car': ['Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot',
  'Akshar Party, Rajkot']}

In [164]:
url26 = "https://www.cars24.com/buy-used-car?f=make%3A%3D%3Ahyundai%3AOR%3Amake%3A%3D%3Amaruti%3AOR%3Amake%3A%3D%3Atata%3AOR%3Amake%3A%3D%3Ahonda%3AOR%3Amake%3A%3D%3Arenault%3AOR%3Amake%3A%3D%3Atoyota%3AOR%3Amake%3A%3D%3Aford%3AOR%3Amake%3A%3D%3Amahindra%3AOR%3Amake%3A%3D%3Avolkswagen%3AOR%3Amake%3A%3D%3Adatsun%3AOR%3Amake%3A%3D%3Akia%3AOR%3Amake%3A%3D%3Anissan%3AOR%3Amake%3A%3D%3Ajeep%3AOR%3Amake%3A%3D%3Askoda&sort=bestmatch&serveWarrantyCount=true&gaId=148626934.1699693409&storeCityId=33&pinId=124001"

In [165]:
new26 = req.get(url26)
new26

In [166]:
soup = BeautifulSoup(new26.text)
soup.text

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n187 Used Cars in Rohtak - Second Hand Cars for Sale\n\n RohtakBuy a carPopular makesMarutiHyundaiTataView all makesPopular ModelsMaruti Wagon RHyundai i10Maruti DzireHyundai i20Hyundai CretaTata NEXONTata ALTROZMaruti AltoTata TIGORMaruti SwiftView all modelsBody typeHatchbackSUVSedanFuel typePetrolCNGDieselTransmissionManualBudgetCars under 2 LakhCars between 2 Lakh - 5 LakhCars between 5 Lakh - 10 LakhSell a carCar financeHello, Sign inAccount LOG IN/SIGN UP My AppointmentsSELLMy BookingsBUYMy OrdersSell Used CarSell car in New DelhiSell car in BengaluruSell car in ChennaiSell car in HyderabadSell car in MumbaiSell car in PuneSell car in AhmedabadSell car in KolkataSell car in JaipurSell car in ChandigarhBuy Used CarUsed cars in New DelhiUsed cars in MumbaiUsed cars in BangaloreUsed cars in HyderabadUsed cars in AhmedabadUsed cars in GurgaonUsed cars in ChennaiUsed cars in PuneUsed cars in NoidaUsed cars in GhaziabadUsed cars in FaridabadUsed cars in LucknowUsed cars in JaipurUsed cars in KolkataUsed cars in KochiUsed cars in NashikUsed cars in NagpurUsed cars in CoimbatoreUsed cars in IndoreUsed cars in PatnaUsed cars in SuratUsed cars in ChandigarhUsed cars in LudhianaUsed cars in RohtakUsed cars in RajkotUsed cars in VadodaraUsed cars in AgraView and pay challanNEWCar Servicing & RepairNEWResourcesRC Transfer StatusBecome Our partnerFAQMake & ModelSuggestionsMaruti Baleno (19)Maruti Swift (12)Maruti Alto K10 (9)Maruti New Wagon-R (8)Honda City (8)Maruti Wagon R 1.0 (6)ALL BRANDSMaruti (89)Hyundai (40)Honda (19)Tata (15)KIA (3)Datsun (3)Renault (3)Mahindra (3)Toyota (3)Volkswagen (3)Ford (2)Jeep (2)Skoda (1)Nissan (1)BMW (0)Mercedes Benz (0)Audi (0)Fiat (0)MG (0)Volvo (0)Jaguar (0)Budget₹ 1,00,000₹ 20,00,000 MinimumMaximumSuggestionsUnder 3 lakhFrom 3 lakh - 5 lakhFrom 5 lakh - 7 lakhFrom 7 lakh - 10 lakhAbove 10 lakhFuelModel YearFeaturesRTOBody TypeTransmissionOwnersSeatsKms DrivenCARS24 HUBDiscountColorClear AllShow More 187 Used cars in RohtakSort By:Best Match  Best MatchRecently AddedPriceLow to HighHigh to LowKms DrivenLow to HighHigh to LowCars ageNew to OldOld to New2011 Hyundai i20MAGNA (O) 1.2Manual89,507 km2nd OwnerPetrolHR-26₹3,597/month ₹46,000 downpayment₹2,30,000Parsvnath City Mall, Faridabad₹21,000off2012 Maruti Swift DzireVXIManual93,869 km2nd OwnerPetrolHR-26₹4,113/month ₹52,600 downpayment₹2,63,000₹2,84,000Sector 33, RohtakNeed a car loan?Answer a few questions to  check EMI offers Down  PaymentInterest  RateMonths  EMICheck eligibility ₹27,000off2015 Honda City1.5L I-VTEC S MTManual24,569 km1st OwnerPetrolHR-26₹7,539/month ₹96,400 downpayment₹4,82,000₹5,09,000Parsvnath City Mall, Faridabad₹46,000off2022 Tata PUNCHADVENTURE MTManual21,566 km1st OwnerPetrolHR-51₹9,650/month ₹1,23,400 downpayment₹6,17,000₹6,63,000Parsvnath City Mall, Faridabad₹29,000off2017 Maruti Wagon R 1.0LXI CNGManual71,802 km1st OwnerCNGHR-10₹5,709/month ₹73,000 downpayment₹3,65,000₹3,94,000Parsvnath City Mall, FaridabadUsed cars in Rohtak by brandMarutiHyundaiTataToyotaHondaNissanVolkswagenRenaultDatsunFord₹21,000off2021 Tata ALTROZXE PETROLManual20,955 km1st OwnerPetrolHR-08₹8,336/month ₹1,06,600 downpayment₹5,33,000₹5,54,000Parsvnath City Mall, Faridabad₹22,000off2017 Hyundai Elite i20ASTA 1.2 (O)Manual66,802 km2nd OwnerCNGHR-36₹8,884/month ₹1,13,600 downpayment₹5,68,000₹5,90,000Sector 33, Rohtak₹88,300off2022 Hyundai NEW I20SPORTZ 1.2 MTManual12,181 km1st OwnerPetrolHR-26₹11,037/month ₹1,41,140 downpayment₹7,05,700₹7,94,000Sector 33, RohtakUsed cars in Rohtak by body typeHatchbackSUVSedan2019 Maruti BalenoZETA PETROL 1.2Manual22,963 km2nd OwnerPetrolHR-26₹9,650/month ₹1,23,400 downpayment₹6,17,000Parsvnath City Mall, Faridabad₹90,000off2019 Hyundai XcentS 1.2Manual50,971 km1st OwnerPetrolHR-51₹7,257/month ₹92,800 downpayment₹4,64,000₹5,54,000Parsvnath City Mall, Faridabad₹53,000off2017 Maruti BalenoZETA PETROL 1.2Manual56,740 km1st OwnerPetrolHR-26₹7,726/month ₹98,800 downpayment₹4,94,000₹5,47,000Parsvnath City Mall, FaridabadUsed cars in Rohtak by fuel typePetrolCNGDiesel₹40,000off2018 Maruti Wagon R 1.0LXI CNGManual78,642 km1st OwnerCNGHR-51₹5,646/month ₹72,200 downpayment₹3,61,000₹4,01,000Sector 33, Rohtak₹25,000off2013 Hyundai Santro XingGL PLUSManual61,788 km1st OwnerPetrolHR-51₹3,144/month ₹40,200 downpayment₹2,01,000₹2,26,000Parsvnath City Mall, Faridabad₹13,000off2019 Maruti Alto K10LXI CNG (AIRBAG)Manual54,914 km1st OwnerCNGHR-51₹5,114/month ₹65,400 downpayment₹3,27,000₹3,40,000Parsvnath City Mall, FaridabadUsed cars in Rohtak by budgetbetween 5 to 10 lakhsbetween 2 to 5 lakhsunder 2 lakhsabove 10 lakhs2010 Maruti Zen EstiloVXIManual56,172 km1st OwnerPetrolDL-9C₹1,799/month ₹23,000 downpayment₹1,15,000Sector 33, Rohtak₹7,000off2014 Hyundai Grand i10ASTA AT 1.2 KAPPA VTVTAutomatic26,218 km1st OwnerPetrolHR-51₹7,163/month ₹91,600 downpayment₹4,58,000₹4,65,000Parsvnath City Mall, Faridabad2023 Maruti BREZZAZXI SMART HYBRID Manual11,948 km1st OwnerPetrolHR-31₹18,120/month ₹2,38,000 downpayment₹11,90,000Parsvnath City Mall, FaridabadUsed cars in Rohtak by modelHyundai i10Maruti Wagon RMaruti DzireHyundai CretaTata NEXONHyundai i20Maruti CelerioTata TIGORMaruti ErtigaMaruti SwiftHyundai SantroHyundai VENUETata ALTROZMaruti CiazHyundai AURAMaruti AltoMaruti Zen EstiloMaruti BalenoMaruti BrezzaDatsun Redi Go2017 Maruti CelerioVXIManual1,18,486 km1st OwnerPetrolHR-26₹5,083/month ₹65,000 downpayment₹3,25,000Parsvnath City Mall, Faridabad₹29,000off2015 Hyundai Grand i10SPORTZ 1.2 KAPPA VTVTManual90,358 km1st OwnerPetrolDL-7C₹5,490/month ₹70,200 downpayment₹3,51,000₹3,80,000Sector 33, Rohtak₹46,000off2011 Maruti SwiftLXIManual81,771 km1st OwnerPetrolHR-51₹2,956/month ₹37,800 downpayment₹1,89,000₹2,35,000Parsvnath City Mall, FaridabadHomeUsed CarsRohtak45k+ Happy Drives storiesPreviousCame here for a pre-owned car and found the best! The team's support exceeded my expectations. Extremely happy with my experience.Mahi PawarHonda CRVI had a smooth car buying experience. I was able to find a car that perfectly matched my requirements from a wide array of options.Pruthvi ZalaHonda BrioThe sales team at CARS24 provided outstanding service, and the finance team delivered incredibly fast service.Deepak DabhiMaruti XL6Customer-centric service, thorough explanations about cars and processes. Had a positive experience with CARS24.GunasekaranMaruti DzireDelighted with my car! The finance and sales teams provided fantastic support. I received the car within a day, and I'm extremely happy.Rahul NayakMaruti SwiftI had the best car-buying experience. From car finalizing to test drive, finance, and car handover, it was a breeze.Rajesh RajMaruti CelerioI bought a Grand i10 from CARS24, and it's the best car for the price. The zero down payment option made it affordable.Parmeshwar TelangHyundai Grand i10CARS24 offers a wide range of good-quality cars, and I couldn't be happier with my choice. Highly recommend!Ashvin ChauhanHyundai XcentCARS24's service was exceptional, and I was impressed by the wide range of cars available. Highly satisfied!Ajay AryaVolkswagen VentoCARS24 is the best place to buy a car. The team helped me find the perfect car that suited my needs perfectly.Bharat PatelFord EcosportCARS24 team was incredibly helpful throughout the process, ensuring everything went smoothly.Chandan ShettyMahindra Kuv100The wide range of cars available impressed me, and because of the finance team, I could easily secure my purchase.Paras PahujaHyundai VernaNextFrequently asked questions RohtakWhat are the most popular brands available for 2nd hand cars in Rohtak?CARS24 has a wide inventory of all brands including Maruti Suzuki, Hyundai, Honda & more. Find the best second hand car in Rohtak of your choice on CARS24.What body types are available for 2nd hand cars in Rohtak?Used cars in Rohtak are available from every segment, be it Hatchback, Sedan, SUV.Can I buy used cars online at CARS24 in Rohtak?Of Course yes, you can buy used cars online in Rohtak from CARS24. You can find thousands of quality second hand cars for sale on our website/app that can be bought at the click of a button & delivered to your doorstep anywhere in RohtakWhat to check before buying a second hand car in Rohtak?Important things to check  before buying a second hand car in Rohtak are:Source: Buying a car from a trusted source is important to make sure the car is in the exact condition as stated & also to deal with any post sale related issues.Condition: Ensure the car is non-accidental & does not have any structural damage. We use a 140 point check to make sure every car we sell is in top condition.Age: Buying a used car that is very old can lead to problems like expensive maintenance costs and scarcity of spare parts. A three to five year old car should be an ideal buy,Car Documents: Verification of vehicle documents like Registration Certificate (RC), Insurance & PUC is very important. Also ensure the car is not under loan (hypothecated), there are no traffic challans or any legal issues with it.Certified or Not: Certified used cars come with warranty and are refurbished to as good as new to protect buyers from unforeseen repair & maintenance cost.Where can I buy used cars in Rohtak?You can buy used cars in Rohtak from Cars24. Visit our website, book the car of your choice & get it delivered to your home.How can I check a second hand car in Rohtak?You can check second hand cars in Rohtak using conventional & time consuming buying methods like classified, dealers etc. CARS24 brings you a virtual showroom experience at your fingertips using 360 view. You can check multiple cars for sale in minutes and buy one from the comfort of your couch. We’ll deliver the car anywhere in RohtakHow many second hand cars are available in Rohtak?187 used cars are available in Rohtak of popular brands like Maruti Suzuki, Hyundai, Honda & moreview all faqsUsed Cars in IndiaCities :Used Cars in BangaloreUsed Cars in MumbaiUsed Cars in HyderabadUsed Cars in ChennaiUsed Cars in PuneUsed Cars in New DelhiUsed Cars in AhmedabadUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in KolkataUsed Cars in ChandigarhUsed Cars in PatnaUsed Cars in KochiUsed Cars in GhaziabadUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurUsed Cars in SuratUsed Cars in RajkotUsed Cars in IndoreUsed Cars in NagpurUsed Cars in VadodaraUsed Cars in CoimbatoreUsed Cars in NashikUsed Cars in AgraUsed Cars in LudhianaUsed Cars in RohtakUsed Cars in KanpurUsed Cars in VijayawadaUsed Cars in BhopalMake :Used Maruti Cars in RohtakUsed Hyundai Cars in RohtakUsed Tata Cars in RohtakUsed Toyota Cars in RohtakUsed Honda Cars in RohtakUsed Nissan Cars in RohtakUsed Volkswagen Cars in RohtakUsed Renault Cars in RohtakUsed Datsun Cars in RohtakUsed Ford Cars in RohtakBody :Used Hatchback Cars in RohtakUsed SUV Cars in RohtakUsed Sedan Cars in RohtakFuel :Used Petrol Cars in RohtakUsed CNG Cars in RohtakUsed Diesel Cars in RohtakBudget :Used Cars between 5 to 10 lakhs in RohtakUsed Cars between 2 to 5 lakhs in RohtakUsed Cars under 2 lakhs in RohtakUsed Cars above 10 lakhs in RohtakModel :Used Hyundai i10 Cars in RohtakUsed Maruti Wagon R Cars in RohtakUsed Maruti Dzire Cars in RohtakUsed Hyundai Creta Cars in RohtakUsed Tata NEXON Cars in RohtakUsed Hyundai i20 Cars in RohtakUsed Maruti Celerio Cars in RohtakUsed Tata TIGOR Cars in RohtakUsed Maruti Ertiga Cars in RohtakUsed Maruti Swift Cars in RohtakUsed Hyundai Santro Cars in RohtakUsed Hyundai VENUE Cars in RohtakUsed Tata ALTROZ Cars in RohtakUsed Maruti Ciaz Cars in RohtakUsed Hyundai AURA Cars in RohtakUsed Maruti Alto Cars in RohtakUsed Maruti Zen Estilo Cars in RohtakUsed Maruti Baleno Cars in RohtakUsed Maruti Brezza Cars in RohtakUsed Datsun Redi Go Cars in RohtakTransmission :Used Manual CarsUsed Automatic CarsKEEP IN TOUCHEXPERIENCE CARS24 APP ON MOBILEPowered by CARS24USEFUL LINKSContact UsSecurityMotor insuranceAbout UsPrivacy PolicyTerms and ConditionsFAQTestimonialsBlogWe're Hiring!Become Our PartnerNeed a LoanRC Transfer StatusCARS24 FinanceInvestorsPOPULAR SEARCHESCheck challanCARS24 PricingSell Used CarVehicle Ownership TransferUsed Car ValuationOTHER GEOGRAPHIESUAEThailandAustraliaNeed help?Help\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [167]:
Year=[]
car_name=[]
Add = []
Kmt=[]
fuel=[]
Trans=[]
Price = []
for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= r"\b\d{4}\b"
    regex= re.findall(pattern,year)
    if regex:
        Year.append(regex[0])
    else:
        Year.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    year = i.find('h3',class_='_2lmIw').text
    pattern= " \w+"
    regex= re.findall(pattern,year)
    if regex:
        car_name.append(regex)
    else:
        car_name.append(np.nan)

for i in soup.find_all('div',class_="_2z-Yu"):
    add = i.find('span',class_="_3DYbK")
    if add:
        Add.append(add.text)
    else:
        Add.append(np.nan)
Kmt=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"\d{1,3},\d{2,3}|[,]\d{1,3}"
    regex= re.findall(pattern,kmt)
    if regex:
        Kmt.append(regex)
    else:
        Kmt.append(np.nan)

fuel=[]
for i in soup.find_all('div',class_="_2z-Yu"):
    kmt = i.find('ul',class_='_13yb6').text
    pattern= r"Petrol|Diesel"
    regex= re.findall(pattern,kmt)
    if regex:
        fuel.append(regex)
    else:
        fuel.append(np.nan)



for i in soup.find_all('div',class_="_2z-Yu"):
    trans = i.find('ul',class_='_1hOnS').text
    pattern= r"Manual|Automatic"
    regex= re.findall(pattern,trans)
    if regex:
        Trans.append(regex)
    else:
        Trans.append(np.nan)


for i in soup.find_all('div',class_="_2z-Yu"):
    price= i.find('div',class_="_18ToE").text
    yoo = price.split("₹")[1].replace(",","")
    Price.append(yoo)
    
    
print(Year)
print(car_name)
print(Add)
print(Kmt)
print(fuel)
print(Trans)
print(Price)

['2011', '2012', '2015', '2022', '2017', '2021', '2017', '2022', '2019', '2019', '2017', '2018', '2013', '2019', '2010', '2014', '2023', '2017', '2015', '2011']
[[' Hyundai', ' i20'], [' Maruti', ' Swift', ' Dzire'], [' Honda', ' City'], [' Tata', ' PUNCH'], [' Maruti', ' Wagon', ' R', ' 1'], [' Tata', ' ALTROZ'], [' Hyundai', ' Elite', ' i20'], [' Hyundai', ' NEW', ' I20'], [' Maruti', ' Baleno'], [' Hyundai', ' Xcent'], [' Maruti', ' Baleno'], [' Maruti', ' Wagon', ' R', ' 1'], [' Hyundai', ' Santro', ' Xing'], [' Maruti', ' Alto', ' K10'], [' Maruti', ' Zen', ' Estilo'], [' Hyundai', ' Grand', ' i10'], [' Maruti', ' BREZZA'], [' Maruti', ' Celerio'], [' Hyundai', ' Grand', ' i10'], [' Maruti', ' Swift']]
['Parsvnath City Mall, Faridabad', 'Sector 33, Rohtak', 'Parsvnath City Mall, Faridabad', 'Parsvnath City Mall, Faridabad', 'Parsvnath City Mall, Faridabad', 'Parsvnath City Mall, Faridabad', 'Sector 33, Rohtak', 'Sector 33, Rohtak', 'Parsvnath City Mall, Faridabad', 'Parsvnath City Mall, Faridabad', 'Parsvnath City Mall, Faridabad', 'Sector 33, Rohtak', 'Parsvnath City Mall, Faridabad', 'Parsvnath City Mall, Faridabad', 'Sector 33, Rohtak', 'Parsvnath City Mall, Faridabad', 'Parsvnath City Mall, Faridabad', 'Parsvnath City Mall, Faridabad', 'Sector 33, Rohtak', 'Parsvnath City Mall, Faridabad']
[['89,507'], ['93,869'], ['24,569'], ['21,566'], ['71,802'], ['20,955'], ['66,802'], ['12,181'], ['22,963'], ['50,971'], ['56,740'], ['78,642'], ['61,788'], ['54,914'], ['56,172'], ['26,218'], ['11,948'], ['1,18', ',486'], ['90,358'], ['81,771']]
[['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], nan, ['Petrol'], nan, ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], nan, ['Petrol'], nan, ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol'], ['Petrol']]
[['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Manual'], ['Automatic'], ['Manual'], ['Manual'], ['Manual'], ['Manual']]
['230000', '263000', '482000', '617000', '365000', '533000', '568000', '705700', '617000', '464000', '494000', '361000', '201000', '327000', '115000', '458000', '1190000', '325000', '351000', '189000']

In [168]:
dicto26 = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':Kmt,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}

In [169]:
kmt1 = []
dicto26["Kmt run"]
for i in dicto26["Kmt run"]:
    a = str(i).replace('[','')
    b = a.replace(' ','')
    c = b.replace(',','')
    d = c.replace(']','')
    e = d.replace("''",'')
    kmt1.append(int(e.strip("'")))

dicto26n = {'Name of Cars':car_name,'Registration Year':Year,'Kmt run':kmt1,'Transmission':Trans,'Fuel type':fuel,'Price':Price,'Location of car':Add}
dicto26n

{'Name of Cars': [[' Hyundai', ' i20'],
  [' Maruti', ' Swift', ' Dzire'],
  [' Honda', ' City'],
  [' Tata', ' PUNCH'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Tata', ' ALTROZ'],
  [' Hyundai', ' Elite', ' i20'],
  [' Hyundai', ' NEW', ' I20'],
  [' Maruti', ' Baleno'],
  [' Hyundai', ' Xcent'],
  [' Maruti', ' Baleno'],
  [' Maruti', ' Wagon', ' R', ' 1'],
  [' Hyundai', ' Santro', ' Xing'],
  [' Maruti', ' Alto', ' K10'],
  [' Maruti', ' Zen', ' Estilo'],
  [' Hyundai', ' Grand', ' i10'],
  [' Maruti', ' BREZZA'],
  [' Maruti', ' Celerio'],
  [' Hyundai', ' Grand', ' i10'],
  [' Maruti', ' Swift']],
 'Registration Year': ['2011',
  '2012',
  '2015',
  '2022',
  '2017',
  '2021',
  '2017',
  '2022',
  '2019',
  '2019',
  '2017',
  '2018',
  '2013',
  '2019',
  '2010',
  '2014',
  '2023',
  '2017',
  '2015',
  '2011'],
 'Kmt run': [89507,
  93869,
  24569,
  21566,
  71802,
  20955,
  66802,
  12181,
  22963,
  50971,
  56740,
  78642,
  61788,
  54914,
  56172,
  26218,
  11948,
  118486,
  90358,
  81771],
 'Transmission': [['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Automatic'],
  ['Manual'],
  ['Manual'],
  ['Manual'],
  ['Manual']],
 'Fuel type': [['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  nan,
  ['Petrol'],
  nan,
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  nan,
  ['Petrol'],
  nan,
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol'],
  ['Petrol']],
 'Price': ['230000',
  '263000',
  '482000',
  '617000',
  '365000',
  '533000',
  '568000',
  '705700',
  '617000',
  '464000',
  '494000',
  '361000',
  '201000',
  '327000',
  '115000',
  '458000',
  '1190000',
  '325000',
  '351000',
  '189000'],
 'Location of car': ['Parsvnath City Mall, Faridabad',
  'Sector 33, Rohtak',
  'Parsvnath City Mall, Faridabad',
  'Parsvnath City Mall, Faridabad',
  'Parsvnath City Mall, Faridabad',
  'Parsvnath City Mall, Faridabad',
  'Sector 33, Rohtak',
  'Sector 33, Rohtak',
  'Parsvnath City Mall, Faridabad',
  'Parsvnath City Mall, Faridabad',
  'Parsvnath City Mall, Faridabad',
  'Sector 33, Rohtak',
  'Parsvnath City Mall, Faridabad',
  'Parsvnath City Mall, Faridabad',
  'Sector 33, Rohtak',
  'Parsvnath City Mall, Faridabad',
  'Parsvnath City Mall, Faridabad',
  'Parsvnath City Mall, Faridabad',
  'Sector 33, Rohtak',
  'Parsvnath City Mall, Faridabad']}

#### Creating Data Frame using pandas

In [170]:
import pandas as pd

In [171]:
df1 = pd.DataFrame(dicton)
df2 = pd.DataFrame(dicto2n)
df3 = pd.DataFrame(dicto3n)
df4 = pd.DataFrame(dicto4n)
df5 = pd.DataFrame(dicto5n)
df6 = pd.DataFrame(dicto6n)
df7 = pd.DataFrame(dicto7n)
df8 = pd.DataFrame(dicto8n)
df9 = pd.DataFrame(dicto9n)
df10 = pd.DataFrame(dicto10n)
df11 = pd.DataFrame(dicto11n)
df12 = pd.DataFrame(dicto12n)
df13 = pd.DataFrame(dicto13n)
df14 = pd.DataFrame(dicto14n)
df15 = pd.DataFrame(dicto15n)
df16 = pd.DataFrame(dicto16n)
df17 = pd.DataFrame(dicto17n)
df18 = pd.DataFrame(dicto18n)
df19 = pd.DataFrame(dicto19n)
df20 = pd.DataFrame(dicto20n)
df21 = pd.DataFrame(dicto21n)
df22 = pd.DataFrame(dicto22n)
df23 = pd.DataFrame(dicto23n)
df24 = pd.DataFrame(dicto24n)
df25 = pd.DataFrame(dicto25n)
df26 = pd.DataFrame(dicto26n)

In [172]:
df = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,df21,df22,df23,df24,df25,df26],axis=0,ignore_index=True)

In [173]:
df

,Name of Cars,Registration Year,Kmt run,Transmission,Fuel type,Price,Location of car
0,"[ Hyundai, i10]",2010,57942,[Manual],[Petrol],247000,"Attapur, Hyderabad"
1,"[ Hyundai, Grand, i10]",2016,75568,[Manual],[Petrol],453000,"Attapur, Hyderabad"
2,"[ Maruti, Ciaz]",2021,41362,[Manual],[Petrol],819000,"Kompally, Hyderabad"
3,"[ Honda, WR]",2017,53535,[Manual],[Diesel],661000,"Bachupally, Hyderabad"
4,"[ Maruti, Baleno]",2017,41260,[Automatic],[Petrol],591000,"Vanasthalipuram, Hyderabad.\n"
...,...,...,...,...,...,...,...
515,"[ Hyundai, Grand, i10]",2014,26218,[Automatic],[Petrol],458000,"Parsvnath City Mall, Faridabad"
516,"[ Maruti, BREZZA]",2023,11948,[Manual],[Petrol],1190000,"Parsvnath City Mall, Faridabad"
517,"[ Maruti, Celerio]",2017,118486,[Manual],[Petrol],325000,"Parsvnath City Mall, Faridabad"
518,"[ Hyundai, Grand, i10]",2015,90358,[Manual],[Petrol],351000,"Sector 33, Rohtak"
519,"[ Maruti, Swift]",2011,81771,[Manual],[Petrol],189000,"Parsvnath City Mall, Faridabad"

#### Handling with structural errors

In [174]:
#For removing []for transmission colum
df['Transmission'] = df['Transmission'].apply(lambda x: x[0])

#For removing [] for fuel type column
def clean_fuel_type(fuel_list):
    if isinstance(fuel_list, list):
        return fuel_list[0]
    else:
        return fuel_list
df['Fuel type'] = df['Fuel type'].apply(clean_fuel_type)

#For creating one more column by extracting 
df['Brand']=[i[0] for i in df['Name of Cars']]

#For removing [] from them
df['Name Of Cars'] = [" ".join(i[0::]) for i in df['Name of Cars']]

#For new column order
new_order = ['Name Of Cars', 'Brand', 'Registration Year','Transmission','Fuel type','Kmt run','Price','Location of car','Name of Cars']
df = df.reindex(columns=new_order)

#For dropping column
df.drop('Name of Cars',axis=1,inplace=True)

#for removing \n from location column
df['Location of car'] = df['Location of car'].replace('.\n','',regex=True)


#to convert nan=np.nan
df["Kmt run"] = df["Kmt run"].replace("nan",np.nan)

In [175]:
df

,Name Of Cars,Brand,Registration Year,Transmission,Fuel type,Kmt run,Price,Location of car
0,Hyundai i10,Hyundai,2010,Manual,Petrol,57942,247000,"Attapur, Hyderabad"
1,Hyundai Grand i10,Hyundai,2016,Manual,Petrol,75568,453000,"Attapur, Hyderabad"
2,Maruti Ciaz,Maruti,2021,Manual,Petrol,41362,819000,"Kompally, Hyderabad"
3,Honda WR,Honda,2017,Manual,Diesel,53535,661000,"Bachupally, Hyderabad"
4,Maruti Baleno,Maruti,2017,Automatic,Petrol,41260,591000,"Vanasthalipuram, Hyderabad"
...,...,...,...,...,...,...,...,...
515,Hyundai Grand i10,Hyundai,2014,Automatic,Petrol,26218,458000,"Parsvnath City Mall, Faridabad"
516,Maruti BREZZA,Maruti,2023,Manual,Petrol,11948,1190000,"Parsvnath City Mall, Faridabad"
517,Maruti Celerio,Maruti,2017,Manual,Petrol,118486,325000,"Parsvnath City Mall, Faridabad"
518,Hyundai Grand i10,Hyundai,2015,Manual,Petrol,90358,351000,"Sector 33, Rohtak"
519,Maruti Swift,Maruti,2011,Manual,Petrol,81771,189000,"Parsvnath City Mall, Faridabad"

#### Handling with missing values

In [176]:
df.isna().sum()

Name Of Cars          0
Brand                 0
Registration Year     0
Transmission          0
Fuel type            35
Kmt run               1
Price                 0
Location of car       2
dtype: int64

In [177]:
df.dropna(axis=0,inplace=True)

In [178]:
df.isna().sum()

Name Of Cars         0
Brand                0
Registration Year    0
Transmission         0
Fuel type            0
Kmt run              0
Price                0
Location of car      0
dtype: int64

In [179]:
df.shape

(482, 8)

#### Handling with Duplicate values

In [180]:
df.duplicated().sum()

68

In [181]:
df.drop_duplicates(inplace=True,ignore_index=True)

In [182]:
df.shape

(414, 8)

#### Handling with Typecasting

In [183]:
df.dtypes

Name Of Cars         object
Brand                object
Registration Year    object
Transmission         object
Fuel type            object
Kmt run              object
Price                object
Location of car      object
dtype: object

In [184]:
df['Registration Year'] = df['Registration Year'].astype('int32')
df['Kmt run'] = df['Kmt run'].astype('int64')
df['Price'] = df['Price'].astype('int64')

In [185]:
df.dtypes

Name Of Cars         object
Brand                object
Registration Year     int32
Transmission         object
Fuel type            object
Kmt run               int64
Price                 int64
Location of car      object
dtype: object

#### Handling with Incorrect Format of the data (Invalid Values, Columns)

In [186]:
df['City Name'] = [i.split(",")[-1] for i in df['Location of car']]


new = []
for i in df['Location of car']:
    if ',' in i:
        new.append(i.split(",")[0])
    else:
        new.append(i)
        
df['Location_of_car'] = new

In [187]:
df['Location of car'] = df['Location of car'].str.strip().replace(" Benga...","Bengaluru")
df['City Name'] = df['City Name'].str.strip().replace("Benga...","Bengaluru")
df['City Name'] = df['City Name'].str.strip().replace("Chenna","Chennai")
df['City Name'] = df['City Name'].str.strip().replace("Patn","Patna")
df['City Name'] = df['City Name'].str.strip().replace("Agr","Agra")
df['City Name'] = df['City Name'].str.strip().replace("Mansarovar","Jaipur")
df['City Name'] = df['City Name'].str.strip().replace("Lasudia Mori","Indore")
df['City Name'] = df['City Name'].str.strip().replace("Navalur","Chennai")
df['City Name'] = df['City Name'].str.strip().replace("Sonnappanahall","Bengaluru")
df['City Name'] = df['City Name'].str.strip().replace("Mulun","Mumbai")

In [188]:
df.drop('Location of car',axis=1,inplace=True)

In [189]:
df

,Name Of Cars,Brand,Registration Year,Transmission,Fuel type,Kmt run,Price,City Name,Location_of_car
0,Hyundai i10,Hyundai,2010,Manual,Petrol,57942,247000,Hyderabad,Attapur
1,Hyundai Grand i10,Hyundai,2016,Manual,Petrol,75568,453000,Hyderabad,Attapur
2,Maruti Ciaz,Maruti,2021,Manual,Petrol,41362,819000,Hyderabad,Kompally
3,Honda WR,Honda,2017,Manual,Diesel,53535,661000,Hyderabad,Bachupally
4,Maruti Baleno,Maruti,2017,Automatic,Petrol,41260,591000,Hyderabad,Vanasthalipuram
...,...,...,...,...,...,...,...,...,...
409,Hyundai Grand i10,Hyundai,2014,Automatic,Petrol,26218,458000,Faridabad,Parsvnath City Mall
410,Maruti BREZZA,Maruti,2023,Manual,Petrol,11948,1190000,Faridabad,Parsvnath City Mall
411,Maruti Celerio,Maruti,2017,Manual,Petrol,118486,325000,Faridabad,Parsvnath City Mall
412,Hyundai Grand i10,Hyundai,2015,Manual,Petrol,90358,351000,Rohtak,Sector 33
413,Maruti Swift,Maruti,2011,Manual,Petrol,81771,189000,Faridabad,Parsvnath City Mall

In [190]:
new_order = ['Name Of Cars', 'Brand', 'Registration Year','Transmission','Fuel type','Kmt run','Price','Location_of_car','City Name']
df = df.reindex(columns=new_order)

In [191]:
df.rename(columns = {'Name Of Cars':'Name of Vehicle'},inplace =True)
df.rename(columns = {'Brand':'Brand of Vehicle'},inplace =True)
df.rename(columns = {'Location_of_car':'Location of Vehicle'},inplace =True)
df.rename(columns = {'City Name':'Name of City'},inplace =True)

In [192]:
df.rename(columns = {'Kmt run':'Kilometers Run'},inplace =True)

In [193]:
df

,Name of Vehicle,Brand of Vehicle,Registration Year,Transmission,Fuel type,Kilometers Run,Price,Location of Vehicle,Name of City
0,Hyundai i10,Hyundai,2010,Manual,Petrol,57942,247000,Attapur,Hyderabad
1,Hyundai Grand i10,Hyundai,2016,Manual,Petrol,75568,453000,Attapur,Hyderabad
2,Maruti Ciaz,Maruti,2021,Manual,Petrol,41362,819000,Kompally,Hyderabad
3,Honda WR,Honda,2017,Manual,Diesel,53535,661000,Bachupally,Hyderabad
4,Maruti Baleno,Maruti,2017,Automatic,Petrol,41260,591000,Vanasthalipuram,Hyderabad
...,...,...,...,...,...,...,...,...,...
409,Hyundai Grand i10,Hyundai,2014,Automatic,Petrol,26218,458000,Parsvnath City Mall,Faridabad
410,Maruti BREZZA,Maruti,2023,Manual,Petrol,11948,1190000,Parsvnath City Mall,Faridabad
411,Maruti Celerio,Maruti,2017,Manual,Petrol,118486,325000,Parsvnath City Mall,Faridabad
412,Hyundai Grand i10,Hyundai,2015,Manual,Petrol,90358,351000,Sector 33,Rohtak
413,Maruti Swift,Maruti,2011,Manual,Petrol,81771,189000,Parsvnath City Mall,Faridabad

#### Saving file.csv

In [194]:
df.to_csv('WebScrapping&Data_Cleaning_Project.csv')